/**
 * AUTO-GENERATED by scripts/generate-education-manifest.mjs — do not edit by hand.
 * 181 documents across 5 categories.
 */
export type EducationDocument = {
  id: string;
  title: string;
  href: string;
  filename: string;
  description?: string;
  subcategory?: string;
  tags?: string[];
};

export type EducationCategory = {
  id: string;
  title: string;
  description: string;
  documents: EducationDocument[];
};

export const EDUCATION_CATEGORIES: EducationCategory[] = [
  {
    "id": "landmark-articles",
    "title": "Landmark articles",
    "description": "Seminal papers by diagnosis and topic — program reading list.",
    "documents": [
      {
        "id": "landmark-articles-anxiety-disorders-barlow-et-al-cognitive-behavioral-therapy-im",
        "title": "Barlow et al. Cognitive behavioral therapy, imipramine, or their combinati",
        "href": "/content/uh-psych/landmark-articles/Anxiety%20Disorders/Barlow%20et%20al.%20-%20Cognitive-behavioral%20therapy%2C%20imipramine%2C%20or%20their%20combinati.pdf",
        "filename": "Barlow et al. - Cognitive-behavioral therapy, imipramine, or their combinati.pdf",
        "subcategory": "Anxiety Disorders"
      },
      {
        "id": "landmark-articles-anxiety-disorders-bighelli-et-al-antidepressants-versus-placeb",
        "title": "Bighelli et al. Antidepressants versus placebo for panic disorder in adults",
        "href": "/content/uh-psych/landmark-articles/Anxiety%20Disorders/Bighelli%20et%20al.%20-%20Antidepressants%20versus%20placebo%20for%20panic%20disorder%20in%20adults.pdf",
        "filename": "Bighelli et al. - Antidepressants versus placebo for panic disorder in adults.pdf",
        "subcategory": "Anxiety Disorders"
      },
      {
        "id": "landmark-articles-anxiety-disorders-davidson-et-al-fluoxetine-comprehensive-cogn",
        "title": "Davidson et al. Fluoxetine, comprehensive cognitive behavioral therapy, and",
        "href": "/content/uh-psych/landmark-articles/Anxiety%20Disorders/Davidson%20et%20al.%20-%20Fluoxetine%2C%20comprehensive%20cognitive%20behavioral%20therapy%2C%20and%20.pdf",
        "filename": "Davidson et al. - Fluoxetine, comprehensive cognitive behavioral therapy, and .pdf",
        "subcategory": "Anxiety Disorders"
      },
      {
        "id": "landmark-articles-appelbaum-assessment-of-patients-competence-to-consent-to-trea",
        "title": "Appelbaum Assessment of Patients Competence to Consent to Treatment",
        "href": "/content/uh-psych/landmark-articles/Appelbaum%20-%20Assessment%20of%20Patients_%20Competence%20to%20Consent%20to%20Treatment.pdf",
        "filename": "Appelbaum - Assessment of Patients_ Competence to Consent to Treatment.pdf"
      },
      {
        "id": "landmark-articles-bipolar-disorder-balance-investigators-and-collaborators-et-al",
        "title": "BALANCE investigators and collaborators et al. Lithium plus valproate combination therapy versus monotherapy for relapse preven",
        "href": "/content/uh-psych/landmark-articles/Bipolar%20Disorder/BALANCE%20investigators%20and%20collaborators%20et%20al.%20-%20Lithium%20plus%20valproate%20combination%20therapy%20versus%20monotherapy%20for%20relapse%20preven.pdf",
        "filename": "BALANCE investigators and collaborators et al. - Lithium plus valproate combination therapy versus monotherapy for relapse preven.pdf",
        "subcategory": "Bipolar Disorder"
      },
      {
        "id": "landmark-articles-bipolar-disorder-cade-lithium-salts-in-the-treatment-of-psycho",
        "title": "Cade Lithium salts in the treatment of psychotic excitement. 1949",
        "href": "/content/uh-psych/landmark-articles/Bipolar%20Disorder/Cade%20-%20Lithium%20salts%20in%20the%20treatment%20of%20psychotic%20excitement.%201949.pdf",
        "filename": "Cade - Lithium salts in the treatment of psychotic excitement. 1949.pdf",
        "subcategory": "Bipolar Disorder"
      },
      {
        "id": "landmark-articles-bipolar-disorder-cipriani-et-al-comparative-efficacy-and-accep",
        "title": "Cipriani et al. Comparative efficacy and acceptability of antimanic drugs in",
        "href": "/content/uh-psych/landmark-articles/Bipolar%20Disorder/Cipriani%20et%20al.%20-%20Comparative%20efficacy%20and%20acceptability%20of%20antimanic%20drugs%20in.pdf",
        "filename": "Cipriani et al. - Comparative efficacy and acceptability of antimanic drugs in.pdf",
        "subcategory": "Bipolar Disorder"
      },
      {
        "id": "landmark-articles-bipolar-disorder-cipriani-et-al-lithium-in-the-prevention-of-s",
        "title": "Cipriani et al. Lithium in the prevention of suicide in mood disorders upda",
        "href": "/content/uh-psych/landmark-articles/Bipolar%20Disorder/Cipriani%20et%20al.%20-%20Lithium%20in%20the%20prevention%20of%20suicide%20in%20mood%20disorders%20upda.pdf",
        "filename": "Cipriani et al. - Lithium in the prevention of suicide in mood disorders upda.pdf",
        "subcategory": "Bipolar Disorder"
      },
      {
        "id": "landmark-articles-bipolar-disorder-geddes-and-miklowitz-treatment-of-bipolar-dis",
        "title": "Geddes and Miklowitz Treatment of bipolar disorder",
        "href": "/content/uh-psych/landmark-articles/Bipolar%20Disorder/Geddes%20and%20Miklowitz%20-%20Treatment%20of%20bipolar%20disorder.pdf",
        "filename": "Geddes and Miklowitz - Treatment of bipolar disorder.pdf",
        "subcategory": "Bipolar Disorder"
      },
      {
        "id": "landmark-articles-bipolar-disorder-janowsky-et-al-playing-the-manic-game-interpe",
        "title": "Janowsky et al. Playing the manic game. Interpersonal maneuvers of the acute",
        "href": "/content/uh-psych/landmark-articles/Bipolar%20Disorder/Janowsky%20et%20al.%20-%20Playing%20the%20manic%20game.%20Interpersonal%20maneuvers%20of%20the%20acute.pdf",
        "filename": "Janowsky et al. - Playing the manic game. Interpersonal maneuvers of the acute.pdf",
        "subcategory": "Bipolar Disorder"
      },
      {
        "id": "landmark-articles-bipolar-disorder-mcknight-et-al-lithium-toxicity-profile-a-sys",
        "title": "McKnight et al. Lithium toxicity profile a systematic review and meta analy",
        "href": "/content/uh-psych/landmark-articles/Bipolar%20Disorder/McKnight%20et%20al.%20-%20Lithium%20toxicity%20profile%20a%20systematic%20review%20and%20meta-analy.pdf",
        "filename": "McKnight et al. - Lithium toxicity profile a systematic review and meta-analy.pdf",
        "subcategory": "Bipolar Disorder"
      },
      {
        "id": "landmark-articles-bipolar-disorder-miklowitz-et-al-psychosocial-treatments-for-b",
        "title": "Miklowitz et al. Psychosocial treatments for bipolar depression a 1 year ran",
        "href": "/content/uh-psych/landmark-articles/Bipolar%20Disorder/Miklowitz%20et%20al.%20-%20Psychosocial%20treatments%20for%20bipolar%20depression%20a%201-year%20ran.pdf",
        "filename": "Miklowitz et al. - Psychosocial treatments for bipolar depression a 1-year ran.pdf",
        "subcategory": "Bipolar Disorder"
      },
      {
        "id": "landmark-articles-bipolar-disorder-nierenberg-et-al-treatment-resistant-bipolar-",
        "title": "Nierenberg et al. Treatment resistant bipolar depression a STEP BD equipoise",
        "href": "/content/uh-psych/landmark-articles/Bipolar%20Disorder/Nierenberg%20et%20al.%20-%20Treatment-resistant%20bipolar%20depression%20a%20STEP-BD%20equipoise%20.pdf",
        "filename": "Nierenberg et al. - Treatment-resistant bipolar depression a STEP-BD equipoise .pdf",
        "subcategory": "Bipolar Disorder"
      },
      {
        "id": "landmark-articles-bipolar-disorder-sachs-et-al-effectiveness-of-adjunctive-antid",
        "title": "Sachs et al. Effectiveness of Adjunctive Antidepressant Treatment for Bip",
        "href": "/content/uh-psych/landmark-articles/Bipolar%20Disorder/Sachs%20et%20al.%20-%20Effectiveness%20of%20Adjunctive%20Antidepressant%20Treatment%20for%20Bip.pdf",
        "filename": "Sachs et al. - Effectiveness of Adjunctive Antidepressant Treatment for Bip.pdf",
        "subcategory": "Bipolar Disorder"
      },
      {
        "id": "landmark-articles-child-and-adolescent-cortese-et-al-comparative-efficacy-and-to",
        "title": "Cortese et al. Comparative efficacy and tolerability of medications for att",
        "href": "/content/uh-psych/landmark-articles/Child%20and%20Adolescent/Cortese%20et%20al.%20-%20Comparative%20efficacy%20and%20tolerability%20of%20medications%20for%20att.pdf",
        "filename": "Cortese et al. - Comparative efficacy and tolerability of medications for att.pdf",
        "subcategory": "Child and Adolescent"
      },
      {
        "id": "landmark-articles-child-and-adolescent-piacentini-et-al-24-and-36-week-outcomes-",
        "title": "Piacentini et al. 24 and 36 week outcomes for the ChildAdolescent Anxiety Mu",
        "href": "/content/uh-psych/landmark-articles/Child%20and%20Adolescent/Piacentini%20et%20al.%20-%2024-%20and%2036-week%20outcomes%20for%20the%20ChildAdolescent%20Anxiety%20Mu.pdf",
        "filename": "Piacentini et al. - 24- and 36-week outcomes for the ChildAdolescent Anxiety Mu.pdf",
        "subcategory": "Child and Adolescent"
      },
      {
        "id": "landmark-articles-child-and-adolescent-rutter-and-sroufe-developmental-psychopat",
        "title": "Rutter and Sroufe Developmental psychopathology concepts and challenges",
        "href": "/content/uh-psych/landmark-articles/Child%20and%20Adolescent/Rutter%20and%20Sroufe%20-%20Developmental%20psychopathology%20concepts%20and%20challenges.pdf",
        "filename": "Rutter and Sroufe - Developmental psychopathology concepts and challenges.pdf",
        "subcategory": "Child and Adolescent"
      },
      {
        "id": "landmark-articles-child-and-adolescent-sharma-et-al-suicidality-and-aggression-d",
        "title": "Sharma et al. Suicidality and aggression during antidepressant treatment",
        "href": "/content/uh-psych/landmark-articles/Child%20and%20Adolescent/Sharma%20et%20al.%20-%20Suicidality%20and%20aggression%20during%20antidepressant%20treatment%20.pdf",
        "filename": "Sharma et al. - Suicidality and aggression during antidepressant treatment .pdf",
        "subcategory": "Child and Adolescent"
      },
      {
        "id": "landmark-articles-cl-appelbaum-assessment-of-patients-competence-to-consent-to-t",
        "title": "Appelbaum Assessment of Patients Competence to Consent to Treatment",
        "href": "/content/uh-psych/landmark-articles/CL/Appelbaum%20-%20Assessment%20of%20Patients_%20Competence%20to%20Consent%20to%20Treatment.pdf",
        "filename": "Appelbaum - Assessment of Patients_ Competence to Consent to Treatment.pdf",
        "subcategory": "CL"
      },
      {
        "id": "landmark-articles-conceptual-frameworks-and-perspectives-in-psychiatry-kendler-e",
        "title": "Kendler Explanatory Models for Psychiatric Illness",
        "href": "/content/uh-psych/landmark-articles/Conceptual%20Frameworks%20and%20Perspectives%20in%20Psychiatry/Kendler%20-%20Explanatory%20Models%20for%20Psychiatric%20Illness.pdf",
        "filename": "Kendler - Explanatory Models for Psychiatric Illness.pdf",
        "subcategory": "Conceptual Frameworks and Perspectives in Psychiatry"
      },
      {
        "id": "landmark-articles-depressive-disorders-beck-the-evolution-of-the-cognitive-model",
        "title": "Beck The evolution of the cognitive model of depression and its n",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/Beck%20-%20The%20evolution%20of%20the%20cognitive%20model%20of%20depression%20and%20its%20n.pdf",
        "filename": "Beck - The evolution of the cognitive model of depression and its n.pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-cipriani-et-al-comparative-efficacy-and-a",
        "title": "Cipriani et al. Comparative efficacy and acceptability of 21 antidepressant",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/Cipriani%20et%20al.%20-%20Comparative%20efficacy%20and%20acceptability%20of%2021%20antidepressant%20.pdf",
        "filename": "Cipriani et al. - Comparative efficacy and acceptability of 21 antidepressant .pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-fava-can-long-term-treatment-with-antidep",
        "title": "Fava Can long term treatment with antidepressant drugs worsen the",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/Fava%20-%20Can%20long-term%20treatment%20with%20antidepressant%20drugs%20worsen%20the.pdf",
        "filename": "Fava - Can long-term treatment with antidepressant drugs worsen the.pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-gobbi-et-al-association-of-cannabis-use-i",
        "title": "Gobbi et al. Association of Cannabis Use in Adolescence and Risk of Depre",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/Gobbi%20et%20al.%20-%20Association%20of%20Cannabis%20Use%20in%20Adolescence%20and%20Risk%20of%20Depre.pdf",
        "filename": "Gobbi et al. - Association of Cannabis Use in Adolescence and Risk of Depre.pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-harmer-et-al-why-do-antidepressants-take-",
        "title": "Harmer et al. Why do antidepressants take so long to work A cognitive neu",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/Harmer%20et%20al.%20-%20Why%20do%20antidepressants%20take%20so%20long%20to%20work%20A%20cognitive%20neu.pdf",
        "filename": "Harmer et al. - Why do antidepressants take so long to work A cognitive neu.pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-kirsch-et-al-initial-severity-and-antidep",
        "title": "Kirsch et al. Initial severity and antidepressant benefits a meta analysi",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/Kirsch%20et%20al.%20-%20Initial%20severity%20and%20antidepressant%20benefits%20a%20meta-analysi.pdf",
        "filename": "Kirsch et al. - Initial severity and antidepressant benefits a meta-analysi.pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-kuhn-the-treatment-of-depressive-states-w",
        "title": "Kuhn The treatment of depressive states with G 22355 (imipramine",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/Kuhn%20-%20The%20treatment%20of%20depressive%20states%20with%20G%2022355%20(imipramine%20.pdf",
        "filename": "Kuhn - The treatment of depressive states with G 22355 (imipramine .pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-mcgrath-et-al-tranylcypromine-versus-venl",
        "title": "McGrath et al. Tranylcypromine versus venlafaxine plus mirtazapine followin",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/McGrath%20et%20al.%20-%20Tranylcypromine%20versus%20venlafaxine%20plus%20mirtazapine%20followin.pdf",
        "filename": "McGrath et al. - Tranylcypromine versus venlafaxine plus mirtazapine followin.pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-rosenblat-et-al-the-effect-of-pharmacogen",
        "title": "Rosenblat et al. The effect of pharmacogenomic testing on response and remiss",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/Rosenblat%20et%20al.%20-%20The%20effect%20of%20pharmacogenomic%20testing%20on%20response%20and%20remiss.pdf",
        "filename": "Rosenblat et al. - The effect of pharmacogenomic testing on response and remiss.pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-rush-et-al-acute-and-longer-term-outcomes",
        "title": "Rush et al. Acute and longer term outcomes in depressed outpatients requ",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/Rush%20et%20al.%20-%20Acute%20and%20longer-term%20outcomes%20in%20depressed%20outpatients%20requ.pdf",
        "filename": "Rush et al. - Acute and longer-term outcomes in depressed outpatients requ.pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-rush-et-al-bupropion-sr-sertraline-or-ven",
        "title": "Rush et al. Bupropion SR, sertraline, or venlafaxine XR after failure of",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/Rush%20et%20al.%20-%20Bupropion-SR%2C%20sertraline%2C%20or%20venlafaxine-XR%20after%20failure%20of.pdf",
        "filename": "Rush et al. - Bupropion-SR, sertraline, or venlafaxine-XR after failure of.pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-trivedi-et-al-evaluation-of-outcomes-with",
        "title": "Trivedi et al. Evaluation of outcomes with citalopram for depression using",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/Trivedi%20et%20al.%20-%20Evaluation%20of%20outcomes%20with%20citalopram%20for%20depression%20using%20.pdf",
        "filename": "Trivedi et al. - Evaluation of outcomes with citalopram for depression using .pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-trivedi-et-al-medication-augmentation-aft",
        "title": "Trivedi et al. Medication augmentation after the failure of SSRIs for depre",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/Trivedi%20et%20al.%20-%20Medication%20augmentation%20after%20the%20failure%20of%20SSRIs%20for%20depre.pdf",
        "filename": "Trivedi et al. - Medication augmentation after the failure of SSRIs for depre.pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-uk-ect-review-group-efficacy-and-safety-o",
        "title": "UK ECT Review Group Efficacy and safety of electroconvulsive therapy in depressi",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/UK%20ECT%20Review%20Group%20-%20Efficacy%20and%20safety%20of%20electroconvulsive%20therapy%20in%20depressi.pdf",
        "filename": "UK ECT Review Group - Efficacy and safety of electroconvulsive therapy in depressi.pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-depressive-disorders-west-and-dally-effects-of-iproniazid-in-d",
        "title": "West and Dally Effects of iproniazid in depressive syndromes",
        "href": "/content/uh-psych/landmark-articles/Depressive%20Disorders/West%20and%20Dally%20-%20Effects%20of%20iproniazid%20in%20depressive%20syndromes.pdf",
        "filename": "West and Dally - Effects of iproniazid in depressive syndromes.pdf",
        "subcategory": "Depressive Disorders"
      },
      {
        "id": "landmark-articles-narrative-reviews-abramowitz-et-al-obsessive-compulsive-disord",
        "title": "Abramowitz et al. Obsessive compulsive disorder",
        "href": "/content/uh-psych/landmark-articles/Narrative%20Reviews/Abramowitz%20et%20al.%20-%20Obsessive-compulsive%20disorder.pdf",
        "filename": "Abramowitz et al. - Obsessive-compulsive disorder.pdf",
        "subcategory": "Narrative Reviews"
      },
      {
        "id": "landmark-articles-narrative-reviews-treasure-et-al-eating-disorders-pdf",
        "title": "Treasure et al. Eating disorders",
        "href": "/content/uh-psych/landmark-articles/Narrative%20Reviews/Treasure%20et%20al.%20-%20Eating%20disorders.pdf",
        "filename": "Treasure et al. - Eating disorders.pdf",
        "subcategory": "Narrative Reviews"
      },
      {
        "id": "landmark-articles-narrative-reviews-yonkers-et-al-management-of-bipolar-disorder",
        "title": "Yonkers et al. Management of bipolar disorder during pregnancy and the post",
        "href": "/content/uh-psych/landmark-articles/Narrative%20Reviews/Yonkers%20et%20al.%20-%20Management%20of%20bipolar%20disorder%20during%20pregnancy%20and%20the%20post.pdf",
        "filename": "Yonkers et al. - Management of bipolar disorder during pregnancy and the post.pdf",
        "subcategory": "Narrative Reviews"
      },
      {
        "id": "landmark-articles-neurocognitive-disorders-schneider-et-al-effectiveness-of-atyp",
        "title": "Schneider et al. Effectiveness of Atypical Antipsychotic Drugs in Patients wi",
        "href": "/content/uh-psych/landmark-articles/Neurocognitive%20Disorders/Schneider%20et%20al.%20-%20Effectiveness%20of%20Atypical%20Antipsychotic%20Drugs%20in%20Patients%20wi.pdf",
        "filename": "Schneider et al. - Effectiveness of Atypical Antipsychotic Drugs in Patients wi.pdf",
        "subcategory": "Neurocognitive Disorders"
      },
      {
        "id": "landmark-articles-personality-disorders-groves-taking-care-of-the-hateful-patien",
        "title": "Groves Taking care of the hateful patient",
        "href": "/content/uh-psych/landmark-articles/Personality%20Disorders/Groves%20-%20Taking%20care%20of%20the%20hateful%20patient.pdf",
        "filename": "Groves - Taking care of the hateful patient.pdf",
        "subcategory": "Personality Disorders"
      },
      {
        "id": "landmark-articles-personality-disorders-vaillant-the-beginning-of-wisdom-is-neve",
        "title": "Vaillant The Beginning of Wisdom Is Never Calling a Patient a Borderl",
        "href": "/content/uh-psych/landmark-articles/Personality%20Disorders/Vaillant%20-%20The%20Beginning%20of%20Wisdom%20Is%20Never%20Calling%20a%20Patient%20a%20Borderl.pdf",
        "filename": "Vaillant - The Beginning of Wisdom Is Never Calling a Patient a Borderl.pdf",
        "subcategory": "Personality Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-agid-et-al-delayed-onset-hypo",
        "title": "Agid et al. Delayed onset hypothesis of antipsychotic action a hypothes",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Agid%20et%20al.%20-%20Delayed-onset%20hypothesis%20of%20antipsychotic%20action%20a%20hypothes.pdf",
        "filename": "Agid et al. - Delayed-onset hypothesis of antipsychotic action a hypothes.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-andreasen-et-al-relapse-durat",
        "title": "Andreasen et al. Relapse duration, treatment intensity, and brain tissue loss",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Andreasen%20et%20al.%20-%20Relapse%20duration%2C%20treatment%20intensity%2C%20and%20brain%20tissue%20loss.pdf",
        "filename": "Andreasen et al. - Relapse duration, treatment intensity, and brain tissue loss.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-chouinard-and-jones-neurolept",
        "title": "Chouinard and Jones Neuroleptic induced supersensitivity psychosis clinical and",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Chouinard%20and%20Jones%20-%20Neuroleptic-induced%20supersensitivity%20psychosis%20clinical%20and.pdf",
        "filename": "Chouinard and Jones - Neuroleptic-induced supersensitivity psychosis clinical and.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-cohen-and-correll-second-gene",
        "title": "Cohen and Correll Second Generation Antipsychotic–Associated Diabetes Mellitus",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Cohen%20and%20Correll%20-%20Second-Generation%20Antipsychotic%E2%80%93Associated%20Diabetes%20Mellitus.pdf",
        "filename": "Cohen and Correll - Second-Generation Antipsychotic–Associated Diabetes Mellitus.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-demjaha-et-al-dopamine-synthe",
        "title": "Demjaha et al. Dopamine synthesis capacity in patients with treatment resis",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Demjaha%20et%20al.%20-%20Dopamine%20synthesis%20capacity%20in%20patients%20with%20treatment-resis.pdf",
        "filename": "Demjaha et al. - Dopamine synthesis capacity in patients with treatment-resis.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-di-forti-et-al-the-contributi",
        "title": "Di Forti et al. The contribution of cannabis use to variation in the inciden",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Di%20Forti%20et%20al.%20-%20The%20contribution%20of%20cannabis%20use%20to%20variation%20in%20the%20inciden.pdf",
        "filename": "Di Forti et al. - The contribution of cannabis use to variation in the inciden.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-fletcher-and-frith-perceiving",
        "title": "Fletcher and Frith Perceiving is believing a Bayesian approach to explaining t",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Fletcher%20and%20Frith%20-%20Perceiving%20is%20believing%20a%20Bayesian%20approach%20to%20explaining%20t.pdf",
        "filename": "Fletcher and Frith - Perceiving is believing a Bayesian approach to explaining t.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-fusar-poli-et-al-the-psychosi",
        "title": "Fusar Poli et al. The psychosis high risk state a comprehensive state of the",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Fusar-Poli%20et%20al.%20-%20The%20psychosis%20high-risk%20state%20a%20comprehensive%20state-of-the-.pdf",
        "filename": "Fusar-Poli et al. - The psychosis high-risk state a comprehensive state-of-the-.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-honer-et-al-clozapine-alone-v",
        "title": "Honer et al. Clozapine Alone versus Clozapine and Risperidone with Refrac",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Honer%20et%20al.%20-%20Clozapine%20Alone%20versus%20Clozapine%20and%20Risperidone%20with%20Refrac.pdf",
        "filename": "Honer et al. - Clozapine Alone versus Clozapine and Risperidone with Refrac.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-jones-et-al-randomized-contro",
        "title": "Jones et al. Randomized controlled trial of the effect on Quality of Life",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Jones%20et%20al.%20-%20Randomized%20controlled%20trial%20of%20the%20effect%20on%20Quality%20of%20Life.pdf",
        "filename": "Jones et al. - Randomized controlled trial of the effect on Quality of Life.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-kahn-et-al-effectiveness-of-a",
        "title": "Kahn et al. Effectiveness of antipsychotic drugs in first episode schizo",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Kahn%20et%20al.%20-%20Effectiveness%20of%20antipsychotic%20drugs%20in%20first-episode%20schizo.pdf",
        "filename": "Kahn et al. - Effectiveness of antipsychotic drugs in first-episode schizo.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-kane-et-al-clozapine-for-the-",
        "title": "Kane et al. Clozapine for the treatment resistant schizophrenic. A doubl",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Kane%20et%20al.%20-%20Clozapine%20for%20the%20treatment-resistant%20schizophrenic.%20A%20doubl.pdf",
        "filename": "Kane et al. - Clozapine for the treatment-resistant schizophrenic. A doubl.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-kapur-psychosis-as-a-state-of",
        "title": "Kapur Psychosis as a state of aberrant salience a framework linki",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Kapur%20-%20Psychosis%20as%20a%20state%20of%20aberrant%20salience%20a%20framework%20linki.pdf",
        "filename": "Kapur - Psychosis as a state of aberrant salience a framework linki.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-lally-et-al-remission-and-rec",
        "title": "Lally et al. Remission and recovery from first episode psychosis in adult",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Lally%20et%20al.%20-%20Remission%20and%20recovery%20from%20first-episode%20psychosis%20in%20adult.pdf",
        "filename": "Lally et al. - Remission and recovery from first-episode psychosis in adult.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-leucht-et-al-comparative-effi",
        "title": "Leucht et al. Comparative efficacy and tolerability of 15 antipsychotic dr",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Leucht%20et%20al.%20-%20Comparative%20efficacy%20and%20tolerability%20of%2015%20antipsychotic%20dr.pdf",
        "filename": "Leucht et al. - Comparative efficacy and tolerability of 15 antipsychotic dr.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-lieberman-et-al-effectiveness",
        "title": "Lieberman et al. Effectiveness of Antipsychotic Drugs in Patients with Chroni",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Lieberman%20et%20al.%20-%20Effectiveness%20of%20Antipsychotic%20Drugs%20in%20Patients%20with%20Chroni.pdf",
        "filename": "Lieberman et al. - Effectiveness of Antipsychotic Drugs in Patients with Chroni.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-tiihonen-et-al-11-year-follow",
        "title": "Tiihonen et al. 11 year follow up of mortality in patients with schizophrenia a population base",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Tiihonen%20et%20al.%20-%2011-year%20follow-up%20of%20mortality%20in%20patients%20with%20schizophrenia%20a%20population-base.pdf",
        "filename": "Tiihonen et al. - 11-year follow-up of mortality in patients with schizophrenia a population-base.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-tiihonen-et-al-association-of",
        "title": "Tiihonen et al. Association of Antipsychotic Polypharmacy vs Monotherapy Wit",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Tiihonen%20et%20al.%20-%20Association%20of%20Antipsychotic%20Polypharmacy%20vs%20Monotherapy%20Wit.pdf",
        "filename": "Tiihonen et al. - Association of Antipsychotic Polypharmacy vs Monotherapy Wit.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      },
      {
        "id": "landmark-articles-schizophrenia-spectrum-disorders-wunderink-et-al-recovery-in-r",
        "title": "Wunderink et al. Recovery in remitted first episode psychosis at 7 years of f",
        "href": "/content/uh-psych/landmark-articles/Schizophrenia%20Spectrum%20Disorders/Wunderink%20et%20al.%20-%20Recovery%20in%20remitted%20first-episode%20psychosis%20at%207%20years%20of%20f.pdf",
        "filename": "Wunderink et al. - Recovery in remitted first-episode psychosis at 7 years of f.pdf",
        "subcategory": "Schizophrenia Spectrum Disorders"
      }
    ]
  },
  {
    "id": "psychopharmacology",
    "title": "Psychopharmacology",
    "description": "Quick-reference charts and fact sheets for inpatient and outpatient prescribing.",
    "documents": [
      {
        "id": "psychopharmacology-acute-bipolar-depression-treatment-pdf",
        "title": "Acute Bipolar Depression Treatment",
        "href": "/content/uh-psych/psychopharmacology/Acute%20Bipolar%20Depression%20Treatment.pdf",
        "filename": "Acute Bipolar Depression Treatment.pdf"
      },
      {
        "id": "psychopharmacology-acute-bipolar-mania-treatment-pdf",
        "title": "Acute Bipolar Mania Treatment",
        "href": "/content/uh-psych/psychopharmacology/Acute%20Bipolar%20Mania%20Treatment.pdf",
        "filename": "Acute Bipolar Mania Treatment.pdf"
      },
      {
        "id": "psychopharmacology-antipsychotics-chart-pdf",
        "title": "Antipsychotics Chart",
        "href": "/content/uh-psych/psychopharmacology/Antipsychotics%20-%20Chart.pdf",
        "filename": "Antipsychotics - Chart.pdf"
      },
      {
        "id": "psychopharmacology-antipsychotics-lecture-pptx",
        "title": "Antipsychotics Lecture",
        "href": "/content/uh-psych/psychopharmacology/Antipsychotics%20Lecture.pptx",
        "filename": "Antipsychotics Lecture.pptx"
      },
      {
        "id": "psychopharmacology-benzodiazepine-equivalence-table-pdf",
        "title": "Benzodiazepine Equivalence Table",
        "href": "/content/uh-psych/psychopharmacology/Benzodiazepine%20Equivalence%20Table.pdf",
        "filename": "Benzodiazepine Equivalence Table.pdf"
      },
      {
        "id": "psychopharmacology-bipolar-maintenance-treatment-pdf",
        "title": "Bipolar Maintenance Treatment",
        "href": "/content/uh-psych/psychopharmacology/Bipolar%20Maintenance%20Treatment.pdf",
        "filename": "Bipolar Maintenance Treatment.pdf"
      },
      {
        "id": "psychopharmacology-clozapine-and-the-risk-of-neutropenia-pdf",
        "title": "Clozapine and the Risk of Neutropenia",
        "href": "/content/uh-psych/psychopharmacology/Clozapine%20and%20the%20Risk%20of%20Neutropenia.pdf",
        "filename": "Clozapine and the Risk of Neutropenia.pdf"
      },
      {
        "id": "psychopharmacology-clozapine-fact-sheet-pdf",
        "title": "Clozapine Fact Sheet",
        "href": "/content/uh-psych/psychopharmacology/Clozapine%20Fact%20Sheet.pdf",
        "filename": "Clozapine Fact Sheet.pdf"
      },
      {
        "id": "psychopharmacology-clozapine-rems-fact-sheet-pdf",
        "title": "Clozapine REMS Fact Sheet",
        "href": "/content/uh-psych/psychopharmacology/Clozapine%20REMS%20Fact%20Sheet.pdf",
        "filename": "Clozapine REMS Fact Sheet.pdf"
      },
      {
        "id": "psychopharmacology-comparative-efficacy-and-tolerability-of-32-oral-antipsychoti",
        "title": "Comparative efficacy and tolerability of 32 oral antipsychotics",
        "href": "/content/uh-psych/psychopharmacology/Comparative%20efficacy%20and%20tolerability%20of%2032%20oral%20antipsychotics.pdf",
        "filename": "Comparative efficacy and tolerability of 32 oral antipsychotics.pdf"
      },
      {
        "id": "psychopharmacology-constipation-prns-pdf",
        "title": "Constipation PRNs",
        "href": "/content/uh-psych/psychopharmacology/Constipation%20PRNs.pdf",
        "filename": "Constipation PRNs.pdf"
      },
      {
        "id": "psychopharmacology-lab-monitoring-for-psychiatric-medications-pdf",
        "title": "Lab Monitoring for Psychiatric Medications",
        "href": "/content/uh-psych/psychopharmacology/Lab%20Monitoring%20for%20Psychiatric%20Medications.pdf",
        "filename": "Lab Monitoring for Psychiatric Medications.pdf"
      },
      {
        "id": "psychopharmacology-lai-chart-1-doc",
        "title": "LAI Chart 1",
        "href": "/content/uh-psych/psychopharmacology/LAI%20Chart%201.doc",
        "filename": "LAI Chart 1.doc"
      },
      {
        "id": "psychopharmacology-lai-chart-2-pdf",
        "title": "LAI Chart 2",
        "href": "/content/uh-psych/psychopharmacology/LAI%20Chart%202.pdf",
        "filename": "LAI Chart 2.pdf"
      },
      {
        "id": "psychopharmacology-lai-chart-3-pdf",
        "title": "LAI Chart 3",
        "href": "/content/uh-psych/psychopharmacology/LAI%20Chart%203.pdf",
        "filename": "LAI Chart 3.pdf"
      },
      {
        "id": "psychopharmacology-lai-practical-guide-pdf",
        "title": "LAI Practical Guide",
        "href": "/content/uh-psych/psychopharmacology/LAI%20Practical%20Guide.pdf",
        "filename": "LAI Practical Guide.pdf"
      },
      {
        "id": "psychopharmacology-medications-bipolar-depression-pdf",
        "title": "Medications Bipolar Depression",
        "href": "/content/uh-psych/psychopharmacology/Medications%20-%20Bipolar%20Depression.pdf",
        "filename": "Medications - Bipolar Depression.pdf"
      },
      {
        "id": "psychopharmacology-methadone-vs-buprenorphine-pdf",
        "title": "Methadone vs Buprenorphine",
        "href": "/content/uh-psych/psychopharmacology/Methadone%20vs%20Buprenorphine.pdf",
        "filename": "Methadone vs Buprenorphine.pdf"
      },
      {
        "id": "psychopharmacology-miscellaneous-psychopharm-notes-pdf",
        "title": "Miscellaneous Psychopharm Notes",
        "href": "/content/uh-psych/psychopharmacology/Miscellaneous%20Psychopharm%20Notes.pdf",
        "filename": "Miscellaneous Psychopharm Notes.pdf"
      },
      {
        "id": "psychopharmacology-prn-medications-agitation-and-psychosis-pdf",
        "title": "PRN Medications Agitation and Psychosis",
        "href": "/content/uh-psych/psychopharmacology/PRN%20Medications%20-%20Agitation%20and%20Psychosis.pdf",
        "filename": "PRN Medications - Agitation and Psychosis.pdf"
      },
      {
        "id": "psychopharmacology-psych-checkpoints-antidepressants-pdf",
        "title": "Psych Checkpoints Antidepressants",
        "href": "/content/uh-psych/psychopharmacology/Psych%20Checkpoints%20-%20Antidepressants.pdf",
        "filename": "Psych Checkpoints - Antidepressants.pdf"
      },
      {
        "id": "psychopharmacology-psych-checkpoints-antipsychotics-and-mood-stabilizers-pdf",
        "title": "Psych Checkpoints Antipsychotics and Mood Stabilizers",
        "href": "/content/uh-psych/psychopharmacology/Psych%20Checkpoints%20-%20Antipsychotics%20and%20Mood%20Stabilizers.pdf",
        "filename": "Psych Checkpoints - Antipsychotics and Mood Stabilizers.pdf"
      },
      {
        "id": "psychopharmacology-psych-med-quick-reference-pdf",
        "title": "Psych Med Quick Reference",
        "href": "/content/uh-psych/psychopharmacology/Psych%20Med%20Quick%20Reference.pdf",
        "filename": "Psych Med Quick Reference.pdf"
      },
      {
        "id": "psychopharmacology-qtc-prolongation-chart-png",
        "title": "QTC Prolongation Chart",
        "href": "/content/uh-psych/psychopharmacology/QTC%20Prolongation%20Chart.png",
        "filename": "QTC Prolongation Chart.png"
      },
      {
        "id": "psychopharmacology-qtc-prolongation-pdf",
        "title": "QTc Prolongation",
        "href": "/content/uh-psych/psychopharmacology/QTc%20Prolongation.pdf",
        "filename": "QTc Prolongation.pdf"
      },
      {
        "id": "psychopharmacology-sga-side-effect-chart-png",
        "title": "SGA Side Effect Chart",
        "href": "/content/uh-psych/psychopharmacology/SGA%20Side%20Effect%20Chart.png",
        "filename": "SGA Side Effect Chart.png"
      },
      {
        "id": "psychopharmacology-standard-medication-administration-pdf",
        "title": "Standard Medication Administration",
        "href": "/content/uh-psych/psychopharmacology/Standard%20Medication%20Administration.pdf",
        "filename": "Standard Medication Administration.pdf"
      },
      {
        "id": "psychopharmacology-tbi-treatment-pdf",
        "title": "TBI Treatment",
        "href": "/content/uh-psych/psychopharmacology/TBI%20Treatment.pdf",
        "filename": "TBI Treatment.pdf"
      },
      {
        "id": "psychopharmacology-treatment-algorithms-pdf",
        "title": "Treatment Algorithms",
        "href": "/content/uh-psych/psychopharmacology/Treatment%20Algorithms.pdf",
        "filename": "Treatment Algorithms.pdf"
      },
      {
        "id": "psychopharmacology-valproic-acid-and-ae-pdf",
        "title": "Valproic Acid and AE",
        "href": "/content/uh-psych/psychopharmacology/Valproic%20Acid%20and%20AE.pdf",
        "filename": "Valproic Acid and AE.pdf"
      }
    ]
  },
  {
    "id": "patient-handouts",
    "title": "For patients",
    "description": "Handouts and community resources to share with patients and families.",
    "documents": [
      {
        "id": "patient-handouts-carelines-helplines-pdf",
        "title": "Carelines & Helplines",
        "href": "/content/uh-psych/patient-handouts/Carelines%20%26%20Helplines.pdf",
        "filename": "Carelines & Helplines.pdf"
      },
      {
        "id": "patient-handouts-condition-specific-resources-anxiety-management-strategies-pdf",
        "title": "Anxiety Management Strategies",
        "href": "/content/uh-psych/patient-handouts/Condition-Specific%20Resources/Anxiety%20Management%20Strategies.pdf",
        "filename": "Anxiety Management Strategies.pdf",
        "subcategory": "Condition-Specific Resources"
      },
      {
        "id": "patient-handouts-condition-specific-resources-dementia-dementia-communicating-ab",
        "title": "Dementia Communicating About What to Expect as Dementia Progresses",
        "href": "/content/uh-psych/patient-handouts/Condition-Specific%20Resources/Dementia/Dementia%20-%20Communicating%20About%20What%20to%20Expect%20as%20Dementia%20Progresses.pdf",
        "filename": "Dementia - Communicating About What to Expect as Dementia Progresses.pdf",
        "subcategory": "Condition-Specific Resources / Dementia"
      },
      {
        "id": "patient-handouts-condition-specific-resources-dementia-dementia-care-resources-f",
        "title": "Dementia Care Resources for Caregivers",
        "href": "/content/uh-psych/patient-handouts/Condition-Specific%20Resources/Dementia/Dementia%20Care%20Resources%20for%20Caregivers.pdf",
        "filename": "Dementia Care Resources for Caregivers.pdf",
        "subcategory": "Condition-Specific Resources / Dementia"
      },
      {
        "id": "patient-handouts-condition-specific-resources-dementia-dementia-directive-pdf",
        "title": "Dementia Directive",
        "href": "/content/uh-psych/patient-handouts/Condition-Specific%20Resources/Dementia/Dementia%20Directive.pdf",
        "filename": "Dementia Directive.pdf",
        "subcategory": "Condition-Specific Resources / Dementia"
      },
      {
        "id": "patient-handouts-condition-specific-resources-general-navigating-a-mental-health",
        "title": "General Navigating a Mental Health Crisis NAMI Resource",
        "href": "/content/uh-psych/patient-handouts/Condition-Specific%20Resources/General%20-%20Navigating%20a%20Mental%20Health%20Crisis%20-%20NAMI%20Resource.pdf",
        "filename": "General - Navigating a Mental Health Crisis - NAMI Resource.pdf",
        "subcategory": "Condition-Specific Resources"
      },
      {
        "id": "patient-handouts-condition-specific-resources-genesight-genesight-clinician-broc",
        "title": "GeneSight Clinician Brochure 2021",
        "href": "/content/uh-psych/patient-handouts/Condition-Specific%20Resources/GeneSight/GeneSight%20-%20Clinician%20Brochure%202021.pdf",
        "filename": "GeneSight - Clinician Brochure 2021.pdf",
        "subcategory": "Condition-Specific Resources / GeneSight"
      },
      {
        "id": "patient-handouts-condition-specific-resources-genesight-genesight-financial-info",
        "title": "GeneSight Financial Information for GeneSight 2021",
        "href": "/content/uh-psych/patient-handouts/Condition-Specific%20Resources/GeneSight/GeneSight%20-%20Financial%20Information%20for%20GeneSight%202021.pdf",
        "filename": "GeneSight - Financial Information for GeneSight 2021.pdf",
        "subcategory": "Condition-Specific Resources / GeneSight"
      },
      {
        "id": "patient-handouts-condition-specific-resources-genesight-genesight-patient-brochu",
        "title": "GeneSight Patient Brochure 2021",
        "href": "/content/uh-psych/patient-handouts/Condition-Specific%20Resources/GeneSight/GeneSight%20-%20Patient%20Brochure%20-%202021.pdf",
        "filename": "GeneSight - Patient Brochure - 2021.pdf",
        "subcategory": "Condition-Specific Resources / GeneSight"
      },
      {
        "id": "patient-handouts-condition-specific-resources-genesight-genesight-psychotropic-s",
        "title": "GeneSight Psychotropic Sample Report Different Gene Variations 2021",
        "href": "/content/uh-psych/patient-handouts/Condition-Specific%20Resources/GeneSight/GeneSight%20-%20Psychotropic%20Sample%20Report%20-%20Different%20Gene%20Variations%202021.pdf",
        "filename": "GeneSight - Psychotropic Sample Report - Different Gene Variations 2021.pdf",
        "subcategory": "Condition-Specific Resources / GeneSight"
      },
      {
        "id": "patient-handouts-condition-specific-resources-non-epileptic-seizures-patient-inf",
        "title": "Non Epileptic Seizures Patient Information",
        "href": "/content/uh-psych/patient-handouts/Condition-Specific%20Resources/Non-Epileptic%20Seizures%20-%20Patient%20Information.pdf",
        "filename": "Non-Epileptic Seizures - Patient Information.pdf",
        "subcategory": "Condition-Specific Resources"
      },
      {
        "id": "patient-handouts-condition-specific-resources-schizophrenia-guidance-for-patient",
        "title": "Schizophrenia Guidance for Patients, Families, and Friends",
        "href": "/content/uh-psych/patient-handouts/Condition-Specific%20Resources/Schizophrenia%20-%20Guidance%20for%20Patients%2C%20Families%2C%20and%20Friends.pdf",
        "filename": "Schizophrenia - Guidance for Patients, Families, and Friends.pdf",
        "subcategory": "Condition-Specific Resources"
      },
      {
        "id": "patient-handouts-condition-specific-resources-what-you-need-to-know-about-ocd-pd",
        "title": "What You Need to Know About OCD",
        "href": "/content/uh-psych/patient-handouts/Condition-Specific%20Resources/What%20You%20Need%20to%20Know%20About%20OCD.pdf",
        "filename": "What You Need to Know About OCD.pdf",
        "subcategory": "Condition-Specific Resources"
      },
      {
        "id": "patient-handouts-county-specific-mh-resources-2015-docx",
        "title": "County Specific MH Resources (2015)",
        "href": "/content/uh-psych/patient-handouts/County-Specific%20MH%20Resources%20(2015).docx",
        "filename": "County-Specific MH Resources (2015).docx"
      },
      {
        "id": "patient-handouts-cuyahoga-county-diversion-center-espanol-pdf",
        "title": "Cuyahoga County Diversion Center Espanol",
        "href": "/content/uh-psych/patient-handouts/Cuyahoga%20County%20Diversion%20Center%20Espanol.pdf",
        "filename": "Cuyahoga County Diversion Center Espanol.pdf"
      },
      {
        "id": "patient-handouts-cuyahoga-county-diversion-center-pdf",
        "title": "Cuyahoga County Diversion Center",
        "href": "/content/uh-psych/patient-handouts/Cuyahoga%20County%20Diversion%20Center.pdf",
        "filename": "Cuyahoga County Diversion Center.pdf"
      },
      {
        "id": "patient-handouts-frontline-services-mobile-crisis-team-brochure-2020-pdf",
        "title": "Frontline Services Mobile Crisis Team Brochure 2020",
        "href": "/content/uh-psych/patient-handouts/Frontline%20Services%20Mobile%20Crisis%20Team%20Brochure%202020.pdf",
        "filename": "Frontline Services Mobile Crisis Team Brochure 2020.pdf"
      },
      {
        "id": "patient-handouts-local-chemical-dependency-resources-9-2021-pdf",
        "title": "Local Chemical Dependency Resources 9.2021",
        "href": "/content/uh-psych/patient-handouts/Local%20Chemical%20Dependency%20Resources%20-%209.2021.pdf",
        "filename": "Local Chemical Dependency Resources - 9.2021.pdf"
      },
      {
        "id": "patient-handouts-local-mental-health-resources-concise-2024-pdf",
        "title": "Local Mental Health Resources Concise 2024",
        "href": "/content/uh-psych/patient-handouts/Local%20Mental%20Health%20Resources%20Concise%20-%202024.pdf",
        "filename": "Local Mental Health Resources Concise - 2024.pdf"
      },
      {
        "id": "patient-handouts-local-mental-health-resources-detailed-2020-pdf",
        "title": "Local Mental Health Resources Detailed 2020",
        "href": "/content/uh-psych/patient-handouts/Local%20Mental%20Health%20Resources%20Detailed%20-%202020.pdf",
        "filename": "Local Mental Health Resources Detailed - 2020.pdf"
      },
      {
        "id": "patient-handouts-mental-health-resources-older-versions-local-mental-health-reso",
        "title": "Local Mental Health Resources Concise 2022",
        "href": "/content/uh-psych/patient-handouts/Mental%20Health%20Resources%20-%20Older%20Versions/Local%20Mental%20Health%20Resources%20Concise%20-%202022.pdf",
        "filename": "Local Mental Health Resources Concise - 2022.pdf",
        "subcategory": "Mental Health Resources - Older Versions"
      },
      {
        "id": "patient-handouts-ohiomha-state-hospitals-2022-pdf",
        "title": "OhioMHA State Hospitals 2022",
        "href": "/content/uh-psych/patient-handouts/OhioMHA%20State%20Hospitals%202022.pdf",
        "filename": "OhioMHA State Hospitals 2022.pdf"
      },
      {
        "id": "patient-handouts-street-card-pdf",
        "title": "Street Card",
        "href": "/content/uh-psych/patient-handouts/Street%20Card.pdf",
        "filename": "Street Card.pdf"
      },
      {
        "id": "patient-handouts-the-centers-behavioral-health-urgent-care-2022-pdf",
        "title": "The Centers Behavioral Health Urgent Care 2022",
        "href": "/content/uh-psych/patient-handouts/The%20Centers%20Behavioral%20Health%20Urgent%20Care%202022.pdf",
        "filename": "The Centers Behavioral Health Urgent Care 2022.pdf"
      },
      {
        "id": "patient-handouts-uh-safety-plan-pdf",
        "title": "UH Safety Plan",
        "href": "/content/uh-psych/patient-handouts/UH%20Safety%20Plan.pdf",
        "filename": "UH Safety Plan.pdf"
      },
      {
        "id": "patient-handouts-worksheets-anxiety-challenging-anxious-thoughts-pdf",
        "title": "Anxiety Challenging Anxious Thoughts",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Anxiety%20-%20Challenging%20Anxious%20Thoughts.pdf",
        "filename": "Anxiety - Challenging Anxious Thoughts.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-anxiety-introduction-to-anxiety-pdf",
        "title": "Anxiety Introduction to Anxiety",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Anxiety%20-%20Introduction%20to%20Anxiety.pdf",
        "filename": "Anxiety - Introduction to Anxiety.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-depression-behavioral-activation-pdf",
        "title": "Depression Behavioral Activation",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Depression%20-%20Behavioral%20Activation.pdf",
        "filename": "Depression - Behavioral Activation.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-depression-managing-of-the-depression-pit-pdf",
        "title": "Depression Managing of the Depression Pit",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Depression%20-%20Managing%20of%20the%20Depression%20Pit.pdf",
        "filename": "Depression - Managing of the Depression Pit.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-depression-self-care-plan-pdf",
        "title": "Depression Self Care Plan",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Depression%20-%20Self-Care%20Plan.pdf",
        "filename": "Depression - Self-Care Plan.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-depression-what-is-depression-pdf",
        "title": "Depression What is Depression",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Depression%20-%20What%20is%20Depression_.pdf",
        "filename": "Depression - What is Depression_.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-depression-workbook-pdf",
        "title": "Depression Workbook",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Depression%20Workbook.pdf",
        "filename": "Depression Workbook.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-automatic-thoughts-pdf",
        "title": "General Automatic Thoughts",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Automatic%20Thoughts.pdf",
        "filename": "General - Automatic Thoughts.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-basic-emotion-assessment-pdf",
        "title": "General Basic Emotion Assessment",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Basic%20Emotion%20Assessment.pdf",
        "filename": "General - Basic Emotion Assessment.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-building-happiness-pdf",
        "title": "General Building Happiness",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Building%20Happiness.pdf",
        "filename": "General - Building Happiness.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-challenging-negative-thoughts-pdf",
        "title": "General Challenging Negative Thoughts",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Challenging%20Negative%20Thoughts.pdf",
        "filename": "General - Challenging Negative Thoughts.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-cognitive-distortions-pdf",
        "title": "General Cognitive Distortions",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Cognitive%20Distortions.pdf",
        "filename": "General - Cognitive Distortions.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-common-unhealthy-thought-patterns-pdf",
        "title": "General Common Unhealthy Thought Patterns",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Common%20Unhealthy%20Thought%20Patterns.pdf",
        "filename": "General - Common Unhealthy Thought Patterns.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-coping-and-distress-skills-pdf",
        "title": "General Coping and Distress Skills",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Coping%20and%20Distress%20Skills.pdf",
        "filename": "General - Coping and Distress Skills.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-distress-tolerance-module-pdf",
        "title": "General Distress Tolerance Module",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Distress%20Tolerance%20Module.pdf",
        "filename": "General - Distress Tolerance Module.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-distress-tolerance-skills-pdf",
        "title": "General Distress Tolerance Skills",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Distress%20Tolerance%20Skills.pdf",
        "filename": "General - Distress Tolerance Skills.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-emotion-regulation-skills-pdf",
        "title": "General Emotion Regulation Skills",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Emotion%20Regulation%20Skills.pdf",
        "filename": "General - Emotion Regulation Skills.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-exploring-values-pdf",
        "title": "General Exploring Values",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Exploring%20Values.pdf",
        "filename": "General - Exploring Values.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-goal-planning-pdf",
        "title": "General Goal Planning",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Goal%20Planning.pdf",
        "filename": "General - Goal Planning.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-interpersonal-effectiveness-skills-pdf",
        "title": "General Interpersonal Effectiveness Skills",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Interpersonal%20Effectiveness%20Skills.pdf",
        "filename": "General - Interpersonal Effectiveness Skills.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-list-of-emotions-pdf",
        "title": "General List of Emotions",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20List%20of%20Emotions.pdf",
        "filename": "General - List of Emotions.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-looking-back-pdf",
        "title": "General Looking Back",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Looking%20Back.pdf",
        "filename": "General - Looking Back.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-mindfulness-exercises-pdf",
        "title": "General Mindfulness Exercises",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Mindfulness%20Exercises.pdf",
        "filename": "General - Mindfulness Exercises.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-mindfulness-skills-pdf",
        "title": "General Mindfulness Skills",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Mindfulness%20Skills.pdf",
        "filename": "General - Mindfulness Skills.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-mindfulness-pdf",
        "title": "General Mindfulness",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Mindfulness.pdf",
        "filename": "General - Mindfulness.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-my-strengths-and-qualities-pdf",
        "title": "General My Strengths and Qualities",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20My%20Strengths%20and%20Qualities.pdf",
        "filename": "General - My Strengths and Qualities.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-negative-self-talk-pdf",
        "title": "General Negative Self Talk",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Negative%20Self-Talk.pdf",
        "filename": "General - Negative Self-Talk.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-negative-thought-stopping-worksheet-pdf",
        "title": "General Negative Thought Stopping Worksheet",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Negative%20Thought%20Stopping%20Worksheet.pdf",
        "filename": "General - Negative Thought Stopping Worksheet.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-positive-experiences-pdf",
        "title": "General Positive Experiences",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Positive%20Experiences.pdf",
        "filename": "General - Positive Experiences.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-positive-journal-pdf",
        "title": "General Positive Journal",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Positive%20Journal.pdf",
        "filename": "General - Positive Journal.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-positive-self-talk-pdf",
        "title": "General Positive Self Talk",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Positive%20Self-Talk.pdf",
        "filename": "General - Positive Self-Talk.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-positive-traits-pdf",
        "title": "General Positive Traits",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Positive%20Traits.pdf",
        "filename": "General - Positive Traits.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-protective-factors-pdf",
        "title": "General Protective Factors",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Protective%20Factors.pdf",
        "filename": "General - Protective Factors.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-relationship-conflict-resolution-pdf",
        "title": "General Relationship Conflict Resolution",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Relationship%20Conflict%20Resolution.pdf",
        "filename": "General - Relationship Conflict Resolution.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-self-talk-pdf",
        "title": "General Self Talk",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Self-Talk.pdf",
        "filename": "General - Self-Talk.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-sentence-completion-pdf",
        "title": "General Sentence Completion",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Sentence%20Completion.pdf",
        "filename": "General - Sentence Completion.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-setting-life-goals-pdf",
        "title": "General Setting Life Goals",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Setting%20Life%20Goals.pdf",
        "filename": "General - Setting Life Goals.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-stress-management-tips-pdf",
        "title": "General Stress Management Tips",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Stress%20Management%20Tips.pdf",
        "filename": "General - Stress Management Tips.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-stress-management-pdf",
        "title": "General Stress Management",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Stress%20Management.pdf",
        "filename": "General - Stress Management.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-the-cognitive-model-practice-exercises-pdf",
        "title": "General The Cognitive Model Practice Exercises",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20The%20Cognitive%20Model%20Practice%20Exercises.pdf",
        "filename": "General - The Cognitive Model Practice Exercises.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-triggers-pdf",
        "title": "General Triggers",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Triggers.pdf",
        "filename": "General - Triggers.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-values-self-exploration-pdf",
        "title": "General Values Self Exploration",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Values%20-%20Self-Exploration.pdf",
        "filename": "General - Values - Self-Exploration.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-values-clarification-pdf",
        "title": "General Values Clarification",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Values%20Clarification.pdf",
        "filename": "General - Values Clarification.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-ways-to-challenge-your-own-beliefs-pdf",
        "title": "General Ways to Challenge Your Own Beliefs",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Ways%20to%20Challenge%20Your%20Own%20Beliefs.pdf",
        "filename": "General - Ways to Challenge Your Own Beliefs.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-what-are-personal-boundaries-pdf",
        "title": "General What are Personal Boundaries",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20What%20are%20Personal%20Boundaries_.pdf",
        "filename": "General - What are Personal Boundaries_.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-general-why-i-m-grateful-pdf",
        "title": "General Why I m Grateful",
        "href": "/content/uh-psych/patient-handouts/Worksheets/General%20-%20Why%20I_m%20Grateful.pdf",
        "filename": "General - Why I_m Grateful.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-grief-my-stages-of-grief-pdf",
        "title": "Grief My Stages of Grief",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Grief%20-%20My%20Stages%20of%20Grief.pdf",
        "filename": "Grief - My Stages of Grief.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-grief-sentence-completion-pdf",
        "title": "Grief Sentence Completion",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Grief%20-%20Sentence%20Completion.pdf",
        "filename": "Grief - Sentence Completion.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-grief-the-grieving-process-pdf",
        "title": "Grief The Grieving Process",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Grief%20-%20The%20Grieving%20Process.pdf",
        "filename": "Grief - The Grieving Process.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-grief-the-stages-of-grief-pdf",
        "title": "Grief The Stages of Grief",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Grief%20-%20The%20Stages%20of%20Grief.pdf",
        "filename": "Grief - The Stages of Grief.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-sleep-hygiene-brief-pdf",
        "title": "Sleep Hygiene Brief",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Sleep%20Hygiene%20-%20Brief.pdf",
        "filename": "Sleep Hygiene - Brief.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-sleep-hygiene-pdf",
        "title": "Sleep Hygiene",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Sleep%20Hygiene.pdf",
        "filename": "Sleep Hygiene.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-substance-use-building-discrepancy-pdf",
        "title": "Substance Use Building Discrepancy",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Substance%20Use%20-%20Building%20Discrepancy.pdf",
        "filename": "Substance Use - Building Discrepancy.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-substance-use-coping-skills-pdf",
        "title": "Substance Use Coping Skills",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Substance%20Use%20-%20Coping%20Skills.pdf",
        "filename": "Substance Use - Coping Skills.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-substance-use-identifying-cravings-people-places-thi",
        "title": "Substance Use Identifying Cravings People Places Things",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Substance%20Use%20-%20Identifying%20Cravings%20-%20People%20Places%20Things.pdf",
        "filename": "Substance Use - Identifying Cravings - People Places Things.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-substance-use-identifying-when-tempted-to-use-pdf",
        "title": "Substance Use Identifying when Tempted to Use",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Substance%20Use%20-%20Identifying%20when%20Tempted%20to%20Use.pdf",
        "filename": "Substance Use - Identifying when Tempted to Use.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-substance-use-motivational-ruler-pdf",
        "title": "Substance Use Motivational Ruler",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Substance%20Use%20-%20Motivational%20Ruler.pdf",
        "filename": "Substance Use - Motivational Ruler.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-substance-use-relapse-prevention-plan-1-pdf",
        "title": "Substance Use Relapse Prevention Plan #1",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Substance%20Use%20-%20Relapse%20Prevention%20Plan%20%231.pdf",
        "filename": "Substance Use - Relapse Prevention Plan #1.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-substance-use-relapse-prevention-plan-2-pdf",
        "title": "Substance Use Relapse Prevention Plan #2",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Substance%20Use%20-%20Relapse%20Prevention%20Plan%20%232.pdf",
        "filename": "Substance Use - Relapse Prevention Plan #2.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-substance-use-stages-of-change-pdf",
        "title": "Substance Use Stages of Change",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Substance%20Use%20-%20Stages%20of%20Change.pdf",
        "filename": "Substance Use - Stages of Change.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-substance-use-tips-for-avoiding-relapse-pdf",
        "title": "Substance Use Tips for Avoiding Relapse",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Substance%20Use%20-%20Tips%20for%20Avoiding%20Relapse.pdf",
        "filename": "Substance Use - Tips for Avoiding Relapse.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-substance-use-workbook-adult-full-version-pdf",
        "title": "Substance Use Workbook Adult Full Version",
        "href": "/content/uh-psych/patient-handouts/Worksheets/Substance%20Use%20Workbook%20-%20Adult%20-%20Full%20Version.pdf",
        "filename": "Substance Use Workbook - Adult - Full Version.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-the-dialectical-behavior-therapy-skills-workbook-pdf",
        "title": "The Dialectical Behavior Therapy Skills Workbook",
        "href": "/content/uh-psych/patient-handouts/Worksheets/The%20Dialectical%20Behavior%20Therapy%20Skills%20Workbook.pdf",
        "filename": "The Dialectical Behavior Therapy Skills Workbook.pdf",
        "subcategory": "Worksheets"
      },
      {
        "id": "patient-handouts-worksheets-uh-mental-health-safety-plan-pdf",
        "title": "UH Mental Health Safety Plan",
        "href": "/content/uh-psych/patient-handouts/Worksheets/UH%20Mental%20Health%20Safety%20Plan.pdf",
        "filename": "UH Mental Health Safety Plan.pdf",
        "subcategory": "Worksheets"
      }
    ]
  },
  {
    "id": "core-readings",
    "title": "Core readings",
    "description": "Foundational texts for capacity, ethics, and clinical reasoning.",
    "documents": [
      {
        "id": "core-readings-appelbaum-competence-to-consent-pdf",
        "title": "appelbaum competence to consent",
        "href": "/content/uh-psych/core-readings/appelbaum-competence-to-consent.pdf",
        "filename": "appelbaum-competence-to-consent.pdf"
      }
    ]
  },
  {
    "id": "electives",
    "title": "Electives",
    "description": "Master elective catalog spreadsheet — locations, faculty, and requirements.",
    "documents": [
      {
        "id": "electives-master-elective-spreadsheet-xlsx",
        "title": "master elective spreadsheet",
        "href": "/content/uh-psych/electives/master-elective-spreadsheet.xlsx",
        "filename": "master-elective-spreadsheet.xlsx"
      }
    ]
  }
];
