// AUTO-GENERATED by docs/seeds/onet/build-onet-seed.mjs — do not edit manually.
// Source: O*NET 30.3 Database, U.S. DOL/ETA, May 2026. CC-BY 4.0.
// Normalization: dual-scale V=100×((Im-1)/4)×(Lv/7); single-scale V=((x-min)/(max-min))×100 (declared anchors)
// https://www.onetcenter.org/license_db.html

export type AdjacentOccupation = { soc: string; title: string; similarity: number };

/** Top-20 non-physician Job-Zone-≥3 adjacent occupations per physician SOC (cosine similarity on 244-dim vectors). */
export const ADJACENCY_BASKETS: Readonly<Record<string, readonly AdjacentOccupation[]>> = {
 "29-1211.00": [
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9595
  },
  {
   "soc": "29-9093.00",
   "title": "Surgical Assistants",
   "similarity": 0.9556
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9522
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9483
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9456
  },
  {
   "soc": "29-2056.00",
   "title": "Veterinary Technologists and Technicians",
   "similarity": 0.9432
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9412
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9404
  },
  {
   "soc": "29-2055.00",
   "title": "Surgical Technologists",
   "similarity": 0.94
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9373
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9367
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9355
  },
  {
   "soc": "29-2012.00",
   "title": "Medical and Clinical Laboratory Technicians",
   "similarity": 0.9331
  },
  {
   "soc": "29-2034.00",
   "title": "Radiologic Technologists and Technicians",
   "similarity": 0.9327
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9312
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.931
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.929
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9272
  },
  {
   "soc": "31-9097.00",
   "title": "Phlebotomists",
   "similarity": 0.9268
  },
  {
   "soc": "31-9091.00",
   "title": "Dental Assistants",
   "similarity": 0.9267
  }
 ],
 "29-1213.00": [
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.958
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9543
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9489
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9454
  },
  {
   "soc": "29-2057.00",
   "title": "Ophthalmic Medical Technicians",
   "similarity": 0.9415
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9398
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.939
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9376
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9367
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.932
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.931
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9301
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9297
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9291
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9286
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9285
  },
  {
   "soc": "31-9097.00",
   "title": "Phlebotomists",
   "similarity": 0.9284
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9264
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9254
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9224
  }
 ],
 "29-1214.00": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9542
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9525
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9516
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9469
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9347
  },
  {
   "soc": "29-9093.00",
   "title": "Surgical Assistants",
   "similarity": 0.932
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9319
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9306
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9305
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9299
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9298
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9298
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9283
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9276
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.927
  },
  {
   "soc": "31-9097.00",
   "title": "Phlebotomists",
   "similarity": 0.9268
  },
  {
   "soc": "31-2011.00",
   "title": "Occupational Therapy Assistants",
   "similarity": 0.9259
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9257
  },
  {
   "soc": "29-2056.00",
   "title": "Veterinary Technologists and Technicians",
   "similarity": 0.9244
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.924
  }
 ],
 "29-1215.00": [
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9426
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9375
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9373
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9337
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9313
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9309
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9308
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9248
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.923
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.921
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9199
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9191
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.918
  },
  {
   "soc": "29-2057.00",
   "title": "Ophthalmic Medical Technicians",
   "similarity": 0.9175
  },
  {
   "soc": "19-3033.00",
   "title": "Clinical and Counseling Psychologists",
   "similarity": 0.9163
  },
  {
   "soc": "29-2099.08",
   "title": "Patient Representatives",
   "similarity": 0.9133
  },
  {
   "soc": "31-9099.01",
   "title": "Speech-Language Pathology Assistants",
   "similarity": 0.9128
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.911
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9101
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9088
  }
 ],
 "29-1216.00": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9596
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9586
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.954
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9501
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.943
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9406
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9398
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9384
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9356
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9348
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9342
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9331
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9308
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9288
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9285
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9284
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9264
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9259
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9258
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9257
  }
 ],
 "29-1217.00": [
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9693
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9641
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9624
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9567
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.955
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9517
  },
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.9507
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9505
  },
  {
   "soc": "19-3033.00",
   "title": "Clinical and Counseling Psychologists",
   "similarity": 0.9411
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9408
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.939
  },
  {
   "soc": "25-1042.00",
   "title": "Biological Science Teachers, Postsecondary",
   "similarity": 0.9373
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.935
  },
  {
   "soc": "21-1023.00",
   "title": "Mental Health and Substance Abuse Social Workers",
   "similarity": 0.9308
  },
  {
   "soc": "11-9121.00",
   "title": "Natural Sciences Managers",
   "similarity": 0.929
  },
  {
   "soc": "25-1066.00",
   "title": "Psychology Teachers, Postsecondary",
   "similarity": 0.929
  },
  {
   "soc": "21-1012.00",
   "title": "Educational, Guidance, and Career Counselors and Advisors",
   "similarity": 0.9287
  },
  {
   "soc": "21-1011.00",
   "title": "Substance Abuse and Behavioral Disorder Counselors",
   "similarity": 0.9283
  },
  {
   "soc": "11-9111.00",
   "title": "Medical and Health Services Managers",
   "similarity": 0.9282
  },
  {
   "soc": "19-1029.03",
   "title": "Geneticists",
   "similarity": 0.9275
  }
 ],
 "29-1218.00": [
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9692
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9637
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9509
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9435
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9429
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9414
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.941
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9392
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9371
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9369
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9365
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9347
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9315
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9295
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9292
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9289
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9288
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9279
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9267
  },
  {
   "soc": "25-2023.00",
   "title": "Career/Technical Education Teachers, Middle School",
   "similarity": 0.9261
  }
 ],
 "29-1221.00": [
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9575
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9523
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9462
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.939
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9372
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.9366
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9355
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9349
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9346
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9301
  },
  {
   "soc": "29-2099.08",
   "title": "Patient Representatives",
   "similarity": 0.9297
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9295
  },
  {
   "soc": "31-2011.00",
   "title": "Occupational Therapy Assistants",
   "similarity": 0.9288
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9287
  },
  {
   "soc": "29-2053.00",
   "title": "Psychiatric Technicians",
   "similarity": 0.9277
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9268
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9265
  },
  {
   "soc": "25-2051.00",
   "title": "Special Education Teachers, Preschool",
   "similarity": 0.9249
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9235
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9232
  }
 ],
 "29-1222.00": [
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9653
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9621
  },
  {
   "soc": "29-2011.01",
   "title": "Cytogenetic Technologists",
   "similarity": 0.9585
  },
  {
   "soc": "29-2036.00",
   "title": "Medical Dosimetrists",
   "similarity": 0.9567
  },
  {
   "soc": "19-1029.02",
   "title": "Molecular and Cellular Biologists",
   "similarity": 0.9517
  },
  {
   "soc": "29-2011.02",
   "title": "Cytotechnologists",
   "similarity": 0.9477
  },
  {
   "soc": "19-1029.03",
   "title": "Geneticists",
   "similarity": 0.9472
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9437
  },
  {
   "soc": "19-1021.00",
   "title": "Biochemists and Biophysicists",
   "similarity": 0.9375
  },
  {
   "soc": "19-4021.00",
   "title": "Biological Technicians",
   "similarity": 0.9372
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9343
  },
  {
   "soc": "19-2041.00",
   "title": "Environmental Scientists and Specialists, Including Health",
   "similarity": 0.9343
  },
  {
   "soc": "19-2031.00",
   "title": "Chemists",
   "similarity": 0.9341
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9335
  },
  {
   "soc": "29-2012.00",
   "title": "Medical and Clinical Laboratory Technicians",
   "similarity": 0.9315
  },
  {
   "soc": "11-9121.00",
   "title": "Natural Sciences Managers",
   "similarity": 0.931
  },
  {
   "soc": "19-1012.00",
   "title": "Food Scientists and Technologists",
   "similarity": 0.9298
  },
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.9294
  },
  {
   "soc": "17-2112.02",
   "title": "Validation Engineers",
   "similarity": 0.9289
  },
  {
   "soc": "17-2031.00",
   "title": "Bioengineers and Biomedical Engineers",
   "similarity": 0.9284
  }
 ],
 "29-1223.00": [
  {
   "soc": "19-3033.00",
   "title": "Clinical and Counseling Psychologists",
   "similarity": 0.9717
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9646
  },
  {
   "soc": "21-1023.00",
   "title": "Mental Health and Substance Abuse Social Workers",
   "similarity": 0.9631
  },
  {
   "soc": "21-1014.00",
   "title": "Mental Health Counselors",
   "similarity": 0.9621
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9617
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9613
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.9585
  },
  {
   "soc": "21-1013.00",
   "title": "Marriage and Family Therapists",
   "similarity": 0.9582
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9517
  },
  {
   "soc": "21-1011.00",
   "title": "Substance Abuse and Behavioral Disorder Counselors",
   "similarity": 0.9511
  },
  {
   "soc": "19-3034.00",
   "title": "School Psychologists",
   "similarity": 0.9458
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9448
  },
  {
   "soc": "21-1012.00",
   "title": "Educational, Guidance, and Career Counselors and Advisors",
   "similarity": 0.9435
  },
  {
   "soc": "21-1021.00",
   "title": "Child, Family, and School Social Workers",
   "similarity": 0.943
  },
  {
   "soc": "25-2058.00",
   "title": "Special Education Teachers, Secondary School",
   "similarity": 0.9409
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9408
  },
  {
   "soc": "21-1015.00",
   "title": "Rehabilitation Counselors",
   "similarity": 0.9348
  },
  {
   "soc": "25-1066.00",
   "title": "Psychology Teachers, Postsecondary",
   "similarity": 0.9296
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9292
  },
  {
   "soc": "25-2056.00",
   "title": "Special Education Teachers, Elementary School",
   "similarity": 0.928
  }
 ],
 "29-1224.00": [
  {
   "soc": "29-2036.00",
   "title": "Medical Dosimetrists",
   "similarity": 0.9498
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9454
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9452
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9403
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9376
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9324
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9323
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9321
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9308
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9304
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9304
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9295
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9278
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9252
  },
  {
   "soc": "19-1029.02",
   "title": "Molecular and Cellular Biologists",
   "similarity": 0.9251
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9246
  },
  {
   "soc": "29-2034.00",
   "title": "Radiologic Technologists and Technicians",
   "similarity": 0.9232
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9228
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9226
  },
  {
   "soc": "29-2011.02",
   "title": "Cytotechnologists",
   "similarity": 0.9207
  }
 ],
 "29-1229.00": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9747
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9648
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9618
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9612
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9581
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9548
  },
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.9495
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9492
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9482
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9473
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9448
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9432
  },
  {
   "soc": "25-1042.00",
   "title": "Biological Science Teachers, Postsecondary",
   "similarity": 0.9428
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.942
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9417
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9399
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9396
  },
  {
   "soc": "19-5011.00",
   "title": "Occupational Health and Safety Specialists",
   "similarity": 0.9391
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9389
  },
  {
   "soc": "25-1053.00",
   "title": "Environmental Science Teachers, Postsecondary",
   "similarity": 0.9389
  }
 ],
 "29-1229.01": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9584
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9579
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9573
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9546
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.953
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9524
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9513
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9505
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9466
  },
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.9428
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9392
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9386
  },
  {
   "soc": "29-2099.08",
   "title": "Patient Representatives",
   "similarity": 0.9379
  },
  {
   "soc": "21-1012.00",
   "title": "Educational, Guidance, and Career Counselors and Advisors",
   "similarity": 0.9371
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9364
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9359
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9354
  },
  {
   "soc": "29-2036.00",
   "title": "Medical Dosimetrists",
   "similarity": 0.9347
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9347
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9335
  }
 ],
 "29-1229.03": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9495
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9429
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9426
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9409
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9384
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9333
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9322
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9322
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9315
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9254
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9245
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9239
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9231
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.923
  },
  {
   "soc": "19-5011.00",
   "title": "Occupational Health and Safety Specialists",
   "similarity": 0.9225
  },
  {
   "soc": "29-9093.00",
   "title": "Surgical Assistants",
   "similarity": 0.9224
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9223
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9215
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9206
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9201
  }
 ],
 "29-1229.04": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9737
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9698
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9584
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9533
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9519
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9429
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9405
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9385
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9384
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9373
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9369
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9368
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9367
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9359
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.9349
  },
  {
   "soc": "25-2023.00",
   "title": "Career/Technical Education Teachers, Middle School",
   "similarity": 0.9348
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9348
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9344
  },
  {
   "soc": "25-2058.00",
   "title": "Special Education Teachers, Secondary School",
   "similarity": 0.9336
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9332
  }
 ],
 "29-1229.05": [
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.9712
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9638
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9629
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9609
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9551
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9543
  },
  {
   "soc": "25-1041.00",
   "title": "Agricultural Sciences Teachers, Postsecondary",
   "similarity": 0.9515
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9513
  },
  {
   "soc": "11-9161.00",
   "title": "Emergency Management Directors",
   "similarity": 0.9509
  },
  {
   "soc": "25-1053.00",
   "title": "Environmental Science Teachers, Postsecondary",
   "similarity": 0.9509
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9501
  },
  {
   "soc": "25-1042.00",
   "title": "Biological Science Teachers, Postsecondary",
   "similarity": 0.9501
  },
  {
   "soc": "11-9121.00",
   "title": "Natural Sciences Managers",
   "similarity": 0.9488
  },
  {
   "soc": "11-9033.00",
   "title": "Education Administrators, Postsecondary",
   "similarity": 0.9481
  },
  {
   "soc": "17-2112.01",
   "title": "Human Factors Engineers and Ergonomists",
   "similarity": 0.9477
  },
  {
   "soc": "19-2041.00",
   "title": "Environmental Scientists and Specialists, Including Health",
   "similarity": 0.9475
  },
  {
   "soc": "11-9111.00",
   "title": "Medical and Health Services Managers",
   "similarity": 0.9465
  },
  {
   "soc": "13-1111.00",
   "title": "Management Analysts",
   "similarity": 0.9461
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9444
  },
  {
   "soc": "19-3032.00",
   "title": "Industrial-Organizational Psychologists",
   "similarity": 0.943
  }
 ],
 "29-1241.00": [
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9538
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.946
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9458
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9449
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9429
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9427
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9414
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9373
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9367
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9364
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9349
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9319
  },
  {
   "soc": "29-2057.00",
   "title": "Ophthalmic Medical Technicians",
   "similarity": 0.9299
  },
  {
   "soc": "29-2036.00",
   "title": "Medical Dosimetrists",
   "similarity": 0.9293
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9292
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9286
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9271
  },
  {
   "soc": "29-2081.00",
   "title": "Opticians, Dispensing",
   "similarity": 0.9265
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9264
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9258
  }
 ],
 "29-1242.00": [
  {
   "soc": "29-2043.00",
   "title": "Paramedics",
   "similarity": 0.8982
  },
  {
   "soc": "15-1299.06",
   "title": "Digital Forensics Analysts",
   "similarity": 0.8944
  },
  {
   "soc": "29-2042.00",
   "title": "Emergency Medical Technicians",
   "similarity": 0.8911
  },
  {
   "soc": "29-9021.00",
   "title": "Health Information Technologists and Medical Registrars",
   "similarity": 0.8839
  },
  {
   "soc": "15-1299.04",
   "title": "Penetration Testers",
   "similarity": 0.8801
  },
  {
   "soc": "15-1299.07",
   "title": "Blockchain Engineers",
   "similarity": 0.854
  },
  {
   "soc": "13-2054.00",
   "title": "Financial Risk Specialists",
   "similarity": 0.8534
  },
  {
   "soc": "19-4044.00",
   "title": "Hydrologic Technicians",
   "similarity": 0.8527
  },
  {
   "soc": "13-2051.00",
   "title": "Financial and Investment Analysts",
   "similarity": 0.8357
  },
  {
   "soc": "15-2051.00",
   "title": "Data Scientists",
   "similarity": 0.8356
  },
  {
   "soc": "25-2055.00",
   "title": "Special Education Teachers, Kindergarten",
   "similarity": 0.8218
  },
  {
   "soc": "17-3028.00",
   "title": "Calibration Technologists and Technicians",
   "similarity": 0.8161
  },
  {
   "soc": "13-1082.00",
   "title": "Project Management Specialists",
   "similarity": 0.8121
  },
  {
   "soc": "11-1031.00",
   "title": "Legislators",
   "similarity": 0.8106
  },
  {
   "soc": "15-1255.00",
   "title": "Web and Digital Interface Designers",
   "similarity": 0.8005
  },
  {
   "soc": "29-2072.00",
   "title": "Medical Records Specialists",
   "similarity": 0.7926
  },
  {
   "soc": "27-4015.00",
   "title": "Lighting Technicians",
   "similarity": 0.7366
  },
  {
   "soc": "11-2032.00",
   "title": "Public Relations Managers",
   "similarity": 0.7305
  },
  {
   "soc": "53-1044.00",
   "title": "First-Line Supervisors of Passenger Attendants",
   "similarity": 0.7207
  },
  {
   "soc": "29-2011.02",
   "title": "Cytotechnologists",
   "similarity": 0.3488
  }
 ],
 "29-1249.00": [
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.8697
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.8583
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.8576
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.853
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.8523
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.8522
  },
  {
   "soc": "29-2011.02",
   "title": "Cytotechnologists",
   "similarity": 0.8493
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.8479
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.8477
  },
  {
   "soc": "29-2036.00",
   "title": "Medical Dosimetrists",
   "similarity": 0.8473
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.845
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.8437
  },
  {
   "soc": "19-1029.03",
   "title": "Geneticists",
   "similarity": 0.84
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.8398
  },
  {
   "soc": "11-9121.00",
   "title": "Natural Sciences Managers",
   "similarity": 0.8392
  },
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.8385
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.838
  },
  {
   "soc": "19-1029.02",
   "title": "Molecular and Cellular Biologists",
   "similarity": 0.8365
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.8364
  },
  {
   "soc": "19-2041.00",
   "title": "Environmental Scientists and Specialists, Including Health",
   "similarity": 0.8358
  }
 ]
};

export const SOC_TITLES: Readonly<Record<string, string>> = {
  "29-1211.00": "Anesthesiologists",
  "29-1213.00": "Dermatologists",
  "29-1214.00": "Emergency Medicine Physicians",
  "29-1215.00": "Family Medicine Physicians",
  "29-1216.00": "General Internal Medicine Physicians",
  "29-1217.00": "Neurologists",
  "29-1218.00": "Obstetricians and Gynecologists",
  "29-1221.00": "Pediatricians, General",
  "29-1222.00": "Physicians, Pathologists",
  "29-1223.00": "Psychiatrists",
  "29-1224.00": "Radiologists",
  "29-1229.00": "Physicians, All Other",
  "29-1229.01": "Allergists and Immunologists",
  "29-1229.03": "Urologists",
  "29-1229.04": "Physical Medicine and Rehabilitation Physicians",
  "29-1229.05": "Preventive Medicine Physicians",
  "29-1241.00": "Ophthalmologists, Except Pediatric",
  "29-1242.00": "Orthopedic Surgeons, Except Pediatric",
  "29-1249.00": "Surgeons, All Other",
  "25-1071.00": "Health Specialties Teachers, Postsecondary",
  "19-1042.00": "Medical Scientists, Except Epidemiologists",
  "11-9111.00": "Medical and Health Services Managers",
  "21-1094.00": "Community Health Workers",
  "15-2051.00": "Data Scientists",
  "29-9021.00": "Health Information Technologists and Medical Registrars",
  "21-1014.00": "Mental Health Counselors",
  "13-1082.00": "Project Management Specialists",
  "13-1111.00": "Management Analysts",
  "15-1211.00": "Computer Systems Analysts",
  "15-1252.00": "Software Developers",
  "15-1255.00": "Web and Digital Interface Designers",
  "17-2031.00": "Bioengineers and Biomedical Engineers",
  "17-2112.00": "Industrial Engineers",
  "19-1041.00": "Epidemiologists",
  "19-3032.00": "Industrial-Organizational Psychologists",
  "21-1022.00": "Healthcare Social Workers",
  "23-1022.00": "Arbitrators, Mediators, and Conciliators",
  "25-9031.00": "Instructional Coordinators",
  "27-3042.00": "Technical Writers",
  "29-2034.00": "Radiologic Technologists and Technicians",
  "29-9092.00": "Genetic Counselors",
  "27-4021.00": "Photographers",
  "27-2042.00": "Musicians and Singers",
  "27-3043.00": "Writers and Authors",
  "27-1013.00": "Fine Artists, Including Painters, Sculptors, and Illustrators",
  "29-9091.00": "Athletic Trainers",
  "35-1011.00": "Chefs and Head Cooks",
  "29-1212.00": "Cardiologists",
  "17-2072.00": "Electronics Engineers, Except Computer",
  "29-2031.00": "Cardiovascular Technologists and Technicians",
  "29-1126.00": "Respiratory Therapists",
  "25-1042.00": "Biological Science Teachers, Postsecondary",
  "21-1015.00": "Rehabilitation Counselors",
  "21-1011.00": "Substance Abuse and Behavioral Disorder Counselors",
  "21-1012.00": "Educational, Guidance, and Career Counselors and Advisors",
  "29-2099.00": "Health Technologists and Technicians, All Other",
  "19-4092.00": "Forensic Science Technicians",
  "29-1123.00": "Physical Therapists",
  "29-1029.00": "Dentists, All Other Specialists",
  "51-9071.00": "Jewelers and Precious Stone and Metal Workers",
  "29-1127.00": "Speech-Language Pathologists",
  "29-2033.00": "Nuclear Medicine Technologists",
  "17-2199.00": "Engineers, All Other",
  "11-9121.00": "Natural Sciences Managers",
  "19-2031.00": "Chemists",
  "19-1022.00": "Microbiologists",
  "29-2032.00": "Diagnostic Medical Sonographers",
  "29-1161.00": "Nurse Midwives",
  "29-1041.00": "Optometrists",
  "17-2011.00": "Aerospace Engineers",
  "19-3033.00": "Clinical and Counseling Psychologists",
  "11-9161.00": "Emergency Management Directors",
  "29-2042.00": "Emergency Medical Technicians",
  "29-2043.00": "Paramedics",
  "25-2059.00": "Special Education Teachers, All Other",
  "29-2011.00": "Medical and Clinical Laboratory Technologists",
  "13-1041.00": "Compliance Officers"
};
