// AUTO-GENERATED by docs/seeds/onet/build-onet-seed.mjs — do not edit manually.
// Source: O*NET 30.3 Database, U.S. DOL/ETA, May 2026. CC-BY 4.0.
// https://www.onetcenter.org/license_db.html

export type AdjacentOccupation = { soc: string; title: string; similarity: number };

/** Top-20 non-physician Job-Zone-≥3 adjacent occupations per physician SOC (cosine similarity). */
export const ADJACENCY_BASKETS: Readonly<Record<string, readonly AdjacentOccupation[]>> = {
 "29-1211.00": [
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9752
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9751
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.973
  },
  {
   "soc": "29-9093.00",
   "title": "Surgical Assistants",
   "similarity": 0.9721
  },
  {
   "soc": "29-2056.00",
   "title": "Veterinary Technologists and Technicians",
   "similarity": 0.97
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9679
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9674
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9649
  },
  {
   "soc": "29-2055.00",
   "title": "Surgical Technologists",
   "similarity": 0.9649
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9647
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9647
  },
  {
   "soc": "29-2034.00",
   "title": "Radiologic Technologists and Technicians",
   "similarity": 0.9642
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9632
  },
  {
   "soc": "29-2012.00",
   "title": "Medical and Clinical Laboratory Technicians",
   "similarity": 0.9628
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9626
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9608
  },
  {
   "soc": "19-1029.02",
   "title": "Molecular and Cellular Biologists",
   "similarity": 0.9576
  },
  {
   "soc": "29-2011.01",
   "title": "Cytogenetic Technologists",
   "similarity": 0.9576
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9574
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9569
  }
 ],
 "29-1213.00": [
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9735
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9734
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9729
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9692
  },
  {
   "soc": "29-2057.00",
   "title": "Ophthalmic Medical Technicians",
   "similarity": 0.964
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9625
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9618
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9617
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9601
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9599
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.959
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9588
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.958
  },
  {
   "soc": "31-2011.00",
   "title": "Occupational Therapy Assistants",
   "similarity": 0.9568
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9566
  },
  {
   "soc": "29-2099.08",
   "title": "Patient Representatives",
   "similarity": 0.9561
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9554
  },
  {
   "soc": "31-9097.00",
   "title": "Phlebotomists",
   "similarity": 0.9553
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9552
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9545
  }
 ],
 "29-1214.00": [
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9751
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9697
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9684
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9679
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9675
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9629
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.962
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.962
  },
  {
   "soc": "31-2011.00",
   "title": "Occupational Therapy Assistants",
   "similarity": 0.9618
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9613
  },
  {
   "soc": "29-9093.00",
   "title": "Surgical Assistants",
   "similarity": 0.961
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9603
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9601
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9598
  },
  {
   "soc": "29-2034.00",
   "title": "Radiologic Technologists and Technicians",
   "similarity": 0.9594
  },
  {
   "soc": "29-2056.00",
   "title": "Veterinary Technologists and Technicians",
   "similarity": 0.9592
  },
  {
   "soc": "31-9097.00",
   "title": "Phlebotomists",
   "similarity": 0.958
  },
  {
   "soc": "29-2053.00",
   "title": "Psychiatric Technicians",
   "similarity": 0.9571
  },
  {
   "soc": "33-3021.00",
   "title": "Detectives and Criminal Investigators",
   "similarity": 0.9541
  },
  {
   "soc": "13-1041.06",
   "title": "Coroners",
   "similarity": 0.9536
  }
 ],
 "29-1215.00": [
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9669
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9638
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9632
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9614
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9598
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9558
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9542
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9528
  },
  {
   "soc": "19-3033.00",
   "title": "Clinical and Counseling Psychologists",
   "similarity": 0.9518
  },
  {
   "soc": "29-2099.08",
   "title": "Patient Representatives",
   "similarity": 0.9509
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.9508
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9497
  },
  {
   "soc": "31-9099.01",
   "title": "Speech-Language Pathology Assistants",
   "similarity": 0.949
  },
  {
   "soc": "29-2057.00",
   "title": "Ophthalmic Medical Technicians",
   "similarity": 0.9481
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9473
  },
  {
   "soc": "21-1014.00",
   "title": "Mental Health Counselors",
   "similarity": 0.9464
  },
  {
   "soc": "21-1021.00",
   "title": "Child, Family, and School Social Workers",
   "similarity": 0.9453
  },
  {
   "soc": "25-2058.00",
   "title": "Special Education Teachers, Secondary School",
   "similarity": 0.9453
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9451
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.945
  }
 ],
 "29-1216.00": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9787
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9743
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9716
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9704
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9696
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9679
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9669
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9666
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9647
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9631
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9629
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9614
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.961
  },
  {
   "soc": "29-2099.08",
   "title": "Patient Representatives",
   "similarity": 0.9607
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9601
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9592
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9591
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9591
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9586
  },
  {
   "soc": "25-2058.00",
   "title": "Special Education Teachers, Secondary School",
   "similarity": 0.9585
  }
 ],
 "29-1217.00": [
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.981
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9797
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9779
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.973
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9721
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9719
  },
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.9718
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9705
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9696
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9678
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9673
  },
  {
   "soc": "25-1042.00",
   "title": "Biological Science Teachers, Postsecondary",
   "similarity": 0.9664
  },
  {
   "soc": "19-3033.00",
   "title": "Clinical and Counseling Psychologists",
   "similarity": 0.9634
  },
  {
   "soc": "25-1192.00",
   "title": "Family and Consumer Sciences Teachers, Postsecondary",
   "similarity": 0.9631
  },
  {
   "soc": "11-9111.00",
   "title": "Medical and Health Services Managers",
   "similarity": 0.9628
  },
  {
   "soc": "25-1066.00",
   "title": "Psychology Teachers, Postsecondary",
   "similarity": 0.9617
  },
  {
   "soc": "25-2058.00",
   "title": "Special Education Teachers, Secondary School",
   "similarity": 0.9616
  },
  {
   "soc": "25-1051.00",
   "title": "Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary",
   "similarity": 0.9611
  },
  {
   "soc": "21-1023.00",
   "title": "Mental Health and Substance Abuse Social Workers",
   "similarity": 0.9598
  },
  {
   "soc": "25-1053.00",
   "title": "Environmental Science Teachers, Postsecondary",
   "similarity": 0.9598
  }
 ],
 "29-1218.00": [
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9824
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.981
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9783
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9739
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9713
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9687
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9684
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9678
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9663
  },
  {
   "soc": "31-2011.00",
   "title": "Occupational Therapy Assistants",
   "similarity": 0.9651
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9647
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9647
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9646
  },
  {
   "soc": "29-2057.00",
   "title": "Ophthalmic Medical Technicians",
   "similarity": 0.9644
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9638
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9636
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9634
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9624
  },
  {
   "soc": "25-2023.00",
   "title": "Career/Technical Education Teachers, Middle School",
   "similarity": 0.9617
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9611
  }
 ],
 "29-1221.00": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9755
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9727
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9671
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.967
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9642
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9634
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9632
  },
  {
   "soc": "29-2099.08",
   "title": "Patient Representatives",
   "similarity": 0.9629
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9621
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.9618
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9596
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9589
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9584
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9579
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9568
  },
  {
   "soc": "25-2058.00",
   "title": "Special Education Teachers, Secondary School",
   "similarity": 0.9566
  },
  {
   "soc": "25-2051.00",
   "title": "Special Education Teachers, Preschool",
   "similarity": 0.9558
  },
  {
   "soc": "29-2053.00",
   "title": "Psychiatric Technicians",
   "similarity": 0.9556
  },
  {
   "soc": "29-2057.00",
   "title": "Ophthalmic Medical Technicians",
   "similarity": 0.9555
  },
  {
   "soc": "31-2011.00",
   "title": "Occupational Therapy Assistants",
   "similarity": 0.9544
  }
 ],
 "29-1222.00": [
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9788
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9784
  },
  {
   "soc": "29-2011.01",
   "title": "Cytogenetic Technologists",
   "similarity": 0.9776
  },
  {
   "soc": "19-1029.02",
   "title": "Molecular and Cellular Biologists",
   "similarity": 0.9735
  },
  {
   "soc": "29-2036.00",
   "title": "Medical Dosimetrists",
   "similarity": 0.9734
  },
  {
   "soc": "29-2011.02",
   "title": "Cytotechnologists",
   "similarity": 0.9708
  },
  {
   "soc": "19-1029.03",
   "title": "Geneticists",
   "similarity": 0.9689
  },
  {
   "soc": "19-1021.00",
   "title": "Biochemists and Biophysicists",
   "similarity": 0.9678
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9639
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9617
  },
  {
   "soc": "19-2031.00",
   "title": "Chemists",
   "similarity": 0.9614
  },
  {
   "soc": "11-9121.00",
   "title": "Natural Sciences Managers",
   "similarity": 0.9612
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9604
  },
  {
   "soc": "17-2031.00",
   "title": "Bioengineers and Biomedical Engineers",
   "similarity": 0.9604
  },
  {
   "soc": "11-3051.01",
   "title": "Quality Control Systems Managers",
   "similarity": 0.9596
  },
  {
   "soc": "29-2012.00",
   "title": "Medical and Clinical Laboratory Technicians",
   "similarity": 0.9593
  },
  {
   "soc": "17-2112.02",
   "title": "Validation Engineers",
   "similarity": 0.9592
  },
  {
   "soc": "19-4021.00",
   "title": "Biological Technicians",
   "similarity": 0.9586
  },
  {
   "soc": "19-2041.00",
   "title": "Environmental Scientists and Specialists, Including Health",
   "similarity": 0.9585
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9585
  }
 ],
 "29-1223.00": [
  {
   "soc": "19-3033.00",
   "title": "Clinical and Counseling Psychologists",
   "similarity": 0.9794
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.9783
  },
  {
   "soc": "21-1023.00",
   "title": "Mental Health and Substance Abuse Social Workers",
   "similarity": 0.9783
  },
  {
   "soc": "21-1014.00",
   "title": "Mental Health Counselors",
   "similarity": 0.9778
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9774
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9769
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9749
  },
  {
   "soc": "21-1013.00",
   "title": "Marriage and Family Therapists",
   "similarity": 0.9736
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9708
  },
  {
   "soc": "21-1021.00",
   "title": "Child, Family, and School Social Workers",
   "similarity": 0.9688
  },
  {
   "soc": "21-1011.00",
   "title": "Substance Abuse and Behavioral Disorder Counselors",
   "similarity": 0.9685
  },
  {
   "soc": "25-2058.00",
   "title": "Special Education Teachers, Secondary School",
   "similarity": 0.9678
  },
  {
   "soc": "19-3034.00",
   "title": "School Psychologists",
   "similarity": 0.9673
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9663
  },
  {
   "soc": "21-1012.00",
   "title": "Educational, Guidance, and Career Counselors and Advisors",
   "similarity": 0.966
  },
  {
   "soc": "21-1015.00",
   "title": "Rehabilitation Counselors",
   "similarity": 0.9652
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9647
  },
  {
   "soc": "25-1066.00",
   "title": "Psychology Teachers, Postsecondary",
   "similarity": 0.9646
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9625
  },
  {
   "soc": "25-1113.00",
   "title": "Social Work Teachers, Postsecondary",
   "similarity": 0.9616
  }
 ],
 "29-1224.00": [
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9741
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9712
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9704
  },
  {
   "soc": "29-2036.00",
   "title": "Medical Dosimetrists",
   "similarity": 0.9694
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9689
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9654
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9634
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.963
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9622
  },
  {
   "soc": "29-2034.00",
   "title": "Radiologic Technologists and Technicians",
   "similarity": 0.9614
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9603
  },
  {
   "soc": "29-2011.02",
   "title": "Cytotechnologists",
   "similarity": 0.9598
  },
  {
   "soc": "19-1029.02",
   "title": "Molecular and Cellular Biologists",
   "similarity": 0.9596
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9596
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9594
  },
  {
   "soc": "29-2011.01",
   "title": "Cytogenetic Technologists",
   "similarity": 0.9584
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9578
  },
  {
   "soc": "29-2056.00",
   "title": "Veterinary Technologists and Technicians",
   "similarity": 0.9568
  },
  {
   "soc": "29-2057.00",
   "title": "Ophthalmic Medical Technicians",
   "similarity": 0.9562
  },
  {
   "soc": "29-2012.00",
   "title": "Medical and Clinical Laboratory Technicians",
   "similarity": 0.9558
  }
 ],
 "29-1229.00": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.986
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9796
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9796
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9766
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9755
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9737
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9724
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9722
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9712
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9697
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9694
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9694
  },
  {
   "soc": "25-1042.00",
   "title": "Biological Science Teachers, Postsecondary",
   "similarity": 0.9689
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9686
  },
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.9683
  },
  {
   "soc": "25-2023.00",
   "title": "Career/Technical Education Teachers, Middle School",
   "similarity": 0.9679
  },
  {
   "soc": "11-9111.00",
   "title": "Medical and Health Services Managers",
   "similarity": 0.9673
  },
  {
   "soc": "25-2058.00",
   "title": "Special Education Teachers, Secondary School",
   "similarity": 0.9671
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9667
  },
  {
   "soc": "25-1041.00",
   "title": "Agricultural Sciences Teachers, Postsecondary",
   "similarity": 0.9665
  }
 ],
 "29-1229.01": [
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9779
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9771
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9767
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9755
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9738
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9709
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9691
  },
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.969
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9681
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9675
  },
  {
   "soc": "29-2099.08",
   "title": "Patient Representatives",
   "similarity": 0.9669
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9658
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9656
  },
  {
   "soc": "11-9111.00",
   "title": "Medical and Health Services Managers",
   "similarity": 0.964
  },
  {
   "soc": "25-1192.00",
   "title": "Family and Consumer Sciences Teachers, Postsecondary",
   "similarity": 0.9631
  },
  {
   "soc": "25-2058.00",
   "title": "Special Education Teachers, Secondary School",
   "similarity": 0.9631
  },
  {
   "soc": "25-1042.00",
   "title": "Biological Science Teachers, Postsecondary",
   "similarity": 0.9629
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9616
  },
  {
   "soc": "25-1051.00",
   "title": "Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary",
   "similarity": 0.9614
  },
  {
   "soc": "11-9031.00",
   "title": "Education and Childcare Administrators, Preschool and Daycare",
   "similarity": 0.961
  }
 ],
 "29-1229.03": [
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9718
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9704
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9695
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9694
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9682
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9671
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9666
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9657
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9637
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9635
  },
  {
   "soc": "29-2056.00",
   "title": "Veterinary Technologists and Technicians",
   "similarity": 0.9625
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9623
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9621
  },
  {
   "soc": "31-9097.00",
   "title": "Phlebotomists",
   "similarity": 0.9613
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9611
  },
  {
   "soc": "29-2034.00",
   "title": "Radiologic Technologists and Technicians",
   "similarity": 0.9586
  },
  {
   "soc": "31-9091.00",
   "title": "Dental Assistants",
   "similarity": 0.9586
  },
  {
   "soc": "29-9093.00",
   "title": "Surgical Assistants",
   "similarity": 0.9585
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9574
  },
  {
   "soc": "19-5011.00",
   "title": "Occupational Health and Safety Specialists",
   "similarity": 0.957
  }
 ],
 "29-1229.04": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.985
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9826
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9746
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9726
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9696
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.9683
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9683
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9683
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9682
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9678
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9677
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9672
  },
  {
   "soc": "25-2023.00",
   "title": "Career/Technical Education Teachers, Middle School",
   "similarity": 0.9669
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9657
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9657
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9656
  },
  {
   "soc": "31-2011.00",
   "title": "Occupational Therapy Assistants",
   "similarity": 0.9654
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9635
  },
  {
   "soc": "25-2058.00",
   "title": "Special Education Teachers, Secondary School",
   "similarity": 0.9631
  },
  {
   "soc": "25-2032.00",
   "title": "Career/Technical Education Teachers, Secondary School",
   "similarity": 0.9627
  }
 ],
 "29-1229.05": [
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.9839
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9775
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9771
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9765
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.975
  },
  {
   "soc": "25-1053.00",
   "title": "Environmental Science Teachers, Postsecondary",
   "similarity": 0.975
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.9747
  },
  {
   "soc": "11-9111.00",
   "title": "Medical and Health Services Managers",
   "similarity": 0.9737
  },
  {
   "soc": "25-1042.00",
   "title": "Biological Science Teachers, Postsecondary",
   "similarity": 0.9732
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9731
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9729
  },
  {
   "soc": "25-1051.00",
   "title": "Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary",
   "similarity": 0.9711
  },
  {
   "soc": "11-9161.00",
   "title": "Emergency Management Directors",
   "similarity": 0.971
  },
  {
   "soc": "17-2112.01",
   "title": "Human Factors Engineers and Ergonomists",
   "similarity": 0.9708
  },
  {
   "soc": "25-1192.00",
   "title": "Family and Consumer Sciences Teachers, Postsecondary",
   "similarity": 0.9708
  },
  {
   "soc": "13-1111.00",
   "title": "Management Analysts",
   "similarity": 0.9703
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9691
  },
  {
   "soc": "25-1041.00",
   "title": "Agricultural Sciences Teachers, Postsecondary",
   "similarity": 0.9688
  },
  {
   "soc": "25-2058.00",
   "title": "Special Education Teachers, Secondary School",
   "similarity": 0.9686
  },
  {
   "soc": "11-9033.00",
   "title": "Education Administrators, Postsecondary",
   "similarity": 0.9683
  }
 ],
 "29-1241.00": [
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9699
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9697
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9688
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9683
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9682
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9675
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9662
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9636
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.962
  },
  {
   "soc": "29-2057.00",
   "title": "Ophthalmic Medical Technicians",
   "similarity": 0.9615
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9603
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9602
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9587
  },
  {
   "soc": "29-2081.00",
   "title": "Opticians, Dispensing",
   "similarity": 0.9577
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9572
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9571
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.957
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9568
  },
  {
   "soc": "31-9097.00",
   "title": "Phlebotomists",
   "similarity": 0.9558
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9547
  }
 ],
 "29-1242.00": [
  {
   "soc": "29-2043.00",
   "title": "Paramedics",
   "similarity": 0.9768
  },
  {
   "soc": "29-9021.00",
   "title": "Health Information Technologists and Medical Registrars",
   "similarity": 0.9756
  },
  {
   "soc": "29-2042.00",
   "title": "Emergency Medical Technicians",
   "similarity": 0.9719
  },
  {
   "soc": "19-4044.00",
   "title": "Hydrologic Technicians",
   "similarity": 0.9648
  },
  {
   "soc": "15-1299.06",
   "title": "Digital Forensics Analysts",
   "similarity": 0.9558
  },
  {
   "soc": "13-2051.00",
   "title": "Financial and Investment Analysts",
   "similarity": 0.9535
  },
  {
   "soc": "13-2054.00",
   "title": "Financial Risk Specialists",
   "similarity": 0.9524
  },
  {
   "soc": "25-2055.00",
   "title": "Special Education Teachers, Kindergarten",
   "similarity": 0.9496
  },
  {
   "soc": "15-1255.00",
   "title": "Web and Digital Interface Designers",
   "similarity": 0.9486
  },
  {
   "soc": "11-1031.00",
   "title": "Legislators",
   "similarity": 0.9485
  },
  {
   "soc": "15-2051.00",
   "title": "Data Scientists",
   "similarity": 0.9462
  },
  {
   "soc": "17-3028.00",
   "title": "Calibration Technologists and Technicians",
   "similarity": 0.9462
  },
  {
   "soc": "13-1082.00",
   "title": "Project Management Specialists",
   "similarity": 0.9461
  },
  {
   "soc": "15-1299.07",
   "title": "Blockchain Engineers",
   "similarity": 0.945
  },
  {
   "soc": "15-1299.04",
   "title": "Penetration Testers",
   "similarity": 0.9405
  },
  {
   "soc": "27-4015.00",
   "title": "Lighting Technicians",
   "similarity": 0.9381
  },
  {
   "soc": "29-2072.00",
   "title": "Medical Records Specialists",
   "similarity": 0.9328
  },
  {
   "soc": "53-1044.00",
   "title": "First-Line Supervisors of Passenger Attendants",
   "similarity": 0.9265
  },
  {
   "soc": "11-2032.00",
   "title": "Public Relations Managers",
   "similarity": 0.9221
  },
  {
   "soc": "25-3031.00",
   "title": "Substitute Teachers, Short-Term",
   "similarity": 0.4712
  }
 ],
 "29-1249.00": [
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.8735
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.8677
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.863
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.8596
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.8591
  },
  {
   "soc": "25-2051.00",
   "title": "Special Education Teachers, Preschool",
   "similarity": 0.8569
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.8561
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.8559
  },
  {
   "soc": "29-2036.00",
   "title": "Medical Dosimetrists",
   "similarity": 0.8558
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.8551
  },
  {
   "soc": "25-3031.00",
   "title": "Substitute Teachers, Short-Term",
   "similarity": 0.8551
  },
  {
   "soc": "25-3011.00",
   "title": "Adult Basic Education, Adult Secondary Education, and English as a Second Language Instructors",
   "similarity": 0.8549
  },
  {
   "soc": "25-9044.00",
   "title": "Teaching Assistants, Postsecondary",
   "similarity": 0.8539
  },
  {
   "soc": "19-3039.02",
   "title": "Neuropsychologists",
   "similarity": 0.8534
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.8531
  },
  {
   "soc": "25-3021.00",
   "title": "Self-Enrichment Teachers",
   "similarity": 0.8524
  },
  {
   "soc": "19-3033.00",
   "title": "Clinical and Counseling Psychologists",
   "similarity": 0.8517
  },
  {
   "soc": "19-3034.00",
   "title": "School Psychologists",
   "similarity": 0.8516
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.8516
  },
  {
   "soc": "15-1211.01",
   "title": "Health Informatics Specialists",
   "similarity": 0.8513
  }
 ]
};

/** O*NET titles for all SOC codes used in the FISCMAK seed. */
export const SOC_TITLES: Readonly<Record<string, string>> = {
  "29-1211.00": "Anesthesiologists",
  "29-1213.00": "Dermatologists",
  "29-1214.00": "Emergency Medicine Physicians",
  "29-1215.00": "Family Medicine Physicians",
  "29-1216.00": "General Internal Medicine Physicians",
  "29-1217.00": "Neurologists",
  "29-1218.00": "Obstetricians and Gynecologists",
  "29-1221.00": "Pediatricians, General",
  "29-1222.00": "Physicians, Pathologists",
  "29-1223.00": "Psychiatrists",
  "29-1224.00": "Radiologists",
  "29-1229.00": "Physicians, All Other",
  "29-1229.01": "Allergists and Immunologists",
  "29-1229.03": "Urologists",
  "29-1229.04": "Physical Medicine and Rehabilitation Physicians",
  "29-1229.05": "Preventive Medicine Physicians",
  "29-1241.00": "Ophthalmologists, Except Pediatric",
  "29-1242.00": "Orthopedic Surgeons, Except Pediatric",
  "29-1249.00": "Surgeons, All Other",
  "25-1071.00": "Health Specialties Teachers, Postsecondary",
  "19-1042.00": "Medical Scientists, Except Epidemiologists",
  "11-9111.00": "Medical and Health Services Managers",
  "21-1094.00": "Community Health Workers",
  "15-2051.00": "Data Scientists",
  "29-9021.00": "Health Information Technologists and Medical Registrars",
  "21-1014.00": "Mental Health Counselors",
  "13-1082.00": "Project Management Specialists",
  "13-1111.00": "Management Analysts",
  "15-1211.00": "Computer Systems Analysts",
  "15-1252.00": "Software Developers",
  "15-1255.00": "Web and Digital Interface Designers",
  "17-2031.00": "Bioengineers and Biomedical Engineers",
  "17-2112.00": "Industrial Engineers",
  "19-1041.00": "Epidemiologists",
  "19-3032.00": "Industrial-Organizational Psychologists",
  "21-1022.00": "Healthcare Social Workers",
  "23-1022.00": "Arbitrators, Mediators, and Conciliators",
  "25-9031.00": "Instructional Coordinators",
  "27-3042.00": "Technical Writers",
  "29-2034.00": "Radiologic Technologists and Technicians",
  "29-9092.00": "Genetic Counselors",
  "27-4021.00": "Photographers",
  "27-2042.00": "Musicians and Singers",
  "27-3043.00": "Writers and Authors",
  "27-1013.00": "Fine Artists, Including Painters, Sculptors, and Illustrators",
  "29-9091.00": "Athletic Trainers",
  "35-1011.00": "Chefs and Head Cooks"
};
