// AUTO-GENERATED by docs/seeds/onet/build-onet-seed.mjs — do not edit manually.
// Source: O*NET 30.3 Database, U.S. DOL/ETA, May 2026. CC-BY 4.0.
// Normalization: dual-scale V=100×((Im-1)/4)×(Lv/7); single-scale V=((x-min)/(max-min))×100 (declared anchors)
// https://www.onetcenter.org/license_db.html

export type AdjacentOccupation = { soc: string; title: string; similarity: number };

/** Top-20 non-physician Job-Zone-≥3 adjacent occupations per physician SOC (cosine similarity on 250-dim vectors). */
export const ADJACENCY_BASKETS: Readonly<Record<string, readonly AdjacentOccupation[]>> = {
 "29-1211.00": [
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9598
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9552
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9508
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9464
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9439
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9432
  },
  {
   "soc": "29-2056.00",
   "title": "Veterinary Technologists and Technicians",
   "similarity": 0.9431
  },
  {
   "soc": "29-2055.00",
   "title": "Surgical Technologists",
   "similarity": 0.9423
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9414
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9408
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.94
  },
  {
   "soc": "29-2034.00",
   "title": "Radiologic Technologists and Technicians",
   "similarity": 0.9357
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9345
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9326
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9321
  },
  {
   "soc": "29-2012.00",
   "title": "Medical and Clinical Laboratory Technicians",
   "similarity": 0.9318
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9317
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9283
  },
  {
   "soc": "31-9091.00",
   "title": "Dental Assistants",
   "similarity": 0.9275
  },
  {
   "soc": "31-9097.00",
   "title": "Phlebotomists",
   "similarity": 0.9247
  }
 ],
 "29-1213.00": [
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9606
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9552
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9512
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9478
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9434
  },
  {
   "soc": "29-2057.00",
   "title": "Ophthalmic Medical Technicians",
   "similarity": 0.942
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9413
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.94
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9379
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9352
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9349
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9347
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9339
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9336
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9335
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9329
  },
  {
   "soc": "25-2023.00",
   "title": "Career/Technical Education Teachers, Middle School",
   "similarity": 0.9276
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9273
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9264
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9248
  }
 ],
 "29-1214.00": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9565
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9543
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9536
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.947
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9391
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.936
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9347
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9346
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9328
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9315
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9314
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9308
  },
  {
   "soc": "25-2023.00",
   "title": "Career/Technical Education Teachers, Middle School",
   "similarity": 0.9293
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.9292
  },
  {
   "soc": "25-2032.00",
   "title": "Career/Technical Education Teachers, Secondary School",
   "similarity": 0.9288
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9284
  },
  {
   "soc": "31-2011.00",
   "title": "Occupational Therapy Assistants",
   "similarity": 0.9282
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9272
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9252
  },
  {
   "soc": "29-2056.00",
   "title": "Veterinary Technologists and Technicians",
   "similarity": 0.9249
  }
 ],
 "29-1215.00": [
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9446
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9419
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9366
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9351
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.935
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9302
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9268
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9264
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9248
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.9245
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9197
  },
  {
   "soc": "29-2057.00",
   "title": "Ophthalmic Medical Technicians",
   "similarity": 0.9187
  },
  {
   "soc": "31-9099.01",
   "title": "Speech-Language Pathology Assistants",
   "similarity": 0.9177
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9167
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9155
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9147
  },
  {
   "soc": "21-1021.00",
   "title": "Child, Family, and School Social Workers",
   "similarity": 0.9144
  },
  {
   "soc": "21-1012.00",
   "title": "Educational, Guidance, and Career Counselors and Advisors",
   "similarity": 0.9141
  },
  {
   "soc": "21-1023.00",
   "title": "Mental Health and Substance Abuse Social Workers",
   "similarity": 0.914
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9126
  }
 ],
 "29-1216.00": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9606
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.959
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9458
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9439
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9428
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9402
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9399
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9388
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.938
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.934
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9338
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9334
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9333
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9328
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9314
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.9308
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9301
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9295
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9294
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9271
  }
 ],
 "29-1217.00": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9649
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9574
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9566
  },
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.9538
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9533
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9447
  },
  {
   "soc": "25-1042.00",
   "title": "Biological Science Teachers, Postsecondary",
   "similarity": 0.9414
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9382
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9375
  },
  {
   "soc": "21-1023.00",
   "title": "Mental Health and Substance Abuse Social Workers",
   "similarity": 0.9341
  },
  {
   "soc": "25-1066.00",
   "title": "Psychology Teachers, Postsecondary",
   "similarity": 0.9338
  },
  {
   "soc": "11-9121.00",
   "title": "Natural Sciences Managers",
   "similarity": 0.9329
  },
  {
   "soc": "11-9111.00",
   "title": "Medical and Health Services Managers",
   "similarity": 0.9324
  },
  {
   "soc": "19-1029.03",
   "title": "Geneticists",
   "similarity": 0.932
  },
  {
   "soc": "21-1011.00",
   "title": "Substance Abuse and Behavioral Disorder Counselors",
   "similarity": 0.9317
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9316
  },
  {
   "soc": "19-3039.03",
   "title": "Clinical Neuropsychologists",
   "similarity": 0.9316
  },
  {
   "soc": "21-1012.00",
   "title": "Educational, Guidance, and Career Counselors and Advisors",
   "similarity": 0.9315
  },
  {
   "soc": "17-2112.01",
   "title": "Human Factors Engineers and Ergonomists",
   "similarity": 0.9311
  },
  {
   "soc": "11-9033.00",
   "title": "Education Administrators, Postsecondary",
   "similarity": 0.931
  }
 ],
 "29-1218.00": [
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9689
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9648
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9519
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9449
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9437
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9421
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9416
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9404
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.939
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9377
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9348
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9335
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9329
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9325
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9314
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.931
  },
  {
   "soc": "25-2023.00",
   "title": "Career/Technical Education Teachers, Middle School",
   "similarity": 0.931
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9305
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9293
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9287
  }
 ],
 "29-1221.00": [
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9579
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.953
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9477
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9422
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.9409
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9394
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9384
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9353
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9342
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9334
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9312
  },
  {
   "soc": "25-2051.00",
   "title": "Special Education Teachers, Preschool",
   "similarity": 0.9296
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9291
  },
  {
   "soc": "31-2011.00",
   "title": "Occupational Therapy Assistants",
   "similarity": 0.9288
  },
  {
   "soc": "25-2023.00",
   "title": "Career/Technical Education Teachers, Middle School",
   "similarity": 0.9278
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9271
  },
  {
   "soc": "29-2053.00",
   "title": "Psychiatric Technicians",
   "similarity": 0.9265
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9255
  },
  {
   "soc": "21-1023.00",
   "title": "Mental Health and Substance Abuse Social Workers",
   "similarity": 0.9233
  },
  {
   "soc": "21-1012.00",
   "title": "Educational, Guidance, and Career Counselors and Advisors",
   "similarity": 0.9232
  }
 ],
 "29-1222.00": [
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9667
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9643
  },
  {
   "soc": "29-2011.01",
   "title": "Cytogenetic Technologists",
   "similarity": 0.9603
  },
  {
   "soc": "19-1029.02",
   "title": "Molecular and Cellular Biologists",
   "similarity": 0.9539
  },
  {
   "soc": "29-2011.02",
   "title": "Cytotechnologists",
   "similarity": 0.9507
  },
  {
   "soc": "19-1029.03",
   "title": "Geneticists",
   "similarity": 0.9501
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9447
  },
  {
   "soc": "19-1021.00",
   "title": "Biochemists and Biophysicists",
   "similarity": 0.9404
  },
  {
   "soc": "19-4021.00",
   "title": "Biological Technicians",
   "similarity": 0.9392
  },
  {
   "soc": "19-2041.00",
   "title": "Environmental Scientists and Specialists, Including Health",
   "similarity": 0.9384
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9383
  },
  {
   "soc": "19-2031.00",
   "title": "Chemists",
   "similarity": 0.9379
  },
  {
   "soc": "11-9121.00",
   "title": "Natural Sciences Managers",
   "similarity": 0.9347
  },
  {
   "soc": "19-1012.00",
   "title": "Food Scientists and Technologists",
   "similarity": 0.9338
  },
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.9338
  },
  {
   "soc": "17-2031.00",
   "title": "Bioengineers and Biomedical Engineers",
   "similarity": 0.9328
  },
  {
   "soc": "29-2012.00",
   "title": "Medical and Clinical Laboratory Technicians",
   "similarity": 0.9297
  },
  {
   "soc": "11-3051.01",
   "title": "Quality Control Systems Managers",
   "similarity": 0.9294
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9277
  },
  {
   "soc": "19-1029.01",
   "title": "Bioinformatics Scientists",
   "similarity": 0.9271
  }
 ],
 "29-1223.00": [
  {
   "soc": "21-1023.00",
   "title": "Mental Health and Substance Abuse Social Workers",
   "similarity": 0.964
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9638
  },
  {
   "soc": "21-1014.00",
   "title": "Mental Health Counselors",
   "similarity": 0.9627
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.9608
  },
  {
   "soc": "21-1013.00",
   "title": "Marriage and Family Therapists",
   "similarity": 0.9606
  },
  {
   "soc": "21-1011.00",
   "title": "Substance Abuse and Behavioral Disorder Counselors",
   "similarity": 0.9534
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9533
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9492
  },
  {
   "soc": "21-1012.00",
   "title": "Educational, Guidance, and Career Counselors and Advisors",
   "similarity": 0.9467
  },
  {
   "soc": "21-1021.00",
   "title": "Child, Family, and School Social Workers",
   "similarity": 0.9455
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9429
  },
  {
   "soc": "21-1015.00",
   "title": "Rehabilitation Counselors",
   "similarity": 0.937
  },
  {
   "soc": "25-1066.00",
   "title": "Psychology Teachers, Postsecondary",
   "similarity": 0.9351
  },
  {
   "soc": "25-1113.00",
   "title": "Social Work Teachers, Postsecondary",
   "similarity": 0.9334
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9322
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9312
  },
  {
   "soc": "25-1192.00",
   "title": "Family and Consumer Sciences Teachers, Postsecondary",
   "similarity": 0.9292
  },
  {
   "soc": "11-9151.00",
   "title": "Social and Community Service Managers",
   "similarity": 0.9268
  },
  {
   "soc": "11-9033.00",
   "title": "Education Administrators, Postsecondary",
   "similarity": 0.926
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.926
  }
 ],
 "29-1224.00": [
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9477
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9469
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9426
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.941
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9352
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9346
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9345
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9344
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9342
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9339
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9337
  },
  {
   "soc": "19-1029.02",
   "title": "Molecular and Cellular Biologists",
   "similarity": 0.9282
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9266
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9265
  },
  {
   "soc": "29-2034.00",
   "title": "Radiologic Technologists and Technicians",
   "similarity": 0.926
  },
  {
   "soc": "29-2011.02",
   "title": "Cytotechnologists",
   "similarity": 0.9253
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9234
  },
  {
   "soc": "17-2031.00",
   "title": "Bioengineers and Biomedical Engineers",
   "similarity": 0.9233
  },
  {
   "soc": "29-2011.01",
   "title": "Cytogenetic Technologists",
   "similarity": 0.9233
  },
  {
   "soc": "19-1029.03",
   "title": "Geneticists",
   "similarity": 0.9228
  }
 ],
 "29-1229.00": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9748
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9644
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9634
  },
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.9529
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9528
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9503
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9472
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9471
  },
  {
   "soc": "25-1042.00",
   "title": "Biological Science Teachers, Postsecondary",
   "similarity": 0.9468
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9448
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9435
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9432
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9429
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.942
  },
  {
   "soc": "25-1053.00",
   "title": "Environmental Science Teachers, Postsecondary",
   "similarity": 0.9419
  },
  {
   "soc": "25-2023.00",
   "title": "Career/Technical Education Teachers, Middle School",
   "similarity": 0.9415
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9413
  },
  {
   "soc": "11-9111.00",
   "title": "Medical and Health Services Managers",
   "similarity": 0.9409
  },
  {
   "soc": "11-9121.00",
   "title": "Natural Sciences Managers",
   "similarity": 0.9409
  },
  {
   "soc": "25-2032.00",
   "title": "Career/Technical Education Teachers, Secondary School",
   "similarity": 0.9405
  }
 ],
 "29-1229.01": [
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9606
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9586
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9555
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9539
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9532
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9488
  },
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.9465
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9406
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.94
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9387
  },
  {
   "soc": "21-1012.00",
   "title": "Educational, Guidance, and Career Counselors and Advisors",
   "similarity": 0.938
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9367
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9366
  },
  {
   "soc": "25-1192.00",
   "title": "Family and Consumer Sciences Teachers, Postsecondary",
   "similarity": 0.9351
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9348
  },
  {
   "soc": "13-2099.04",
   "title": "Fraud Examiners, Investigators and Analysts",
   "similarity": 0.9342
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.934
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9334
  },
  {
   "soc": "19-2041.00",
   "title": "Environmental Scientists and Specialists, Including Health",
   "similarity": 0.9333
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.933
  }
 ],
 "29-1229.03": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9516
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.944
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9435
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9417
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9417
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9363
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9362
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9346
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9333
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9283
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9271
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.927
  },
  {
   "soc": "29-2035.00",
   "title": "Magnetic Resonance Imaging Technologists",
   "similarity": 0.9261
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9248
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9243
  },
  {
   "soc": "19-1029.02",
   "title": "Molecular and Cellular Biologists",
   "similarity": 0.9229
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.921
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9209
  },
  {
   "soc": "11-3051.01",
   "title": "Quality Control Systems Managers",
   "similarity": 0.9206
  },
  {
   "soc": "29-2056.00",
   "title": "Veterinary Technologists and Technicians",
   "similarity": 0.9201
  }
 ],
 "29-1229.04": [
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.974
  },
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9694
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9566
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9439
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.9438
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.9408
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.9404
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9404
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.9396
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.939
  },
  {
   "soc": "25-2023.00",
   "title": "Career/Technical Education Teachers, Middle School",
   "similarity": 0.9384
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.9381
  },
  {
   "soc": "21-1022.00",
   "title": "Healthcare Social Workers",
   "similarity": 0.938
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9375
  },
  {
   "soc": "29-9091.00",
   "title": "Athletic Trainers",
   "similarity": 0.9366
  },
  {
   "soc": "21-1011.00",
   "title": "Substance Abuse and Behavioral Disorder Counselors",
   "similarity": 0.936
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9356
  },
  {
   "soc": "25-2032.00",
   "title": "Career/Technical Education Teachers, Secondary School",
   "similarity": 0.9343
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.934
  },
  {
   "soc": "25-1042.00",
   "title": "Biological Science Teachers, Postsecondary",
   "similarity": 0.9335
  }
 ],
 "29-1229.05": [
  {
   "soc": "19-1041.00",
   "title": "Epidemiologists",
   "similarity": 0.973
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.965
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9649
  },
  {
   "soc": "25-1041.00",
   "title": "Agricultural Sciences Teachers, Postsecondary",
   "similarity": 0.9548
  },
  {
   "soc": "11-9161.00",
   "title": "Emergency Management Directors",
   "similarity": 0.9539
  },
  {
   "soc": "25-1042.00",
   "title": "Biological Science Teachers, Postsecondary",
   "similarity": 0.9535
  },
  {
   "soc": "25-1193.00",
   "title": "Recreation and Fitness Studies Teachers, Postsecondary",
   "similarity": 0.9534
  },
  {
   "soc": "25-1053.00",
   "title": "Environmental Science Teachers, Postsecondary",
   "similarity": 0.9528
  },
  {
   "soc": "11-9033.00",
   "title": "Education Administrators, Postsecondary",
   "similarity": 0.9517
  },
  {
   "soc": "11-9121.00",
   "title": "Natural Sciences Managers",
   "similarity": 0.9509
  },
  {
   "soc": "19-2041.00",
   "title": "Environmental Scientists and Specialists, Including Health",
   "similarity": 0.9508
  },
  {
   "soc": "17-2112.01",
   "title": "Human Factors Engineers and Ergonomists",
   "similarity": 0.9503
  },
  {
   "soc": "11-9111.00",
   "title": "Medical and Health Services Managers",
   "similarity": 0.9496
  },
  {
   "soc": "13-1111.00",
   "title": "Management Analysts",
   "similarity": 0.9495
  },
  {
   "soc": "21-1091.00",
   "title": "Health Education Specialists",
   "similarity": 0.9495
  },
  {
   "soc": "29-9092.00",
   "title": "Genetic Counselors",
   "similarity": 0.948
  },
  {
   "soc": "19-3032.00",
   "title": "Industrial-Organizational Psychologists",
   "similarity": 0.9467
  },
  {
   "soc": "25-1051.00",
   "title": "Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary",
   "similarity": 0.9449
  },
  {
   "soc": "25-1043.00",
   "title": "Forestry and Conservation Science Teachers, Postsecondary",
   "similarity": 0.9445
  },
  {
   "soc": "25-9031.00",
   "title": "Instructional Coordinators",
   "similarity": 0.9445
  }
 ],
 "29-1241.00": [
  {
   "soc": "29-9099.01",
   "title": "Midwives",
   "similarity": 0.9547
  },
  {
   "soc": "25-1072.00",
   "title": "Nursing Instructors and Teachers, Postsecondary",
   "similarity": 0.9475
  },
  {
   "soc": "29-2099.01",
   "title": "Neurodiagnostic Technologists",
   "similarity": 0.9469
  },
  {
   "soc": "29-2099.05",
   "title": "Ophthalmic Medical Technologists",
   "similarity": 0.946
  },
  {
   "soc": "31-9092.00",
   "title": "Medical Assistants",
   "similarity": 0.9458
  },
  {
   "soc": "29-2032.00",
   "title": "Diagnostic Medical Sonographers",
   "similarity": 0.9454
  },
  {
   "soc": "29-2061.00",
   "title": "Licensed Practical and Licensed Vocational Nurses",
   "similarity": 0.9435
  },
  {
   "soc": "29-2031.00",
   "title": "Cardiovascular Technologists and Technicians",
   "similarity": 0.9391
  },
  {
   "soc": "11-9121.01",
   "title": "Clinical Research Coordinators",
   "similarity": 0.939
  },
  {
   "soc": "29-2011.00",
   "title": "Medical and Clinical Laboratory Technologists",
   "similarity": 0.9382
  },
  {
   "soc": "19-1042.00",
   "title": "Medical Scientists, Except Epidemiologists",
   "similarity": 0.9326
  },
  {
   "soc": "29-2057.00",
   "title": "Ophthalmic Medical Technicians",
   "similarity": 0.9317
  },
  {
   "soc": "19-1022.00",
   "title": "Microbiologists",
   "similarity": 0.9309
  },
  {
   "soc": "29-2092.00",
   "title": "Hearing Aid Specialists",
   "similarity": 0.9308
  },
  {
   "soc": "29-2033.00",
   "title": "Nuclear Medicine Technologists",
   "similarity": 0.9293
  },
  {
   "soc": "29-2081.00",
   "title": "Opticians, Dispensing",
   "similarity": 0.9291
  },
  {
   "soc": "29-2091.00",
   "title": "Orthotists and Prosthetists",
   "similarity": 0.929
  },
  {
   "soc": "25-1071.00",
   "title": "Health Specialties Teachers, Postsecondary",
   "similarity": 0.9276
  },
  {
   "soc": "31-2021.00",
   "title": "Physical Therapist Assistants",
   "similarity": 0.9274
  },
  {
   "soc": "21-1094.00",
   "title": "Community Health Workers",
   "similarity": 0.926
  }
 ],
 "29-1242.00": [
  {
   "soc": "13-2051.00",
   "title": "Financial and Investment Analysts",
   "similarity": 0.9041
  },
  {
   "soc": "11-1031.00",
   "title": "Legislators",
   "similarity": 0.8886
  },
  {
   "soc": "29-2043.00",
   "title": "Paramedics",
   "similarity": 0.6656
  },
  {
   "soc": "15-1299.06",
   "title": "Digital Forensics Analysts",
   "similarity": 0.6628
  },
  {
   "soc": "29-2042.00",
   "title": "Emergency Medical Technicians",
   "similarity": 0.6604
  },
  {
   "soc": "29-9021.00",
   "title": "Health Information Technologists and Medical Registrars",
   "similarity": 0.655
  },
  {
   "soc": "15-1299.04",
   "title": "Penetration Testers",
   "similarity": 0.6522
  },
  {
   "soc": "15-1299.07",
   "title": "Blockchain Engineers",
   "similarity": 0.6328
  },
  {
   "soc": "13-2054.00",
   "title": "Financial Risk Specialists",
   "similarity": 0.6324
  },
  {
   "soc": "19-4044.00",
   "title": "Hydrologic Technicians",
   "similarity": 0.6319
  },
  {
   "soc": "15-2051.00",
   "title": "Data Scientists",
   "similarity": 0.6192
  },
  {
   "soc": "25-2055.00",
   "title": "Special Education Teachers, Kindergarten",
   "similarity": 0.609
  },
  {
   "soc": "17-3028.00",
   "title": "Calibration Technologists and Technicians",
   "similarity": 0.6048
  },
  {
   "soc": "13-1082.00",
   "title": "Project Management Specialists",
   "similarity": 0.6018
  },
  {
   "soc": "15-1255.00",
   "title": "Web and Digital Interface Designers",
   "similarity": 0.5932
  },
  {
   "soc": "29-2072.00",
   "title": "Medical Records Specialists",
   "similarity": 0.5873
  },
  {
   "soc": "27-4015.00",
   "title": "Lighting Technicians",
   "similarity": 0.5459
  },
  {
   "soc": "11-2032.00",
   "title": "Public Relations Managers",
   "similarity": 0.5414
  },
  {
   "soc": "53-1044.00",
   "title": "First-Line Supervisors of Passenger Attendants",
   "similarity": 0.534
  },
  {
   "soc": "25-1022.00",
   "title": "Mathematical Science Teachers, Postsecondary",
   "similarity": 0.4492
  }
 ],
 "29-1249.00": [
  {
   "soc": "13-2051.00",
   "title": "Financial and Investment Analysts",
   "similarity": 0.649
  },
  {
   "soc": "11-1031.00",
   "title": "Legislators",
   "similarity": 0.6341
  },
  {
   "soc": "13-1011.00",
   "title": "Agents and Business Managers of Artists, Performers, and Athletes",
   "similarity": 0.3345
  },
  {
   "soc": "11-3111.00",
   "title": "Compensation and Benefits Managers",
   "similarity": 0.3216
  },
  {
   "soc": "23-1023.00",
   "title": "Judges, Magistrate Judges, and Magistrates",
   "similarity": 0.3211
  },
  {
   "soc": "13-1131.00",
   "title": "Fundraisers",
   "similarity": 0.3168
  },
  {
   "soc": "25-3021.00",
   "title": "Self-Enrichment Teachers",
   "similarity": 0.3164
  },
  {
   "soc": "27-1013.00",
   "title": "Fine Artists, Including Painters, Sculptors, and Illustrators",
   "similarity": 0.3146
  },
  {
   "soc": "11-2021.00",
   "title": "Marketing Managers",
   "similarity": 0.3135
  },
  {
   "soc": "25-3011.00",
   "title": "Adult Basic Education, Adult Secondary Education, and English as a Second Language Instructors",
   "similarity": 0.3132
  },
  {
   "soc": "11-1011.03",
   "title": "Chief Sustainability Officers",
   "similarity": 0.3111
  },
  {
   "soc": "11-9199.11",
   "title": "Brownfield Redevelopment Specialists and Site Managers",
   "similarity": 0.311
  },
  {
   "soc": "11-9199.10",
   "title": "Wind Energy Development Managers",
   "similarity": 0.3107
  },
  {
   "soc": "11-1021.00",
   "title": "General and Operations Managers",
   "similarity": 0.3101
  },
  {
   "soc": "25-1065.00",
   "title": "Political Science Teachers, Postsecondary",
   "similarity": 0.3097
  },
  {
   "soc": "21-2011.00",
   "title": "Clergy",
   "similarity": 0.308
  },
  {
   "soc": "25-1123.00",
   "title": "English Language and Literature Teachers, Postsecondary",
   "similarity": 0.3077
  },
  {
   "soc": "25-1112.00",
   "title": "Law Teachers, Postsecondary",
   "similarity": 0.3074
  },
  {
   "soc": "13-1075.00",
   "title": "Labor Relations Specialists",
   "similarity": 0.3059
  },
  {
   "soc": "19-3011.01",
   "title": "Environmental Economists",
   "similarity": 0.3059
  }
 ]
};

export const SOC_TITLES: Readonly<Record<string, string>> = {
  "29-1211.00": "Anesthesiologists",
  "29-1213.00": "Dermatologists",
  "29-1214.00": "Emergency Medicine Physicians",
  "29-1215.00": "Family Medicine Physicians",
  "29-1216.00": "General Internal Medicine Physicians",
  "29-1217.00": "Neurologists",
  "29-1218.00": "Obstetricians and Gynecologists",
  "29-1221.00": "Pediatricians, General",
  "29-1222.00": "Physicians, Pathologists",
  "29-1223.00": "Psychiatrists",
  "29-1224.00": "Radiologists",
  "29-1229.00": "Physicians, All Other",
  "29-1229.01": "Allergists and Immunologists",
  "29-1229.03": "Urologists",
  "29-1229.04": "Physical Medicine and Rehabilitation Physicians",
  "29-1229.05": "Preventive Medicine Physicians",
  "29-1241.00": "Ophthalmologists, Except Pediatric",
  "29-1242.00": "Orthopedic Surgeons, Except Pediatric",
  "29-1249.00": "Surgeons, All Other",
  "25-1071.00": "Health Specialties Teachers, Postsecondary",
  "19-1042.00": "Medical Scientists, Except Epidemiologists",
  "11-9111.00": "Medical and Health Services Managers",
  "21-1094.00": "Community Health Workers",
  "15-2051.00": "Data Scientists",
  "29-9021.00": "Health Information Technologists and Medical Registrars",
  "21-1014.00": "Mental Health Counselors",
  "13-1082.00": "Project Management Specialists",
  "13-1111.00": "Management Analysts",
  "15-1211.00": "Computer Systems Analysts",
  "15-1252.00": "Software Developers",
  "15-1255.00": "Web and Digital Interface Designers",
  "17-2031.00": "Bioengineers and Biomedical Engineers",
  "17-2112.00": "Industrial Engineers",
  "19-1041.00": "Epidemiologists",
  "19-3032.00": "Industrial-Organizational Psychologists",
  "21-1022.00": "Healthcare Social Workers",
  "23-1022.00": "Arbitrators, Mediators, and Conciliators",
  "25-9031.00": "Instructional Coordinators",
  "27-3042.00": "Technical Writers",
  "29-2034.00": "Radiologic Technologists and Technicians",
  "29-9092.00": "Genetic Counselors",
  "27-4021.00": "Photographers",
  "27-2042.00": "Musicians and Singers",
  "27-3043.00": "Writers and Authors",
  "27-1013.00": "Fine Artists, Including Painters, Sculptors, and Illustrators",
  "29-9091.00": "Athletic Trainers",
  "35-1011.00": "Chefs and Head Cooks",
  "29-1212.00": "Cardiologists",
  "17-2072.00": "Electronics Engineers, Except Computer",
  "29-2031.00": "Cardiovascular Technologists and Technicians",
  "29-1126.00": "Respiratory Therapists",
  "25-1042.00": "Biological Science Teachers, Postsecondary",
  "21-1015.00": "Rehabilitation Counselors",
  "21-1011.00": "Substance Abuse and Behavioral Disorder Counselors",
  "21-1012.00": "Educational, Guidance, and Career Counselors and Advisors",
  "29-2099.00": "Health Technologists and Technicians, All Other",
  "19-4092.00": "Forensic Science Technicians",
  "29-1123.00": "Physical Therapists",
  "29-1029.00": "Dentists, All Other Specialists",
  "51-9071.00": "Jewelers and Precious Stone and Metal Workers",
  "29-1127.00": "Speech-Language Pathologists",
  "29-2033.00": "Nuclear Medicine Technologists",
  "17-2199.00": "Engineers, All Other",
  "11-9121.00": "Natural Sciences Managers",
  "19-2031.00": "Chemists",
  "19-1022.00": "Microbiologists",
  "29-2032.00": "Diagnostic Medical Sonographers",
  "29-1161.00": "Nurse Midwives",
  "29-1041.00": "Optometrists",
  "17-2011.00": "Aerospace Engineers",
  "19-3033.00": "Clinical and Counseling Psychologists",
  "11-9161.00": "Emergency Management Directors",
  "29-2042.00": "Emergency Medical Technicians",
  "29-2043.00": "Paramedics",
  "25-2059.00": "Special Education Teachers, All Other",
  "29-2011.00": "Medical and Clinical Laboratory Technologists",
  "13-1041.00": "Compliance Officers"
};
