// AUTO-GENERATED by docs/seeds/onet/build-onet-seed.mjs — do not edit manually.
// Source: O*NET 30.3 Database, U.S. DOL/ETA, May 2026. CC-BY 4.0.
// Normalization: dual-scale V=100×((Im-1)/4)×(Lv/7); single-scale V=((x-min)/(max-min))×100 (declared anchors)
// https://www.onetcenter.org/license_db.html

export type OnetDescriptor = {
  idx: number;
  elementId: string;
  title: string;
  category: "Abilities"|"Knowledge"|"WorkActivities"|"EssentialSkills"|"TransferableSkills"|"WorkContext"|"WorkStyles"|"WorkValues"|"RIASEC"|"JobZone";
};

export const DESCRIPTOR_CATALOG: readonly OnetDescriptor[] = [
  {
    "idx": 0,
    "elementId": "1.A.1.a.1",
    "title": "Oral Comprehension",
    "category": "Abilities"
  },
  {
    "idx": 1,
    "elementId": "1.A.1.a.2",
    "title": "Written Comprehension",
    "category": "Abilities"
  },
  {
    "idx": 2,
    "elementId": "1.A.1.a.3",
    "title": "Oral Expression",
    "category": "Abilities"
  },
  {
    "idx": 3,
    "elementId": "1.A.1.a.4",
    "title": "Written Expression",
    "category": "Abilities"
  },
  {
    "idx": 4,
    "elementId": "1.A.1.b.1",
    "title": "Fluency of Ideas",
    "category": "Abilities"
  },
  {
    "idx": 5,
    "elementId": "1.A.1.b.2",
    "title": "Originality",
    "category": "Abilities"
  },
  {
    "idx": 6,
    "elementId": "1.A.1.b.3",
    "title": "Problem Sensitivity",
    "category": "Abilities"
  },
  {
    "idx": 7,
    "elementId": "1.A.1.b.4",
    "title": "Deductive Reasoning",
    "category": "Abilities"
  },
  {
    "idx": 8,
    "elementId": "1.A.1.b.5",
    "title": "Inductive Reasoning",
    "category": "Abilities"
  },
  {
    "idx": 9,
    "elementId": "1.A.1.b.6",
    "title": "Information Ordering",
    "category": "Abilities"
  },
  {
    "idx": 10,
    "elementId": "1.A.1.b.7",
    "title": "Category Flexibility",
    "category": "Abilities"
  },
  {
    "idx": 11,
    "elementId": "1.A.1.c.1",
    "title": "Mathematical Reasoning",
    "category": "Abilities"
  },
  {
    "idx": 12,
    "elementId": "1.A.1.c.2",
    "title": "Number Facility",
    "category": "Abilities"
  },
  {
    "idx": 13,
    "elementId": "1.A.1.d.1",
    "title": "Memorization",
    "category": "Abilities"
  },
  {
    "idx": 14,
    "elementId": "1.A.1.e.1",
    "title": "Speed of Closure",
    "category": "Abilities"
  },
  {
    "idx": 15,
    "elementId": "1.A.1.e.2",
    "title": "Flexibility of Closure",
    "category": "Abilities"
  },
  {
    "idx": 16,
    "elementId": "1.A.1.e.3",
    "title": "Perceptual Speed",
    "category": "Abilities"
  },
  {
    "idx": 17,
    "elementId": "1.A.1.f.1",
    "title": "Spatial Orientation",
    "category": "Abilities"
  },
  {
    "idx": 18,
    "elementId": "1.A.1.f.2",
    "title": "Visualization",
    "category": "Abilities"
  },
  {
    "idx": 19,
    "elementId": "1.A.1.g.1",
    "title": "Selective Attention",
    "category": "Abilities"
  },
  {
    "idx": 20,
    "elementId": "1.A.1.g.2",
    "title": "Time Sharing",
    "category": "Abilities"
  },
  {
    "idx": 21,
    "elementId": "1.A.2.a.1",
    "title": "Arm-Hand Steadiness",
    "category": "Abilities"
  },
  {
    "idx": 22,
    "elementId": "1.A.2.a.2",
    "title": "Manual Dexterity",
    "category": "Abilities"
  },
  {
    "idx": 23,
    "elementId": "1.A.2.a.3",
    "title": "Finger Dexterity",
    "category": "Abilities"
  },
  {
    "idx": 24,
    "elementId": "1.A.2.b.1",
    "title": "Control Precision",
    "category": "Abilities"
  },
  {
    "idx": 25,
    "elementId": "1.A.2.b.2",
    "title": "Multilimb Coordination",
    "category": "Abilities"
  },
  {
    "idx": 26,
    "elementId": "1.A.2.b.3",
    "title": "Response Orientation",
    "category": "Abilities"
  },
  {
    "idx": 27,
    "elementId": "1.A.2.b.4",
    "title": "Rate Control",
    "category": "Abilities"
  },
  {
    "idx": 28,
    "elementId": "1.A.2.c.1",
    "title": "Reaction Time",
    "category": "Abilities"
  },
  {
    "idx": 29,
    "elementId": "1.A.2.c.2",
    "title": "Wrist-Finger Speed",
    "category": "Abilities"
  },
  {
    "idx": 30,
    "elementId": "1.A.2.c.3",
    "title": "Speed of Limb Movement",
    "category": "Abilities"
  },
  {
    "idx": 31,
    "elementId": "1.A.3.a.1",
    "title": "Static Strength",
    "category": "Abilities"
  },
  {
    "idx": 32,
    "elementId": "1.A.3.a.2",
    "title": "Explosive Strength",
    "category": "Abilities"
  },
  {
    "idx": 33,
    "elementId": "1.A.3.a.3",
    "title": "Dynamic Strength",
    "category": "Abilities"
  },
  {
    "idx": 34,
    "elementId": "1.A.3.a.4",
    "title": "Trunk Strength",
    "category": "Abilities"
  },
  {
    "idx": 35,
    "elementId": "1.A.3.b.1",
    "title": "Stamina",
    "category": "Abilities"
  },
  {
    "idx": 36,
    "elementId": "1.A.3.c.1",
    "title": "Extent Flexibility",
    "category": "Abilities"
  },
  {
    "idx": 37,
    "elementId": "1.A.3.c.2",
    "title": "Dynamic Flexibility",
    "category": "Abilities"
  },
  {
    "idx": 38,
    "elementId": "1.A.3.c.3",
    "title": "Gross Body Coordination",
    "category": "Abilities"
  },
  {
    "idx": 39,
    "elementId": "1.A.3.c.4",
    "title": "Gross Body Equilibrium",
    "category": "Abilities"
  },
  {
    "idx": 40,
    "elementId": "1.A.4.a.1",
    "title": "Near Vision",
    "category": "Abilities"
  },
  {
    "idx": 41,
    "elementId": "1.A.4.a.2",
    "title": "Far Vision",
    "category": "Abilities"
  },
  {
    "idx": 42,
    "elementId": "1.A.4.a.3",
    "title": "Visual Color Discrimination",
    "category": "Abilities"
  },
  {
    "idx": 43,
    "elementId": "1.A.4.a.4",
    "title": "Night Vision",
    "category": "Abilities"
  },
  {
    "idx": 44,
    "elementId": "1.A.4.a.5",
    "title": "Peripheral Vision",
    "category": "Abilities"
  },
  {
    "idx": 45,
    "elementId": "1.A.4.a.6",
    "title": "Depth Perception",
    "category": "Abilities"
  },
  {
    "idx": 46,
    "elementId": "1.A.4.a.7",
    "title": "Glare Sensitivity",
    "category": "Abilities"
  },
  {
    "idx": 47,
    "elementId": "1.A.4.b.1",
    "title": "Hearing Sensitivity",
    "category": "Abilities"
  },
  {
    "idx": 48,
    "elementId": "1.A.4.b.2",
    "title": "Auditory Attention",
    "category": "Abilities"
  },
  {
    "idx": 49,
    "elementId": "1.A.4.b.3",
    "title": "Sound Localization",
    "category": "Abilities"
  },
  {
    "idx": 50,
    "elementId": "1.A.4.b.4",
    "title": "Speech Recognition",
    "category": "Abilities"
  },
  {
    "idx": 51,
    "elementId": "1.A.4.b.5",
    "title": "Speech Clarity",
    "category": "Abilities"
  },
  {
    "idx": 52,
    "elementId": "2.C.1.a",
    "title": "Administration and Management",
    "category": "Knowledge"
  },
  {
    "idx": 53,
    "elementId": "2.C.1.b",
    "title": "Administrative",
    "category": "Knowledge"
  },
  {
    "idx": 54,
    "elementId": "2.C.1.c",
    "title": "Economics and Accounting",
    "category": "Knowledge"
  },
  {
    "idx": 55,
    "elementId": "2.C.1.d",
    "title": "Sales and Marketing",
    "category": "Knowledge"
  },
  {
    "idx": 56,
    "elementId": "2.C.1.e",
    "title": "Customer and Personal Service",
    "category": "Knowledge"
  },
  {
    "idx": 57,
    "elementId": "2.C.1.f",
    "title": "Personnel and Human Resources",
    "category": "Knowledge"
  },
  {
    "idx": 58,
    "elementId": "2.C.10",
    "title": "Transportation",
    "category": "Knowledge"
  },
  {
    "idx": 59,
    "elementId": "2.C.2.a",
    "title": "Production and Processing",
    "category": "Knowledge"
  },
  {
    "idx": 60,
    "elementId": "2.C.2.b",
    "title": "Food Production",
    "category": "Knowledge"
  },
  {
    "idx": 61,
    "elementId": "2.C.3.a",
    "title": "Computers and Electronics",
    "category": "Knowledge"
  },
  {
    "idx": 62,
    "elementId": "2.C.3.b",
    "title": "Engineering and Technology",
    "category": "Knowledge"
  },
  {
    "idx": 63,
    "elementId": "2.C.3.c",
    "title": "Design",
    "category": "Knowledge"
  },
  {
    "idx": 64,
    "elementId": "2.C.3.d",
    "title": "Building and Construction",
    "category": "Knowledge"
  },
  {
    "idx": 65,
    "elementId": "2.C.3.e",
    "title": "Mechanical",
    "category": "Knowledge"
  },
  {
    "idx": 66,
    "elementId": "2.C.4.a",
    "title": "Mathematics",
    "category": "Knowledge"
  },
  {
    "idx": 67,
    "elementId": "2.C.4.b",
    "title": "Physics",
    "category": "Knowledge"
  },
  {
    "idx": 68,
    "elementId": "2.C.4.c",
    "title": "Chemistry",
    "category": "Knowledge"
  },
  {
    "idx": 69,
    "elementId": "2.C.4.d",
    "title": "Biology",
    "category": "Knowledge"
  },
  {
    "idx": 70,
    "elementId": "2.C.4.e",
    "title": "Psychology",
    "category": "Knowledge"
  },
  {
    "idx": 71,
    "elementId": "2.C.4.f",
    "title": "Sociology and Anthropology",
    "category": "Knowledge"
  },
  {
    "idx": 72,
    "elementId": "2.C.4.g",
    "title": "Geography",
    "category": "Knowledge"
  },
  {
    "idx": 73,
    "elementId": "2.C.5.a",
    "title": "Medicine and Dentistry",
    "category": "Knowledge"
  },
  {
    "idx": 74,
    "elementId": "2.C.5.b",
    "title": "Therapy and Counseling",
    "category": "Knowledge"
  },
  {
    "idx": 75,
    "elementId": "2.C.6",
    "title": "Education and Training",
    "category": "Knowledge"
  },
  {
    "idx": 76,
    "elementId": "2.C.7.a",
    "title": "English Language",
    "category": "Knowledge"
  },
  {
    "idx": 77,
    "elementId": "2.C.7.b",
    "title": "Foreign Language",
    "category": "Knowledge"
  },
  {
    "idx": 78,
    "elementId": "2.C.7.c",
    "title": "Fine Arts",
    "category": "Knowledge"
  },
  {
    "idx": 79,
    "elementId": "2.C.7.d",
    "title": "History and Archeology",
    "category": "Knowledge"
  },
  {
    "idx": 80,
    "elementId": "2.C.7.e",
    "title": "Philosophy and Theology",
    "category": "Knowledge"
  },
  {
    "idx": 81,
    "elementId": "2.C.8.a",
    "title": "Public Safety and Security",
    "category": "Knowledge"
  },
  {
    "idx": 82,
    "elementId": "2.C.8.b",
    "title": "Law and Government",
    "category": "Knowledge"
  },
  {
    "idx": 83,
    "elementId": "2.C.9.a",
    "title": "Telecommunications",
    "category": "Knowledge"
  },
  {
    "idx": 84,
    "elementId": "2.C.9.b",
    "title": "Communications and Media",
    "category": "Knowledge"
  },
  {
    "idx": 85,
    "elementId": "4.A.1.a.1",
    "title": "Getting Information",
    "category": "WorkActivities"
  },
  {
    "idx": 86,
    "elementId": "4.A.1.a.2",
    "title": "Monitoring Processes, Materials, or Surroundings",
    "category": "WorkActivities"
  },
  {
    "idx": 87,
    "elementId": "4.A.1.b.1",
    "title": "Identifying Objects, Actions, and Events",
    "category": "WorkActivities"
  },
  {
    "idx": 88,
    "elementId": "4.A.1.b.2",
    "title": "Inspecting Equipment, Structures, or Materials",
    "category": "WorkActivities"
  },
  {
    "idx": 89,
    "elementId": "4.A.1.b.3",
    "title": "Estimating the Quantifiable Characteristics of Products, Events, or Information",
    "category": "WorkActivities"
  },
  {
    "idx": 90,
    "elementId": "4.A.2.a.1",
    "title": "Judging the Qualities of Objects, Services, or People",
    "category": "WorkActivities"
  },
  {
    "idx": 91,
    "elementId": "4.A.2.a.2",
    "title": "Processing Information",
    "category": "WorkActivities"
  },
  {
    "idx": 92,
    "elementId": "4.A.2.a.3",
    "title": "Evaluating Information to Determine Compliance with Standards",
    "category": "WorkActivities"
  },
  {
    "idx": 93,
    "elementId": "4.A.2.a.4",
    "title": "Analyzing Data or Information",
    "category": "WorkActivities"
  },
  {
    "idx": 94,
    "elementId": "4.A.2.b.1",
    "title": "Making Decisions and Solving Problems",
    "category": "WorkActivities"
  },
  {
    "idx": 95,
    "elementId": "4.A.2.b.2",
    "title": "Thinking Creatively",
    "category": "WorkActivities"
  },
  {
    "idx": 96,
    "elementId": "4.A.2.b.3",
    "title": "Updating and Using Relevant Knowledge",
    "category": "WorkActivities"
  },
  {
    "idx": 97,
    "elementId": "4.A.2.b.4",
    "title": "Developing Objectives and Strategies",
    "category": "WorkActivities"
  },
  {
    "idx": 98,
    "elementId": "4.A.2.b.5",
    "title": "Scheduling Work and Activities",
    "category": "WorkActivities"
  },
  {
    "idx": 99,
    "elementId": "4.A.2.b.6",
    "title": "Organizing, Planning, and Prioritizing Work",
    "category": "WorkActivities"
  },
  {
    "idx": 100,
    "elementId": "4.A.3.a.1",
    "title": "Performing General Physical Activities",
    "category": "WorkActivities"
  },
  {
    "idx": 101,
    "elementId": "4.A.3.a.2",
    "title": "Handling and Moving Objects",
    "category": "WorkActivities"
  },
  {
    "idx": 102,
    "elementId": "4.A.3.a.3",
    "title": "Controlling Machines and Processes",
    "category": "WorkActivities"
  },
  {
    "idx": 103,
    "elementId": "4.A.3.a.4",
    "title": "Operating Vehicles, Mechanized Devices, or Equipment",
    "category": "WorkActivities"
  },
  {
    "idx": 104,
    "elementId": "4.A.3.b.1",
    "title": "Working with Computers",
    "category": "WorkActivities"
  },
  {
    "idx": 105,
    "elementId": "4.A.3.b.2",
    "title": "Drafting, Laying Out, and Specifying Technical Devices, Parts, and Equipment",
    "category": "WorkActivities"
  },
  {
    "idx": 106,
    "elementId": "4.A.3.b.4",
    "title": "Repairing and Maintaining Mechanical Equipment",
    "category": "WorkActivities"
  },
  {
    "idx": 107,
    "elementId": "4.A.3.b.5",
    "title": "Repairing and Maintaining Electronic Equipment",
    "category": "WorkActivities"
  },
  {
    "idx": 108,
    "elementId": "4.A.3.b.6",
    "title": "Documenting/Recording Information",
    "category": "WorkActivities"
  },
  {
    "idx": 109,
    "elementId": "4.A.4.a.1",
    "title": "Interpreting the Meaning of Information for Others",
    "category": "WorkActivities"
  },
  {
    "idx": 110,
    "elementId": "4.A.4.a.2",
    "title": "Communicating with Supervisors, Peers, or Subordinates",
    "category": "WorkActivities"
  },
  {
    "idx": 111,
    "elementId": "4.A.4.a.3",
    "title": "Communicating with People Outside the Organization",
    "category": "WorkActivities"
  },
  {
    "idx": 112,
    "elementId": "4.A.4.a.4",
    "title": "Establishing and Maintaining Interpersonal Relationships",
    "category": "WorkActivities"
  },
  {
    "idx": 113,
    "elementId": "4.A.4.a.5",
    "title": "Assisting and Caring for Others",
    "category": "WorkActivities"
  },
  {
    "idx": 114,
    "elementId": "4.A.4.a.6",
    "title": "Selling or Influencing Others",
    "category": "WorkActivities"
  },
  {
    "idx": 115,
    "elementId": "4.A.4.a.7",
    "title": "Resolving Conflicts and Negotiating with Others",
    "category": "WorkActivities"
  },
  {
    "idx": 116,
    "elementId": "4.A.4.a.8",
    "title": "Performing for or Working Directly with the Public",
    "category": "WorkActivities"
  },
  {
    "idx": 117,
    "elementId": "4.A.4.b.1",
    "title": "Coordinating the Work and Activities of Others",
    "category": "WorkActivities"
  },
  {
    "idx": 118,
    "elementId": "4.A.4.b.2",
    "title": "Developing and Building Teams",
    "category": "WorkActivities"
  },
  {
    "idx": 119,
    "elementId": "4.A.4.b.3",
    "title": "Training and Teaching Others",
    "category": "WorkActivities"
  },
  {
    "idx": 120,
    "elementId": "4.A.4.b.4",
    "title": "Guiding, Directing, and Motivating Subordinates",
    "category": "WorkActivities"
  },
  {
    "idx": 121,
    "elementId": "4.A.4.b.5",
    "title": "Coaching and Developing Others",
    "category": "WorkActivities"
  },
  {
    "idx": 122,
    "elementId": "4.A.4.b.6",
    "title": "Providing Consultation and Advice to Others",
    "category": "WorkActivities"
  },
  {
    "idx": 123,
    "elementId": "4.A.4.c.1",
    "title": "Performing Administrative Activities",
    "category": "WorkActivities"
  },
  {
    "idx": 124,
    "elementId": "4.A.4.c.2",
    "title": "Staffing Organizational Units",
    "category": "WorkActivities"
  },
  {
    "idx": 125,
    "elementId": "4.A.4.c.3",
    "title": "Monitoring and Controlling Resources",
    "category": "WorkActivities"
  },
  {
    "idx": 126,
    "elementId": "2.A.1.a",
    "title": "Reading Comprehension",
    "category": "EssentialSkills"
  },
  {
    "idx": 127,
    "elementId": "2.A.1.b",
    "title": "Active Listening",
    "category": "EssentialSkills"
  },
  {
    "idx": 128,
    "elementId": "2.A.1.c",
    "title": "Writing",
    "category": "EssentialSkills"
  },
  {
    "idx": 129,
    "elementId": "2.A.1.d",
    "title": "Speaking",
    "category": "EssentialSkills"
  },
  {
    "idx": 130,
    "elementId": "2.A.1.e",
    "title": "Mathematics",
    "category": "EssentialSkills"
  },
  {
    "idx": 131,
    "elementId": "2.A.1.f",
    "title": "Science",
    "category": "EssentialSkills"
  },
  {
    "idx": 132,
    "elementId": "2.A.2.a",
    "title": "Critical Thinking",
    "category": "EssentialSkills"
  },
  {
    "idx": 133,
    "elementId": "2.A.2.b",
    "title": "Active Learning",
    "category": "EssentialSkills"
  },
  {
    "idx": 134,
    "elementId": "2.A.2.c",
    "title": "Learning Strategies",
    "category": "EssentialSkills"
  },
  {
    "idx": 135,
    "elementId": "2.A.2.d",
    "title": "Monitoring",
    "category": "EssentialSkills"
  },
  {
    "idx": 136,
    "elementId": "2.B.1.a",
    "title": "Social Perceptiveness",
    "category": "TransferableSkills"
  },
  {
    "idx": 137,
    "elementId": "2.B.1.b",
    "title": "Coordination",
    "category": "TransferableSkills"
  },
  {
    "idx": 138,
    "elementId": "2.B.1.c",
    "title": "Persuasion",
    "category": "TransferableSkills"
  },
  {
    "idx": 139,
    "elementId": "2.B.1.d",
    "title": "Negotiation",
    "category": "TransferableSkills"
  },
  {
    "idx": 140,
    "elementId": "2.B.1.e",
    "title": "Instructing",
    "category": "TransferableSkills"
  },
  {
    "idx": 141,
    "elementId": "2.B.1.f",
    "title": "Service Orientation",
    "category": "TransferableSkills"
  },
  {
    "idx": 142,
    "elementId": "2.B.2.i",
    "title": "Complex Problem Solving",
    "category": "TransferableSkills"
  },
  {
    "idx": 143,
    "elementId": "2.B.3.a",
    "title": "Operations Analysis",
    "category": "TransferableSkills"
  },
  {
    "idx": 144,
    "elementId": "2.B.3.b",
    "title": "Technology Design",
    "category": "TransferableSkills"
  },
  {
    "idx": 145,
    "elementId": "2.B.3.c",
    "title": "Equipment Selection",
    "category": "TransferableSkills"
  },
  {
    "idx": 146,
    "elementId": "2.B.3.d",
    "title": "Installation",
    "category": "TransferableSkills"
  },
  {
    "idx": 147,
    "elementId": "2.B.3.e",
    "title": "Programming",
    "category": "TransferableSkills"
  },
  {
    "idx": 148,
    "elementId": "2.B.3.g",
    "title": "Operations Monitoring",
    "category": "TransferableSkills"
  },
  {
    "idx": 149,
    "elementId": "2.B.3.h",
    "title": "Operation and Control",
    "category": "TransferableSkills"
  },
  {
    "idx": 150,
    "elementId": "2.B.3.j",
    "title": "Equipment Maintenance",
    "category": "TransferableSkills"
  },
  {
    "idx": 151,
    "elementId": "2.B.3.k",
    "title": "Troubleshooting",
    "category": "TransferableSkills"
  },
  {
    "idx": 152,
    "elementId": "2.B.3.l",
    "title": "Repairing",
    "category": "TransferableSkills"
  },
  {
    "idx": 153,
    "elementId": "2.B.3.m",
    "title": "Quality Control Analysis",
    "category": "TransferableSkills"
  },
  {
    "idx": 154,
    "elementId": "2.B.4.e",
    "title": "Judgment and Decision Making",
    "category": "TransferableSkills"
  },
  {
    "idx": 155,
    "elementId": "2.B.4.g",
    "title": "Systems Analysis",
    "category": "TransferableSkills"
  },
  {
    "idx": 156,
    "elementId": "2.B.4.h",
    "title": "Systems Evaluation",
    "category": "TransferableSkills"
  },
  {
    "idx": 157,
    "elementId": "2.B.5.a",
    "title": "Time Management",
    "category": "TransferableSkills"
  },
  {
    "idx": 158,
    "elementId": "2.B.5.b",
    "title": "Management of Financial Resources",
    "category": "TransferableSkills"
  },
  {
    "idx": 159,
    "elementId": "2.B.5.c",
    "title": "Management of Material Resources",
    "category": "TransferableSkills"
  },
  {
    "idx": 160,
    "elementId": "2.B.5.d",
    "title": "Management of Personnel Resources",
    "category": "TransferableSkills"
  },
  {
    "idx": 161,
    "elementId": "4.C.1.a.2.c",
    "title": "Public Speaking",
    "category": "WorkContext"
  },
  {
    "idx": 162,
    "elementId": "4.C.1.a.2.f",
    "title": "Telephone Conversations",
    "category": "WorkContext"
  },
  {
    "idx": 163,
    "elementId": "4.C.1.a.2.h",
    "title": "E-Mail",
    "category": "WorkContext"
  },
  {
    "idx": 164,
    "elementId": "4.C.1.a.2.j",
    "title": "Written Letters and Memos",
    "category": "WorkContext"
  },
  {
    "idx": 165,
    "elementId": "4.C.1.a.2.l",
    "title": "Face-to-Face Discussions with Individuals and Within Teams",
    "category": "WorkContext"
  },
  {
    "idx": 166,
    "elementId": "4.C.1.a.4",
    "title": "Contact With Others",
    "category": "WorkContext"
  },
  {
    "idx": 167,
    "elementId": "4.C.1.b.1.e",
    "title": "Work With or Contribute to a Work Group or Team",
    "category": "WorkContext"
  },
  {
    "idx": 168,
    "elementId": "4.C.1.b.1.f",
    "title": "Deal With External Customers or the Public in General",
    "category": "WorkContext"
  },
  {
    "idx": 169,
    "elementId": "4.C.1.b.1.g",
    "title": "Coordinate or Lead Others in Accomplishing Work Activities",
    "category": "WorkContext"
  },
  {
    "idx": 170,
    "elementId": "4.C.1.c.1",
    "title": "Health and Safety of Other Workers",
    "category": "WorkContext"
  },
  {
    "idx": 171,
    "elementId": "4.C.1.c.2",
    "title": "Work Outcomes and Results of Other Workers",
    "category": "WorkContext"
  },
  {
    "idx": 172,
    "elementId": "4.C.1.d.1",
    "title": "Conflict Situations",
    "category": "WorkContext"
  },
  {
    "idx": 173,
    "elementId": "4.C.1.d.2",
    "title": "Dealing With Unpleasant, Angry, or Discourteous People",
    "category": "WorkContext"
  },
  {
    "idx": 174,
    "elementId": "4.C.1.d.3",
    "title": "Dealing with Violent or Physically Aggressive People",
    "category": "WorkContext"
  },
  {
    "idx": 175,
    "elementId": "4.C.2.a.1.a",
    "title": "Indoors, Environmentally Controlled",
    "category": "WorkContext"
  },
  {
    "idx": 176,
    "elementId": "4.C.2.a.1.b",
    "title": "Indoors, Not Environmentally Controlled",
    "category": "WorkContext"
  },
  {
    "idx": 177,
    "elementId": "4.C.2.a.1.c",
    "title": "Outdoors, Exposed to All Weather Conditions",
    "category": "WorkContext"
  },
  {
    "idx": 178,
    "elementId": "4.C.2.a.1.d",
    "title": "Outdoors, Under Cover",
    "category": "WorkContext"
  },
  {
    "idx": 179,
    "elementId": "4.C.2.a.1.e",
    "title": "In an Open Vehicle or Operating Equipment",
    "category": "WorkContext"
  },
  {
    "idx": 180,
    "elementId": "4.C.2.a.1.f",
    "title": "In an Enclosed Vehicle or Operate Enclosed Equipment",
    "category": "WorkContext"
  },
  {
    "idx": 181,
    "elementId": "4.C.2.a.3",
    "title": "Physical Proximity",
    "category": "WorkContext"
  },
  {
    "idx": 182,
    "elementId": "4.C.2.b.1.a",
    "title": "Exposed to Sounds, Noise Levels that are Distracting or Uncomfortable",
    "category": "WorkContext"
  },
  {
    "idx": 183,
    "elementId": "4.C.2.b.1.b",
    "title": "Exposed to Very Hot or Cold Temperatures",
    "category": "WorkContext"
  },
  {
    "idx": 184,
    "elementId": "4.C.2.b.1.c",
    "title": "Exposed to Extremely Bright or Inadequate Lighting Conditions",
    "category": "WorkContext"
  },
  {
    "idx": 185,
    "elementId": "4.C.2.b.1.d",
    "title": "Exposed to Contaminants",
    "category": "WorkContext"
  },
  {
    "idx": 186,
    "elementId": "4.C.2.b.1.e",
    "title": "Exposed to Cramped Work Space, Awkward Positions",
    "category": "WorkContext"
  },
  {
    "idx": 187,
    "elementId": "4.C.2.b.1.f",
    "title": "Exposed to Whole Body Vibration",
    "category": "WorkContext"
  },
  {
    "idx": 188,
    "elementId": "4.C.2.c.1.a",
    "title": "Exposed to Radiation",
    "category": "WorkContext"
  },
  {
    "idx": 189,
    "elementId": "4.C.2.c.1.b",
    "title": "Exposed to Disease or Infections",
    "category": "WorkContext"
  },
  {
    "idx": 190,
    "elementId": "4.C.2.c.1.c",
    "title": "Exposed to High Places",
    "category": "WorkContext"
  },
  {
    "idx": 191,
    "elementId": "4.C.2.c.1.d",
    "title": "Exposed to Hazardous Conditions",
    "category": "WorkContext"
  },
  {
    "idx": 192,
    "elementId": "4.C.2.c.1.e",
    "title": "Exposed to Hazardous Equipment",
    "category": "WorkContext"
  },
  {
    "idx": 193,
    "elementId": "4.C.2.c.1.f",
    "title": "Exposed to Minor Burns, Cuts, Bites, or Stings",
    "category": "WorkContext"
  },
  {
    "idx": 194,
    "elementId": "4.C.2.d.1.a",
    "title": "Spend Time Sitting",
    "category": "WorkContext"
  },
  {
    "idx": 195,
    "elementId": "4.C.2.d.1.b",
    "title": "Spend Time Standing",
    "category": "WorkContext"
  },
  {
    "idx": 196,
    "elementId": "4.C.2.d.1.c",
    "title": "Spend Time Climbing Ladders, Scaffolds, or Poles",
    "category": "WorkContext"
  },
  {
    "idx": 197,
    "elementId": "4.C.2.d.1.d",
    "title": "Spend Time Walking or Running",
    "category": "WorkContext"
  },
  {
    "idx": 198,
    "elementId": "4.C.2.d.1.e",
    "title": "Spend Time Kneeling, Crouching, Stooping, or Crawling",
    "category": "WorkContext"
  },
  {
    "idx": 199,
    "elementId": "4.C.2.d.1.f",
    "title": "Spend Time Keeping or Regaining Balance",
    "category": "WorkContext"
  },
  {
    "idx": 200,
    "elementId": "4.C.2.d.1.g",
    "title": "Spend Time Using Your Hands to Handle, Control, or Feel Objects, Tools, or Controls",
    "category": "WorkContext"
  },
  {
    "idx": 201,
    "elementId": "4.C.2.d.1.h",
    "title": "Spend Time Bending or Twisting Your Body",
    "category": "WorkContext"
  },
  {
    "idx": 202,
    "elementId": "4.C.2.d.1.i",
    "title": "Spend Time Making Repetitive Motions",
    "category": "WorkContext"
  },
  {
    "idx": 203,
    "elementId": "4.C.2.e.1.d",
    "title": "Wear Common Protective or Safety Equipment such as Safety Shoes, Glasses, Gloves, Hearing Protection, Hard Hats, or Life Jackets",
    "category": "WorkContext"
  },
  {
    "idx": 204,
    "elementId": "4.C.2.e.1.e",
    "title": "Wear Specialized Protective or Safety Equipment such as Breathing Apparatus, Safety Harness, Full Protection Suits, or Radiation Protection",
    "category": "WorkContext"
  },
  {
    "idx": 205,
    "elementId": "4.C.3.a.1",
    "title": "Consequence of Error",
    "category": "WorkContext"
  },
  {
    "idx": 206,
    "elementId": "4.C.3.a.2.a",
    "title": "Impact of Decisions on Co-workers or Company Results",
    "category": "WorkContext"
  },
  {
    "idx": 207,
    "elementId": "4.C.3.a.2.b",
    "title": "Frequency of Decision Making",
    "category": "WorkContext"
  },
  {
    "idx": 208,
    "elementId": "4.C.3.a.4",
    "title": "Freedom to Make Decisions",
    "category": "WorkContext"
  },
  {
    "idx": 209,
    "elementId": "4.C.3.b.2",
    "title": "Degree of Automation",
    "category": "WorkContext"
  },
  {
    "idx": 210,
    "elementId": "4.C.3.b.4",
    "title": "Importance of Being Exact or Accurate",
    "category": "WorkContext"
  },
  {
    "idx": 211,
    "elementId": "4.C.3.b.7",
    "title": "Importance of Repeating Same Tasks",
    "category": "WorkContext"
  },
  {
    "idx": 212,
    "elementId": "4.C.3.b.8",
    "title": "Determine Tasks, Priorities and Goals",
    "category": "WorkContext"
  },
  {
    "idx": 213,
    "elementId": "4.C.3.c.1",
    "title": "Level of Competition",
    "category": "WorkContext"
  },
  {
    "idx": 214,
    "elementId": "4.C.3.d.1",
    "title": "Time Pressure",
    "category": "WorkContext"
  },
  {
    "idx": 215,
    "elementId": "4.C.3.d.3",
    "title": "Pace Determined by Speed of Equipment",
    "category": "WorkContext"
  },
  {
    "idx": 216,
    "elementId": "1.D.1.a",
    "title": "Innovation",
    "category": "WorkStyles"
  },
  {
    "idx": 217,
    "elementId": "1.D.1.b",
    "title": "Achievement Orientation",
    "category": "WorkStyles"
  },
  {
    "idx": 218,
    "elementId": "1.D.1.c",
    "title": "Intellectual Curiosity",
    "category": "WorkStyles"
  },
  {
    "idx": 219,
    "elementId": "1.D.1.d",
    "title": "Tolerance for Ambiguity",
    "category": "WorkStyles"
  },
  {
    "idx": 220,
    "elementId": "1.D.1.e",
    "title": "Initiative",
    "category": "WorkStyles"
  },
  {
    "idx": 221,
    "elementId": "1.D.1.f",
    "title": "Adaptability",
    "category": "WorkStyles"
  },
  {
    "idx": 222,
    "elementId": "1.D.1.g",
    "title": "Self-Confidence",
    "category": "WorkStyles"
  },
  {
    "idx": 223,
    "elementId": "1.D.1.h",
    "title": "Perseverance",
    "category": "WorkStyles"
  },
  {
    "idx": 224,
    "elementId": "1.D.1.i",
    "title": "Leadership Orientation",
    "category": "WorkStyles"
  },
  {
    "idx": 225,
    "elementId": "1.D.2.a",
    "title": "Humility",
    "category": "WorkStyles"
  },
  {
    "idx": 226,
    "elementId": "1.D.2.b",
    "title": "Sincerity",
    "category": "WorkStyles"
  },
  {
    "idx": 227,
    "elementId": "1.D.2.c",
    "title": "Empathy",
    "category": "WorkStyles"
  },
  {
    "idx": 228,
    "elementId": "1.D.2.d",
    "title": "Cooperation",
    "category": "WorkStyles"
  },
  {
    "idx": 229,
    "elementId": "1.D.2.e",
    "title": "Optimism",
    "category": "WorkStyles"
  },
  {
    "idx": 230,
    "elementId": "1.D.2.f",
    "title": "Social Orientation",
    "category": "WorkStyles"
  },
  {
    "idx": 231,
    "elementId": "1.D.3.a",
    "title": "Cautiousness",
    "category": "WorkStyles"
  },
  {
    "idx": 232,
    "elementId": "1.D.3.b",
    "title": "Attention to Detail",
    "category": "WorkStyles"
  },
  {
    "idx": 233,
    "elementId": "1.D.3.c",
    "title": "Dependability",
    "category": "WorkStyles"
  },
  {
    "idx": 234,
    "elementId": "1.D.3.d",
    "title": "Integrity",
    "category": "WorkStyles"
  },
  {
    "idx": 235,
    "elementId": "1.D.4.a",
    "title": "Stress Tolerance",
    "category": "WorkStyles"
  },
  {
    "idx": 236,
    "elementId": "1.D.4.b",
    "title": "Self-Control",
    "category": "WorkStyles"
  },
  {
    "idx": 237,
    "elementId": "1.B.2.a",
    "title": "Achievement",
    "category": "WorkValues"
  },
  {
    "idx": 238,
    "elementId": "1.B.2.b",
    "title": "Working Conditions",
    "category": "WorkValues"
  },
  {
    "idx": 239,
    "elementId": "1.B.2.c",
    "title": "Recognition",
    "category": "WorkValues"
  },
  {
    "idx": 240,
    "elementId": "1.B.2.d",
    "title": "Relationships",
    "category": "WorkValues"
  },
  {
    "idx": 241,
    "elementId": "1.B.2.e",
    "title": "Support",
    "category": "WorkValues"
  },
  {
    "idx": 242,
    "elementId": "1.B.2.f",
    "title": "Independence",
    "category": "WorkValues"
  },
  {
    "idx": 243,
    "elementId": "1.B.1.a",
    "title": "Realistic",
    "category": "RIASEC"
  },
  {
    "idx": 244,
    "elementId": "1.B.1.b",
    "title": "Investigative",
    "category": "RIASEC"
  },
  {
    "idx": 245,
    "elementId": "1.B.1.c",
    "title": "Artistic",
    "category": "RIASEC"
  },
  {
    "idx": 246,
    "elementId": "1.B.1.d",
    "title": "Social",
    "category": "RIASEC"
  },
  {
    "idx": 247,
    "elementId": "1.B.1.e",
    "title": "Enterprising",
    "category": "RIASEC"
  },
  {
    "idx": 248,
    "elementId": "1.B.1.f",
    "title": "Conventional",
    "category": "RIASEC"
  },
  {
    "idx": 249,
    "elementId": "JZ.1",
    "title": "Job Zone",
    "category": "JobZone"
  }
] as const;

export const DESCRIPTOR_COUNT = 250;

/** Normalization metadata for reference and DB validation. */
export const NORMALIZATION_META = {
  "version": "O*NET 30.3",
  "dualScale": {
    "formula": "100 × max(0,(Im-1)/4) × max(0,Lv/7)",
    "categories": [
      "Abilities",
      "Knowledge",
      "WorkActivities",
      "EssentialSkills",
      "TransferableSkills"
    ]
  },
  "singleScale": {
    "formula": "((x-min)/(max-min))×100",
    "ranges": {
      "WorkContext": {
        "min": 1,
        "max": 5
      },
      "WorkStyles": {
        "min": 1,
        "max": 5
      },
      "WorkValues": {
        "min": 1,
        "max": 7
      },
      "RIASEC": {
        "min": 1,
        "max": 7
      },
      "JobZone": {
        "min": 1,
        "max": 5
      }
    }
  }
} as const;
