// AUTO-GENERATED by docs/seeds/onet/build-onet-seed.mjs — do not edit manually.
// Source: ACGME Milestone 2.0 program JSON files (229 files, 135 canonical).
// Attribution: O*NET 30.3 Database, U.S. DOL/ETA — CC-BY 4.0.
// https://www.onetcenter.org/license_db.html

/**
 * Normalized ACGME competency-emphasis vectors for all canonical ACGME programs.
 * emphasis[key] = share of subcompetencies in that ACGME competency domain (sums to 1.0).
 * Skills 6 (Collaboration) and 7 (PPD) have no ACGME milestone → not included in emphasis.
 * λ = 1 (milestone modulation weight — see build-onet-seed.mjs §10B).
 */

export type AcgmeEmphasis = {
  slug: string;
  parent_slug: string | null;
  program_type: "primary" | "subspecialty";
  emphasis: {
    pc: number; mk: number; pbli: number; ics: number; prof: number; sbp: number;
  };
  subcompetency_count: number;
};

export const MILESTONE_EMPHASIS: readonly AcgmeEmphasis[] = [
  {
    "slug": "addiction-medicine",
    "parent_slug": "preventive-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.125,
      "mk": 0.1875,
      "pbli": 0.125,
      "ics": 0.1875,
      "prof": 0.1875,
      "sbp": 0.1875
    },
    "subcompetency_count": 16
  },
  {
    "slug": "addiction-psychiatry",
    "parent_slug": "psychiatry",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.17647058823529413,
      "mk": 0.17647058823529413,
      "pbli": 0.11764705882352941,
      "ics": 0.17647058823529413,
      "prof": 0.17647058823529413,
      "sbp": 0.17647058823529413
    },
    "subcompetency_count": 17
  },
  {
    "slug": "adult-cardiothoracic-anesthesiology",
    "parent_slug": "anesthesiology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.30434782608695654,
      "mk": 0.21739130434782608,
      "pbli": 0.08695652173913043,
      "ics": 0.13043478260869565,
      "prof": 0.13043478260869565,
      "sbp": 0.13043478260869565
    },
    "subcompetency_count": 23
  },
  {
    "slug": "advanced-heart-failure-and-transplant-cardiology",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.23809523809523808,
      "mk": 0.23809523809523808,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.14285714285714285,
      "sbp": 0.14285714285714285
    },
    "subcompetency_count": 21
  },
  {
    "slug": "aerospace-medicine",
    "parent_slug": "preventive-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3,
      "mk": 0.1,
      "pbli": 0.1,
      "ics": 0.15,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "allergy-and-immunology",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.21052631578947367,
      "mk": 0.15789473684210525,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.21052631578947367
    },
    "subcompetency_count": 19
  },
  {
    "slug": "anesthesiology",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.43478260869565216,
      "mk": 0.08695652173913043,
      "pbli": 0.08695652173913043,
      "ics": 0.13043478260869565,
      "prof": 0.13043478260869565,
      "sbp": 0.13043478260869565
    },
    "subcompetency_count": 23
  },
  {
    "slug": "anesthesiology--hospice-and-palliative-medicine",
    "parent_slug": "anesthesiology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "cardiovascular-disease",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.23529411764705882,
      "mk": 0.11764705882352941,
      "pbli": 0.11764705882352941,
      "ics": 0.17647058823529413,
      "prof": 0.17647058823529413,
      "sbp": 0.17647058823529413
    },
    "subcompetency_count": 17
  },
  {
    "slug": "chemical-pathology",
    "parent_slug": "pathology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.21052631578947367,
      "mk": 0.10526315789473684,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.2631578947368421
    },
    "subcompetency_count": 19
  },
  {
    "slug": "child-abuse-pediatrics",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2222222222222222,
      "mk": 0.07407407407407407,
      "pbli": 0.1111111111111111,
      "ics": 0.2222222222222222,
      "prof": 0.14814814814814814,
      "sbp": 0.2222222222222222
    },
    "subcompetency_count": 27
  },
  {
    "slug": "child-and-adolescent-psychiatry",
    "parent_slug": "psychiatry",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.30434782608695654,
      "mk": 0.21739130434782608,
      "pbli": 0.08695652173913043,
      "ics": 0.13043478260869565,
      "prof": 0.13043478260869565,
      "sbp": 0.13043478260869565
    },
    "subcompetency_count": 23
  },
  {
    "slug": "child-neurology",
    "parent_slug": "neurology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.38461538461538464,
      "mk": 0.15384615384615385,
      "pbli": 0.07692307692307693,
      "ics": 0.15384615384615385,
      "prof": 0.11538461538461539,
      "sbp": 0.11538461538461539
    },
    "subcompetency_count": 26
  },
  {
    "slug": "clinical-cardiac-electrophysiology",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.375,
      "mk": 0.16666666666666666,
      "pbli": 0.08333333333333333,
      "ics": 0.125,
      "prof": 0.125,
      "sbp": 0.125
    },
    "subcompetency_count": 24
  },
  {
    "slug": "clinical-informatics",
    "parent_slug": "preventive-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.09523809523809523,
      "mk": 0.09523809523809523,
      "pbli": 0.23809523809523808,
      "ics": 0.19047619047619047,
      "prof": 0.23809523809523808,
      "sbp": 0.14285714285714285
    },
    "subcompetency_count": 21
  },
  {
    "slug": "clinical-neurophysiology",
    "parent_slug": "neurology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.32142857142857145,
      "mk": 0.17857142857142858,
      "pbli": 0.07142857142857142,
      "ics": 0.17857142857142858,
      "prof": 0.10714285714285714,
      "sbp": 0.14285714285714285
    },
    "subcompetency_count": 28
  },
  {
    "slug": "colon-and-rectal-surgery",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.48148148148148145,
      "mk": 0.07407407407407407,
      "pbli": 0.07407407407407407,
      "ics": 0.1111111111111111,
      "prof": 0.14814814814814814,
      "sbp": 0.1111111111111111
    },
    "subcompetency_count": 27
  },
  {
    "slug": "congenital-cardiac-surgery",
    "parent_slug": "thoracic-surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.17647058823529413,
      "mk": 0.11764705882352941,
      "pbli": 0.11764705882352941,
      "ics": 0.17647058823529413,
      "prof": 0.23529411764705882,
      "sbp": 0.17647058823529413
    },
    "subcompetency_count": 17
  },
  {
    "slug": "craniofacial-surgery",
    "parent_slug": "plastic-surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2222222222222222,
      "mk": 0.2222222222222222,
      "pbli": 0.1111111111111111,
      "ics": 0.1111111111111111,
      "prof": 0.16666666666666666,
      "sbp": 0.16666666666666666
    },
    "subcompetency_count": 18
  },
  {
    "slug": "critical-care-anesthesiology",
    "parent_slug": "anesthesiology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2631578947368421,
      "mk": 0.10526315789473684,
      "pbli": 0.10526315789473684,
      "ics": 0.21052631578947367,
      "prof": 0.15789473684210525,
      "sbp": 0.15789473684210525
    },
    "subcompetency_count": 19
  },
  {
    "slug": "cytopathology",
    "parent_slug": "pathology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2857142857142857,
      "mk": 0.09523809523809523,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.14285714285714285,
      "sbp": 0.23809523809523808
    },
    "subcompetency_count": 21
  },
  {
    "slug": "dermatology",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.38095238095238093,
      "mk": 0.09523809523809523,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.14285714285714285,
      "sbp": 0.14285714285714285
    },
    "subcompetency_count": 21
  },
  {
    "slug": "dermatopathology",
    "parent_slug": "pathology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.21052631578947367,
      "mk": 0.15789473684210525,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.21052631578947367
    },
    "subcompetency_count": 19
  },
  {
    "slug": "developmental-behavioral-pediatrics",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.20833333333333334,
      "mk": 0.16666666666666666,
      "pbli": 0.08333333333333333,
      "ics": 0.125,
      "prof": 0.16666666666666666,
      "sbp": 0.25
    },
    "subcompetency_count": 24
  },
  {
    "slug": "diagnostic-radiology",
    "parent_slug": "radiology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.16666666666666666,
      "mk": 0.16666666666666666,
      "pbli": 0.08333333333333333,
      "ics": 0.125,
      "prof": 0.125,
      "sbp": 0.3333333333333333
    },
    "subcompetency_count": 24
  },
  {
    "slug": "emergency-medical-services",
    "parent_slug": "emergency-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.21052631578947367,
      "mk": 0.10526315789473684,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.2631578947368421
    },
    "subcompetency_count": 19
  },
  {
    "slug": "emergency-medicine",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.36363636363636365,
      "mk": 0.09090909090909091,
      "pbli": 0.09090909090909091,
      "ics": 0.13636363636363635,
      "prof": 0.13636363636363635,
      "sbp": 0.18181818181818182
    },
    "subcompetency_count": 22
  },
  {
    "slug": "emergency-medicine--hospice-and-palliative-medicine",
    "parent_slug": "emergency-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "endocrinology-diabetes-and-metabolism",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3157894736842105,
      "mk": 0.10526315789473684,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.15789473684210525
    },
    "subcompetency_count": 19
  },
  {
    "slug": "family-medicine",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.2631578947368421,
      "mk": 0.10526315789473684,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.21052631578947367
    },
    "subcompetency_count": 19
  },
  {
    "slug": "family-medicine--geriatric-medicine",
    "parent_slug": "family-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2727272727272727,
      "mk": 0.09090909090909091,
      "pbli": 0.09090909090909091,
      "ics": 0.18181818181818182,
      "prof": 0.18181818181818182,
      "sbp": 0.18181818181818182
    },
    "subcompetency_count": 22
  },
  {
    "slug": "family-medicine--hospice-and-palliative-medicine",
    "parent_slug": "family-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "family-medicine--sleep-medicine",
    "parent_slug": "family-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2222222222222222,
      "mk": 0.1111111111111111,
      "pbli": 0.1111111111111111,
      "ics": 0.2222222222222222,
      "prof": 0.16666666666666666,
      "sbp": 0.16666666666666666
    },
    "subcompetency_count": 18
  },
  {
    "slug": "family-medicine--sports-medicine",
    "parent_slug": "family-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.15,
      "prof": 0.15,
      "sbp": 0.15
    },
    "subcompetency_count": 20
  },
  {
    "slug": "female-pelvic-medicine-and-reconstructive-surgery",
    "parent_slug": "urology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.25,
      "mk": 0.2857142857142857,
      "pbli": 0.10714285714285714,
      "ics": 0.14285714285714285,
      "prof": 0.10714285714285714,
      "sbp": 0.10714285714285714
    },
    "subcompetency_count": 28
  },
  {
    "slug": "forensic-pathology",
    "parent_slug": "pathology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.10526315789473684,
      "mk": 0.15789473684210525,
      "pbli": 0.10526315789473684,
      "ics": 0.21052631578947367,
      "prof": 0.15789473684210525,
      "sbp": 0.2631578947368421
    },
    "subcompetency_count": 19
  },
  {
    "slug": "forensic-psychiatry",
    "parent_slug": "psychiatry",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.17647058823529413,
      "mk": 0.11764705882352941,
      "pbli": 0.11764705882352941,
      "ics": 0.11764705882352941,
      "prof": 0.23529411764705882,
      "sbp": 0.23529411764705882
    },
    "subcompetency_count": 17
  },
  {
    "slug": "gastroenterology",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.23529411764705882,
      "mk": 0.11764705882352941,
      "pbli": 0.11764705882352941,
      "ics": 0.17647058823529413,
      "prof": 0.17647058823529413,
      "sbp": 0.17647058823529413
    },
    "subcompetency_count": 17
  },
  {
    "slug": "geriatric-psychiatry",
    "parent_slug": "psychiatry",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.25,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.15,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "gynecologic-oncology",
    "parent_slug": "obstetrics-and-gynecology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.18518518518518517,
      "mk": 0.2962962962962963,
      "pbli": 0.1111111111111111,
      "ics": 0.14814814814814814,
      "prof": 0.1111111111111111,
      "sbp": 0.14814814814814814
    },
    "subcompetency_count": 27
  },
  {
    "slug": "hematology",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.23809523809523808,
      "mk": 0.14285714285714285,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.14285714285714285,
      "sbp": 0.23809523809523808
    },
    "subcompetency_count": 21
  },
  {
    "slug": "hematology-and-medical-oncology",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.22727272727272727,
      "mk": 0.18181818181818182,
      "pbli": 0.09090909090909091,
      "ics": 0.13636363636363635,
      "prof": 0.13636363636363635,
      "sbp": 0.22727272727272727
    },
    "subcompetency_count": 22
  },
  {
    "slug": "hematopathology",
    "parent_slug": "pathology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.17391304347826086,
      "mk": 0.2608695652173913,
      "pbli": 0.08695652173913043,
      "ics": 0.13043478260869565,
      "prof": 0.13043478260869565,
      "sbp": 0.21739130434782608
    },
    "subcompetency_count": 23
  },
  {
    "slug": "infectious-disease",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.13043478260869565,
      "mk": 0.2608695652173913,
      "pbli": 0.08695652173913043,
      "ics": 0.13043478260869565,
      "prof": 0.17391304347826086,
      "sbp": 0.21739130434782608
    },
    "subcompetency_count": 23
  },
  {
    "slug": "internal-medicine",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.2857142857142857,
      "mk": 0.14285714285714285,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.19047619047619047,
      "sbp": 0.14285714285714285
    },
    "subcompetency_count": 21
  },
  {
    "slug": "internal-medicine--geriatric-medicine",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2727272727272727,
      "mk": 0.09090909090909091,
      "pbli": 0.09090909090909091,
      "ics": 0.18181818181818182,
      "prof": 0.18181818181818182,
      "sbp": 0.18181818181818182
    },
    "subcompetency_count": 22
  },
  {
    "slug": "internal-medicine--hospice-and-palliative-medicine",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "internal-medicine--sleep-medicine",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2222222222222222,
      "mk": 0.1111111111111111,
      "pbli": 0.1111111111111111,
      "ics": 0.2222222222222222,
      "prof": 0.16666666666666666,
      "sbp": 0.16666666666666666
    },
    "subcompetency_count": 18
  },
  {
    "slug": "internal-medicine--sports-medicine",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.15,
      "prof": 0.15,
      "sbp": 0.15
    },
    "subcompetency_count": 20
  },
  {
    "slug": "interventional-cardiology",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.17647058823529413,
      "mk": 0.17647058823529413,
      "pbli": 0.11764705882352941,
      "ics": 0.17647058823529413,
      "prof": 0.17647058823529413,
      "sbp": 0.17647058823529413
    },
    "subcompetency_count": 17
  },
  {
    "slug": "laboratory-genetics-and-genomics",
    "parent_slug": "medical-genetics-and-genomics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.21052631578947367,
      "mk": 0.10526315789473684,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.2631578947368421
    },
    "subcompetency_count": 19
  },
  {
    "slug": "medical-biochemical-genetics",
    "parent_slug": "medical-genetics-and-genomics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.1875,
      "mk": 0.125,
      "pbli": 0.125,
      "ics": 0.1875,
      "prof": 0.1875,
      "sbp": 0.1875
    },
    "subcompetency_count": 16
  },
  {
    "slug": "medical-genetics-and-genomics",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.17647058823529413,
      "mk": 0.17647058823529413,
      "pbli": 0.11764705882352941,
      "ics": 0.17647058823529413,
      "prof": 0.17647058823529413,
      "sbp": 0.17647058823529413
    },
    "subcompetency_count": 17
  },
  {
    "slug": "medical-microbiology",
    "parent_slug": "pathology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.14285714285714285,
      "mk": 0.19047619047619047,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.14285714285714285,
      "sbp": 0.2857142857142857
    },
    "subcompetency_count": 21
  },
  {
    "slug": "medical-oncology",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.23809523809523808,
      "mk": 0.14285714285714285,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.14285714285714285,
      "sbp": 0.23809523809523808
    },
    "subcompetency_count": 21
  },
  {
    "slug": "medical-toxicology",
    "parent_slug": "preventive-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.18181818181818182,
      "mk": 0.22727272727272727,
      "pbli": 0.09090909090909091,
      "ics": 0.13636363636363635,
      "prof": 0.13636363636363635,
      "sbp": 0.22727272727272727
    },
    "subcompetency_count": 22
  },
  {
    "slug": "micrographic-surgery-and-dermatologic-oncology",
    "parent_slug": "dermatology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2222222222222222,
      "mk": 0.1111111111111111,
      "pbli": 0.1111111111111111,
      "ics": 0.16666666666666666,
      "prof": 0.16666666666666666,
      "sbp": 0.2222222222222222
    },
    "subcompetency_count": 18
  },
  {
    "slug": "molecular-genetic-pathology",
    "parent_slug": "pathology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.13636363636363635,
      "mk": 0.18181818181818182,
      "pbli": 0.13636363636363635,
      "ics": 0.13636363636363635,
      "prof": 0.13636363636363635,
      "sbp": 0.2727272727272727
    },
    "subcompetency_count": 22
  },
  {
    "slug": "musculoskeletal-oncology",
    "parent_slug": "orthopaedic-surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.16666666666666666,
      "mk": 0.1111111111111111,
      "pbli": 0.16666666666666666,
      "ics": 0.2222222222222222,
      "prof": 0.16666666666666666,
      "sbp": 0.16666666666666666
    },
    "subcompetency_count": 18
  },
  {
    "slug": "neonatal-perinatal-medicine",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3076923076923077,
      "mk": 0.07692307692307693,
      "pbli": 0.07692307692307693,
      "ics": 0.15384615384615385,
      "prof": 0.15384615384615385,
      "sbp": 0.23076923076923078
    },
    "subcompetency_count": 26
  },
  {
    "slug": "nephrology",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3181818181818182,
      "mk": 0.13636363636363635,
      "pbli": 0.09090909090909091,
      "ics": 0.13636363636363635,
      "prof": 0.13636363636363635,
      "sbp": 0.18181818181818182
    },
    "subcompetency_count": 22
  },
  {
    "slug": "neurocritical-care",
    "parent_slug": "neurology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.25,
      "mk": 0.16666666666666666,
      "pbli": 0.08333333333333333,
      "ics": 0.20833333333333334,
      "prof": 0.125,
      "sbp": 0.16666666666666666
    },
    "subcompetency_count": 24
  },
  {
    "slug": "neurodevelopmental-disabilities",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3125,
      "mk": 0.15625,
      "pbli": 0.0625,
      "ics": 0.125,
      "prof": 0.15625,
      "sbp": 0.1875
    },
    "subcompetency_count": 32
  },
  {
    "slug": "neurological-surgery",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.4,
      "mk": 0.1,
      "pbli": 0.15,
      "ics": 0.1,
      "prof": 0.1,
      "sbp": 0.15
    },
    "subcompetency_count": 20
  },
  {
    "slug": "neurology",
    "parent_slug": "psychiatry",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.4444444444444444,
      "mk": 0.07407407407407407,
      "pbli": 0.07407407407407407,
      "ics": 0.14814814814814814,
      "prof": 0.1111111111111111,
      "sbp": 0.14814814814814814
    },
    "subcompetency_count": 27
  },
  {
    "slug": "neurology--hospice-and-palliative-medicine",
    "parent_slug": "neurology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "neurology--sleep-medicine",
    "parent_slug": "neurology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2222222222222222,
      "mk": 0.1111111111111111,
      "pbli": 0.1111111111111111,
      "ics": 0.2222222222222222,
      "prof": 0.16666666666666666,
      "sbp": 0.16666666666666666
    },
    "subcompetency_count": 18
  },
  {
    "slug": "neuropathology",
    "parent_slug": "pathology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.15,
      "prof": 0.15,
      "sbp": 0.25
    },
    "subcompetency_count": 20
  },
  {
    "slug": "neuroradiology",
    "parent_slug": "radiology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.19047619047619047,
      "mk": 0.09523809523809523,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.14285714285714285,
      "sbp": 0.3333333333333333
    },
    "subcompetency_count": 21
  },
  {
    "slug": "neurotology",
    "parent_slug": "otolaryngology---head-and-neck-surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2631578947368421,
      "mk": 0.15789473684210525,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.15789473684210525
    },
    "subcompetency_count": 19
  },
  {
    "slug": "nuclear-medicine",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.22727272727272727,
      "mk": 0.22727272727272727,
      "pbli": 0.09090909090909091,
      "ics": 0.13636363636363635,
      "prof": 0.13636363636363635,
      "sbp": 0.18181818181818182
    },
    "subcompetency_count": 22
  },
  {
    "slug": "nuclear-radiology",
    "parent_slug": "radiology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.15,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.15,
      "prof": 0.15,
      "sbp": 0.3
    },
    "subcompetency_count": 20
  },
  {
    "slug": "obstetric-anesthesiology",
    "parent_slug": "anesthesiology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.25,
      "mk": 0.1,
      "pbli": 0.15,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.15
    },
    "subcompetency_count": 20
  },
  {
    "slug": "obstetrics-and-gynecology",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.4375,
      "mk": 0.0625,
      "pbli": 0.0625,
      "ics": 0.125,
      "prof": 0.125,
      "sbp": 0.1875
    },
    "subcompetency_count": 32
  },
  {
    "slug": "obstetrics-and-gynecology--hospice-and-palliative-medicine",
    "parent_slug": "obstetrics-and-gynecology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "obstetrics-and-gynecology--maternal-fetal-medicine",
    "parent_slug": "obstetrics-and-gynecology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.19230769230769232,
      "mk": 0.15384615384615385,
      "pbli": 0.11538461538461539,
      "ics": 0.15384615384615385,
      "prof": 0.15384615384615385,
      "sbp": 0.23076923076923078
    },
    "subcompetency_count": 26
  },
  {
    "slug": "ophthalmic-plastic-and-reconstructive-surgery",
    "parent_slug": "ophthalmology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.23529411764705882,
      "mk": 0.11764705882352941,
      "pbli": 0.11764705882352941,
      "ics": 0.17647058823529413,
      "prof": 0.17647058823529413,
      "sbp": 0.17647058823529413
    },
    "subcompetency_count": 17
  },
  {
    "slug": "ophthalmology",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.3,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.15,
      "prof": 0.15,
      "sbp": 0.15
    },
    "subcompetency_count": 20
  },
  {
    "slug": "orthopaedic-surgery",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.35,
      "mk": 0.1,
      "pbli": 0.1,
      "ics": 0.15,
      "prof": 0.15,
      "sbp": 0.15
    },
    "subcompetency_count": 20
  },
  {
    "slug": "orthopaedic-surgery--orthopaedic-sports-medicine",
    "parent_slug": "orthopaedic-surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2777777777777778,
      "mk": 0.1111111111111111,
      "pbli": 0.1111111111111111,
      "ics": 0.16666666666666666,
      "prof": 0.16666666666666666,
      "sbp": 0.16666666666666666
    },
    "subcompetency_count": 18
  },
  {
    "slug": "orthopaedic-surgery-of-the-spine",
    "parent_slug": "orthopaedic-surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3157894736842105,
      "mk": 0.10526315789473684,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.15789473684210525
    },
    "subcompetency_count": 19
  },
  {
    "slug": "orthopaedic-trauma",
    "parent_slug": "orthopaedic-surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.23809523809523808,
      "mk": 0.23809523809523808,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.14285714285714285,
      "sbp": 0.14285714285714285
    },
    "subcompetency_count": 21
  },
  {
    "slug": "osteopathic-neuromusculoskeletal-medicine",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.2777777777777778,
      "mk": 0.1111111111111111,
      "pbli": 0.1111111111111111,
      "ics": 0.16666666666666666,
      "prof": 0.16666666666666666,
      "sbp": 0.16666666666666666
    },
    "subcompetency_count": 18
  },
  {
    "slug": "otolaryngology---head-and-neck-surgery",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.391304347826087,
      "mk": 0.13043478260869565,
      "pbli": 0.08695652173913043,
      "ics": 0.13043478260869565,
      "prof": 0.13043478260869565,
      "sbp": 0.13043478260869565
    },
    "subcompetency_count": 23
  },
  {
    "slug": "otolaryngology---head-and-neck-surgery--neurotology",
    "parent_slug": "otolaryngology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2631578947368421,
      "mk": 0.15789473684210525,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.15789473684210525
    },
    "subcompetency_count": 19
  },
  {
    "slug": "otolaryngology---head-and-neck-surgery--pediatric-otolaryngology",
    "parent_slug": "otolaryngology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3157894736842105,
      "mk": 0.10526315789473684,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.15789473684210525
    },
    "subcompetency_count": 19
  },
  {
    "slug": "pathology",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.2857142857142857,
      "mk": 0.09523809523809523,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.14285714285714285,
      "sbp": 0.23809523809523808
    },
    "subcompetency_count": 21
  },
  {
    "slug": "pathology--blood-banking-and-transfusion-medicine",
    "parent_slug": "pathology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.17391304347826086,
      "mk": 0.2608695652173913,
      "pbli": 0.08695652173913043,
      "ics": 0.13043478260869565,
      "prof": 0.13043478260869565,
      "sbp": 0.21739130434782608
    },
    "subcompetency_count": 23
  },
  {
    "slug": "pediatric-anesthesiology",
    "parent_slug": "anesthesiology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.35,
      "mk": 0.1,
      "pbli": 0.1,
      "ics": 0.15,
      "prof": 0.15,
      "sbp": 0.15
    },
    "subcompetency_count": 20
  },
  {
    "slug": "pediatric-cardiac-anesthesiology",
    "parent_slug": "anesthesiology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3333333333333333,
      "mk": 0.14285714285714285,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.14285714285714285,
      "sbp": 0.14285714285714285
    },
    "subcompetency_count": 21
  },
  {
    "slug": "pediatric-cardiology",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.17391304347826086,
      "mk": 0.13043478260869565,
      "pbli": 0.08695652173913043,
      "ics": 0.17391304347826086,
      "prof": 0.17391304347826086,
      "sbp": 0.2608695652173913
    },
    "subcompetency_count": 23
  },
  {
    "slug": "pediatric-critical-care",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.21739130434782608,
      "mk": 0.08695652173913043,
      "pbli": 0.08695652173913043,
      "ics": 0.17391304347826086,
      "prof": 0.17391304347826086,
      "sbp": 0.2608695652173913
    },
    "subcompetency_count": 23
  },
  {
    "slug": "pediatric-dermatology",
    "parent_slug": "dermatology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.23809523809523808,
      "mk": 0.09523809523809523,
      "pbli": 0.14285714285714285,
      "ics": 0.19047619047619047,
      "prof": 0.19047619047619047,
      "sbp": 0.14285714285714285
    },
    "subcompetency_count": 21
  },
  {
    "slug": "pediatric-endocrinology",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.20833333333333334,
      "mk": 0.125,
      "pbli": 0.08333333333333333,
      "ics": 0.16666666666666666,
      "prof": 0.16666666666666666,
      "sbp": 0.25
    },
    "subcompetency_count": 24
  },
  {
    "slug": "pediatric-gastroenterology",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2916666666666667,
      "mk": 0.08333333333333333,
      "pbli": 0.08333333333333333,
      "ics": 0.125,
      "prof": 0.16666666666666666,
      "sbp": 0.25
    },
    "subcompetency_count": 24
  },
  {
    "slug": "pediatric-hematology-oncology",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.16,
      "pbli": 0.08,
      "ics": 0.16,
      "prof": 0.16,
      "sbp": 0.24
    },
    "subcompetency_count": 25
  },
  {
    "slug": "pediatric-infectious-diseases",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.19230769230769232,
      "mk": 0.23076923076923078,
      "pbli": 0.07692307692307693,
      "ics": 0.11538461538461539,
      "prof": 0.15384615384615385,
      "sbp": 0.23076923076923078
    },
    "subcompetency_count": 26
  },
  {
    "slug": "pediatric-nephrology",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.34615384615384615,
      "mk": 0.07692307692307693,
      "pbli": 0.07692307692307693,
      "ics": 0.11538461538461539,
      "prof": 0.15384615384615385,
      "sbp": 0.23076923076923078
    },
    "subcompetency_count": 26
  },
  {
    "slug": "pediatric-orthopaedics",
    "parent_slug": "orthopaedic-surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2608695652173913,
      "mk": 0.2608695652173913,
      "pbli": 0.08695652173913043,
      "ics": 0.13043478260869565,
      "prof": 0.13043478260869565,
      "sbp": 0.13043478260869565
    },
    "subcompetency_count": 23
  },
  {
    "slug": "pediatric-otolaryngology",
    "parent_slug": "otolaryngology---head-and-neck-surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3157894736842105,
      "mk": 0.10526315789473684,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.15789473684210525
    },
    "subcompetency_count": 19
  },
  {
    "slug": "pediatric-pathology",
    "parent_slug": "pathology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.21052631578947367,
      "mk": 0.10526315789473684,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.2631578947368421
    },
    "subcompetency_count": 19
  },
  {
    "slug": "pediatric-pulmonology",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.19047619047619047,
      "mk": 0.09523809523809523,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.19047619047619047,
      "sbp": 0.2857142857142857
    },
    "subcompetency_count": 21
  },
  {
    "slug": "pediatric-radiology",
    "parent_slug": "radiology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.1,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.15,
      "prof": 0.15,
      "sbp": 0.35
    },
    "subcompetency_count": 20
  },
  {
    "slug": "pediatric-rehabilitation-medicine",
    "parent_slug": "physical-medicine-and-rehabilitation",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3333333333333333,
      "mk": 0.08333333333333333,
      "pbli": 0.08333333333333333,
      "ics": 0.125,
      "prof": 0.20833333333333334,
      "sbp": 0.16666666666666666
    },
    "subcompetency_count": 24
  },
  {
    "slug": "pediatric-rheumatology",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.28,
      "mk": 0.12,
      "pbli": 0.08,
      "ics": 0.12,
      "prof": 0.16,
      "sbp": 0.24
    },
    "subcompetency_count": 25
  },
  {
    "slug": "pediatric-surgery",
    "parent_slug": "surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.44,
      "mk": 0.12,
      "pbli": 0.08,
      "ics": 0.12,
      "prof": 0.12,
      "sbp": 0.12
    },
    "subcompetency_count": 25
  },
  {
    "slug": "pediatric-urology",
    "parent_slug": "urology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2857142857142857,
      "mk": 0.14285714285714285,
      "pbli": 0.09523809523809523,
      "ics": 0.19047619047619047,
      "prof": 0.14285714285714285,
      "sbp": 0.14285714285714285
    },
    "subcompetency_count": 21
  },
  {
    "slug": "pediatrics",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.22727272727272727,
      "mk": 0.09090909090909091,
      "pbli": 0.09090909090909091,
      "ics": 0.13636363636363635,
      "prof": 0.18181818181818182,
      "sbp": 0.2727272727272727
    },
    "subcompetency_count": 22
  },
  {
    "slug": "pediatrics--hospice-and-palliative-medicine",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "pediatrics--pediatric-hospital-medicine",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.14285714285714285,
      "mk": 0.09523809523809523,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.19047619047619047,
      "sbp": 0.3333333333333333
    },
    "subcompetency_count": 21
  },
  {
    "slug": "pediatrics--sleep-medicine",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2222222222222222,
      "mk": 0.1111111111111111,
      "pbli": 0.1111111111111111,
      "ics": 0.2222222222222222,
      "prof": 0.16666666666666666,
      "sbp": 0.16666666666666666
    },
    "subcompetency_count": 18
  },
  {
    "slug": "pediatrics--sports-medicine",
    "parent_slug": "pediatrics",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.15,
      "prof": 0.15,
      "sbp": 0.15
    },
    "subcompetency_count": 20
  },
  {
    "slug": "physical-medicine-and-rehabilitation--hospice-and-palliative-medicine",
    "parent_slug": "physical-medicine-and-rehabilitation",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "physical-medicine-and-rehabilitation--spinal-cord-injury-medicine",
    "parent_slug": "physical-medicine-and-rehabilitation",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.21739130434782608,
      "mk": 0.13043478260869565,
      "pbli": 0.08695652173913043,
      "ics": 0.17391304347826086,
      "prof": 0.21739130434782608,
      "sbp": 0.17391304347826086
    },
    "subcompetency_count": 23
  },
  {
    "slug": "plastic-surgery",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.3181818181818182,
      "mk": 0.22727272727272727,
      "pbli": 0.09090909090909091,
      "ics": 0.09090909090909091,
      "prof": 0.13636363636363635,
      "sbp": 0.13636363636363635
    },
    "subcompetency_count": 22
  },
  {
    "slug": "preventive-medicine--public-health-and-general-preventive-medicine",
    "parent_slug": "preventive-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.25,
      "pbli": 0.15,
      "ics": 0.1,
      "prof": 0.15,
      "sbp": 0.15
    },
    "subcompetency_count": 20
  },
  {
    "slug": "psychiatry",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.2857142857142857,
      "mk": 0.19047619047619047,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.14285714285714285,
      "sbp": 0.14285714285714285
    },
    "subcompetency_count": 21
  },
  {
    "slug": "psychiatry--hospice-and-palliative-medicine",
    "parent_slug": "psychiatry",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "psychiatry--sleep-medicine",
    "parent_slug": "psychiatry",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2222222222222222,
      "mk": 0.1111111111111111,
      "pbli": 0.1111111111111111,
      "ics": 0.2222222222222222,
      "prof": 0.16666666666666666,
      "sbp": 0.16666666666666666
    },
    "subcompetency_count": 18
  },
  {
    "slug": "pulmonary-disease",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.21052631578947367,
      "mk": 0.10526315789473684,
      "pbli": 0.10526315789473684,
      "ics": 0.21052631578947367,
      "prof": 0.15789473684210525,
      "sbp": 0.21052631578947367
    },
    "subcompetency_count": 19
  },
  {
    "slug": "pulmonary-disease-and-critical-care-medicine",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.25,
      "mk": 0.1,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "radiation-oncology",
    "parent_slug": "radiology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.38095238095238093,
      "mk": 0.09523809523809523,
      "pbli": 0.09523809523809523,
      "ics": 0.14285714285714285,
      "prof": 0.14285714285714285,
      "sbp": 0.14285714285714285
    },
    "subcompetency_count": 21
  },
  {
    "slug": "radiation-oncology--hospice-and-palliative-medicine",
    "parent_slug": "radiation-oncology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "radiology--hospice-and-palliative-medicine",
    "parent_slug": "radiology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "reproductive-endocrinology-and-infertility",
    "parent_slug": "obstetrics-and-gynecology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.13636363636363635,
      "mk": 0.22727272727272727,
      "pbli": 0.13636363636363635,
      "ics": 0.18181818181818182,
      "prof": 0.13636363636363635,
      "sbp": 0.18181818181818182
    },
    "subcompetency_count": 22
  },
  {
    "slug": "rheumatology",
    "parent_slug": "internal-medicine",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.3,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.15,
      "prof": 0.15,
      "sbp": 0.15
    },
    "subcompetency_count": 20
  },
  {
    "slug": "selective-pathology",
    "parent_slug": "pathology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.25,
      "mk": 0.1,
      "pbli": 0.1,
      "ics": 0.15,
      "prof": 0.15,
      "sbp": 0.25
    },
    "subcompetency_count": 20
  },
  {
    "slug": "surgery--hospice-and-palliative-medicine",
    "parent_slug": "surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.15,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.2
    },
    "subcompetency_count": 20
  },
  {
    "slug": "surgical-critical-care",
    "parent_slug": "surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.4,
      "mk": 0.12,
      "pbli": 0.08,
      "ics": 0.12,
      "prof": 0.12,
      "sbp": 0.16
    },
    "subcompetency_count": 25
  },
  {
    "slug": "thoracic-surgery-integrated",
    "parent_slug": "thoracic-surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.375,
      "mk": 0.125,
      "pbli": 0.08333333333333333,
      "ics": 0.125,
      "prof": 0.16666666666666666,
      "sbp": 0.125
    },
    "subcompetency_count": 24
  },
  {
    "slug": "transitional-year",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.3157894736842105,
      "mk": 0.10526315789473684,
      "pbli": 0.10526315789473684,
      "ics": 0.15789473684210525,
      "prof": 0.15789473684210525,
      "sbp": 0.15789473684210525
    },
    "subcompetency_count": 19
  },
  {
    "slug": "urogynecology-and-reconstructive-pelvic-surgery",
    "parent_slug": "obstetrics-and-gynecology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.25,
      "mk": 0.2857142857142857,
      "pbli": 0.10714285714285714,
      "ics": 0.14285714285714285,
      "prof": 0.10714285714285714,
      "sbp": 0.10714285714285714
    },
    "subcompetency_count": 28
  },
  {
    "slug": "urology",
    "parent_slug": null,
    "program_type": "primary",
    "emphasis": {
      "pc": 0.3,
      "mk": 0.1,
      "pbli": 0.1,
      "ics": 0.2,
      "prof": 0.15,
      "sbp": 0.15
    },
    "subcompetency_count": 20
  },
  {
    "slug": "vascular-neurology",
    "parent_slug": "neurology",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2,
      "mk": 0.28,
      "pbli": 0.08,
      "ics": 0.16,
      "prof": 0.12,
      "sbp": 0.16
    },
    "subcompetency_count": 25
  },
  {
    "slug": "vascular-surgery-independent",
    "parent_slug": "surgery",
    "program_type": "subspecialty",
    "emphasis": {
      "pc": 0.2857142857142857,
      "mk": 0.17857142857142858,
      "pbli": 0.07142857142857142,
      "ics": 0.10714285714285714,
      "prof": 0.14285714285714285,
      "sbp": 0.21428571428571427
    },
    "subcompetency_count": 28
  }
] as const;

/** O(1) lookup by canonical ACGME slug. */
export const MILESTONE_EMPHASIS_BY_SLUG: Readonly<Record<string, AcgmeEmphasis>> = Object.fromEntries(
  MILESTONE_EMPHASIS.map(e => [e.slug, e])
) as Readonly<Record<string, AcgmeEmphasis>>;
