// AUTO-GENERATED by docs/seeds/onet/build-onet-seed.mjs — do not edit manually.
// Source: O*NET 30.3 Database, U.S. DOL/ETA, May 2026. CC-BY 4.0.
// Subspecialty anchor data from FISCMAK_Subspecialty_Anchor_SOCs.csv (166 rows).
// https://www.onetcenter.org/license_db.html

/**
 * Stale O*NET 30.3 codes found in the CSV — flagged, not auto-corrected.
 * Computation uses ANCHOR_SOC_EFFECTIVE; the CSV code is preserved for audit.
 *
 * 19-3031.00 → 19-3033.00 (renamed: Clinical and Counseling Psychologists)
 * 13-1061.00 → 11-9161.00 (wrong SOC family; correct is Emergency Management Directors)
 * 29-2041.00 → avg(29-2042.00,29-2043.00) (split into EMTs + Paramedics)
 * 25-2054.00 → 25-2059.00 (restructured; use Special Education Teachers, All Other)
 * 29-2010.00 → 29-2011.00 (group code; use Medical and Clinical Lab Technologists)
 *
 * Anchor SOCs in the 29-1xxx family (29-1126, 29-1123, 29-1127, 29-1161, 29-1041, 29-1029)
 * are excluded from the adjacency candidate pool by design — not an error.
 */

export type SubspecialtyAnchor = {
  /** Parent physician SOC code (with .00). */
  parent_soc: string;
  /** CSV tier (2 = standard 0.20 alpha; 3 = strong anchor 0.40 alpha). */
  tier: number;
  /** Anchor SOC as written in FISCMAK_Subspecialty_Anchor_SOCs.csv. May be a stale O*NET 30.3 code. */
  anchor_soc_csv: string;
  /**
   * Resolved O*NET 30.3 code used for actual computation.
   * Equals anchor_soc_csv unless flagged. For the 29-2041 split: "avg(29-2042.00,29-2043.00)".
   */
  anchor_soc_effective: string;
  anchor_title: string;
  /** Blending weight: V_blend = (1-alpha)*V_parent + alpha*V_anchor. */
  alpha: number;
  /** Present when anchor_soc_csv is stale or incorrect in O*NET 30.3. */
  flagged?: string;
};

export const SUBSPECIALTY_ANCHORS: Readonly<Record<string, SubspecialtyAnchor>> = {
  "Electrophysiology": {
    "parent_soc": "29-1212.00",
    "tier": 2,
    "anchor_soc_csv": "17-2072.00",
    "anchor_soc_effective": "17-2072.00",
    "anchor_title": "Electronics Engineers",
    "alpha": 0.2
  },
  "Interventional Cardiology": {
    "parent_soc": "29-1212.00",
    "tier": 2,
    "anchor_soc_csv": "29-2031.00",
    "anchor_soc_effective": "29-2031.00",
    "anchor_title": "Cardiovascular Technologists",
    "alpha": 0.2
  },
  "Advanced Heart Failure/Transplant": {
    "parent_soc": "29-1212.00",
    "tier": 2,
    "anchor_soc_csv": "21-1022.00",
    "anchor_soc_effective": "21-1022.00",
    "anchor_title": "Healthcare Social Workers",
    "alpha": 0.2
  },
  "Adult Congenital Heart": {
    "parent_soc": "29-1212.00",
    "tier": 2,
    "anchor_soc_csv": "25-1042.00",
    "anchor_soc_effective": "25-1042.00",
    "anchor_title": "Biological Science Teachers, Postsec",
    "alpha": 0.2
  },
  "Gastroenterology": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "29-2034.00",
    "anchor_soc_effective": "29-2034.00",
    "anchor_title": "Radiologic Technologists",
    "alpha": 0.2
  },
  "Hepatology/Transplant": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "21-1022.00",
    "anchor_soc_effective": "21-1022.00",
    "anchor_title": "Healthcare Social Workers",
    "alpha": 0.2
  },
  "Pulmonary/Critical Care": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "29-1126.00",
    "anchor_soc_effective": "29-1126.00",
    "anchor_title": "Respiratory Therapists",
    "alpha": 0.2
  },
  "Interventional Pulmonology": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "29-2034.00",
    "anchor_soc_effective": "29-2034.00",
    "anchor_title": "Radiologic Technologists",
    "alpha": 0.2
  },
  "Hematology/Oncology": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Endocrinology": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Nephrology": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "17-2112.00",
    "anchor_soc_effective": "17-2112.00",
    "anchor_title": "Industrial Engineers",
    "alpha": 0.2
  },
  "Rheumatology": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Infectious Disease": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "19-1041.00",
    "anchor_soc_effective": "19-1041.00",
    "anchor_title": "Epidemiologists",
    "alpha": 0.2
  },
  "Geriatric Medicine (IM)": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "21-1015.00",
    "anchor_soc_effective": "21-1015.00",
    "anchor_title": "Rehabilitation Counselors",
    "alpha": 0.2
  },
  "Critical Care Medicine": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "29-1126.00",
    "anchor_soc_effective": "29-1126.00",
    "anchor_title": "Respiratory Therapists",
    "alpha": 0.2
  },
  "Allergy & Immunology": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Clinical Informatics (IM)": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "15-1252.00",
    "anchor_soc_effective": "15-1252.00",
    "anchor_title": "Software Developers",
    "alpha": 0.2
  },
  "Hospice & Palliative (IM)": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "21-1022.00",
    "anchor_soc_effective": "21-1022.00",
    "anchor_title": "Healthcare Social Workers",
    "alpha": 0.2
  },
  "Sleep Medicine (IM)": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "29-2099.00",
    "anchor_soc_effective": "29-2099.00",
    "anchor_title": "Health Technologists, All Other",
    "alpha": 0.2
  },
  "Hospital Medicine (Adult)": {
    "parent_soc": "29-1216.00",
    "tier": 2,
    "anchor_soc_csv": "11-9111.00",
    "anchor_soc_effective": "11-9111.00",
    "anchor_title": "Medical/Health Services Managers",
    "alpha": 0.2
  },
  "FM / Geriatric Medicine": {
    "parent_soc": "29-1215.00",
    "tier": 2,
    "anchor_soc_csv": "21-1015.00",
    "anchor_soc_effective": "21-1015.00",
    "anchor_title": "Rehabilitation Counselors",
    "alpha": 0.2
  },
  "FM / Sports Medicine": {
    "parent_soc": "29-1215.00",
    "tier": 2,
    "anchor_soc_csv": "29-9091.00",
    "anchor_soc_effective": "29-9091.00",
    "anchor_title": "Athletic Trainers",
    "alpha": 0.2
  },
  "FM / Hospice & Palliative": {
    "parent_soc": "29-1215.00",
    "tier": 2,
    "anchor_soc_csv": "21-1022.00",
    "anchor_soc_effective": "21-1022.00",
    "anchor_title": "Healthcare Social Workers",
    "alpha": 0.2
  },
  "FM / Addiction Medicine": {
    "parent_soc": "29-1215.00",
    "tier": 2,
    "anchor_soc_csv": "21-1011.00",
    "anchor_soc_effective": "21-1011.00",
    "anchor_title": "Substance Abuse Counselors",
    "alpha": 0.2
  },
  "FM / Adolescent Medicine": {
    "parent_soc": "29-1215.00",
    "tier": 2,
    "anchor_soc_csv": "21-1012.00",
    "anchor_soc_effective": "21-1012.00",
    "anchor_title": "Educational/Career Counselors",
    "alpha": 0.2
  },
  "Neonatology": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "29-1126.00",
    "anchor_soc_effective": "29-1126.00",
    "anchor_title": "Respiratory Therapists",
    "alpha": 0.2
  },
  "Peds Cardiology": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "29-2031.00",
    "anchor_soc_effective": "29-2031.00",
    "anchor_title": "Cardiovascular Technologists",
    "alpha": 0.2
  },
  "Peds Critical Care": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "29-1126.00",
    "anchor_soc_effective": "29-1126.00",
    "anchor_title": "Respiratory Therapists",
    "alpha": 0.2
  },
  "Peds Emergency Medicine": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "29-2041.00",
    "anchor_soc_effective": "avg(29-2042.00,29-2043.00)",
    "anchor_title": "EMTs/Paramedics",
    "alpha": 0.2,
    "flagged": "Split into 29-2042.00 (EMTs) + 29-2043.00 (Paramedics) in O*NET 30.3; use average"
  },
  "Peds GI": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "29-2034.00",
    "anchor_soc_effective": "29-2034.00",
    "anchor_title": "Radiologic Technologists",
    "alpha": 0.2
  },
  "Peds Heme/Onc": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Peds Endocrinology": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Peds Pulmonology": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "29-1126.00",
    "anchor_soc_effective": "29-1126.00",
    "anchor_title": "Respiratory Therapists",
    "alpha": 0.2
  },
  "Peds Nephrology": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "17-2112.00",
    "anchor_soc_effective": "17-2112.00",
    "anchor_title": "Industrial Engineers",
    "alpha": 0.2
  },
  "Peds Rheumatology": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Peds Infectious Disease": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "19-1041.00",
    "anchor_soc_effective": "19-1041.00",
    "anchor_title": "Epidemiologists",
    "alpha": 0.2
  },
  "Developmental-Behavioral Peds": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "19-3031.00",
    "anchor_soc_effective": "19-3033.00",
    "anchor_title": "Clinical Psychologists",
    "alpha": 0.2,
    "flagged": "Renamed to 19-3033.00 in O*NET 30.3 (Clinical and Counseling Psychologists)"
  },
  "Adolescent Medicine": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "21-1012.00",
    "anchor_soc_effective": "21-1012.00",
    "anchor_title": "Educational/Career Counselors",
    "alpha": 0.2
  },
  "Child Abuse Pediatrics": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "19-4092.00",
    "anchor_soc_effective": "19-4092.00",
    "anchor_title": "Forensic Science Technicians",
    "alpha": 0.2
  },
  "Peds Hospital Medicine": {
    "parent_soc": "29-1221.00",
    "tier": 2,
    "anchor_soc_csv": "11-9111.00",
    "anchor_soc_effective": "11-9111.00",
    "anchor_title": "Medical/Health Services Managers",
    "alpha": 0.2
  },
  "Child & Adolescent Psychiatry": {
    "parent_soc": "29-1223.00",
    "tier": 2,
    "anchor_soc_csv": "25-2054.00",
    "anchor_soc_effective": "25-2059.00",
    "anchor_title": "Special Education Teachers",
    "alpha": 0.2,
    "flagged": "Restructured in O*NET 30.3; use 25-2059.00 (Special Education Teachers, All Other)"
  },
  "Addiction Psychiatry": {
    "parent_soc": "29-1223.00",
    "tier": 2,
    "anchor_soc_csv": "21-1011.00",
    "anchor_soc_effective": "21-1011.00",
    "anchor_title": "Substance Abuse Counselors",
    "alpha": 0.2
  },
  "Forensic Psychiatry": {
    "parent_soc": "29-1223.00",
    "tier": 2,
    "anchor_soc_csv": "19-4092.00",
    "anchor_soc_effective": "19-4092.00",
    "anchor_title": "Forensic Science Technicians",
    "alpha": 0.2
  },
  "Geriatric Psychiatry": {
    "parent_soc": "29-1223.00",
    "tier": 2,
    "anchor_soc_csv": "21-1015.00",
    "anchor_soc_effective": "21-1015.00",
    "anchor_title": "Rehabilitation Counselors",
    "alpha": 0.2
  },
  "Consultation-Liaison Psychiatry": {
    "parent_soc": "29-1223.00",
    "tier": 2,
    "anchor_soc_csv": "11-9111.00",
    "anchor_soc_effective": "11-9111.00",
    "anchor_title": "Medical/Health Services Managers",
    "alpha": 0.2
  },
  "Addiction Medicine (Psych)": {
    "parent_soc": "29-1223.00",
    "tier": 2,
    "anchor_soc_csv": "21-1011.00",
    "anchor_soc_effective": "21-1011.00",
    "anchor_title": "Substance Abuse Counselors",
    "alpha": 0.2
  },
  "Surgical Critical Care": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "29-1126.00",
    "anchor_soc_effective": "29-1126.00",
    "anchor_title": "Respiratory Therapists",
    "alpha": 0.2
  },
  "Pediatric Surgery": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "25-2054.00",
    "anchor_soc_effective": "25-2059.00",
    "anchor_title": "Special Education Teachers",
    "alpha": 0.2,
    "flagged": "Restructured in O*NET 30.3; use 25-2059.00 (Special Education Teachers, All Other)"
  },
  "Complex Surgical Oncology": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Vascular Surgery": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "17-2112.00",
    "anchor_soc_effective": "17-2112.00",
    "anchor_title": "Industrial Engineers",
    "alpha": 0.2
  },
  "Hand Surgery (Surgery)": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "29-1123.00",
    "anchor_soc_effective": "29-1123.00",
    "anchor_title": "Physical Therapists",
    "alpha": 0.2
  },
  "Ortho / Sports Medicine": {
    "parent_soc": "29-1242.00",
    "tier": 2,
    "anchor_soc_csv": "29-9091.00",
    "anchor_soc_effective": "29-9091.00",
    "anchor_title": "Athletic Trainers",
    "alpha": 0.2
  },
  "Ortho / Spine": {
    "parent_soc": "29-1242.00",
    "tier": 2,
    "anchor_soc_csv": "17-2112.00",
    "anchor_soc_effective": "17-2112.00",
    "anchor_title": "Industrial Engineers",
    "alpha": 0.2
  },
  "Ortho / Hand": {
    "parent_soc": "29-1242.00",
    "tier": 2,
    "anchor_soc_csv": "29-1123.00",
    "anchor_soc_effective": "29-1123.00",
    "anchor_title": "Physical Therapists",
    "alpha": 0.2
  },
  "Ortho / Trauma": {
    "parent_soc": "29-1242.00",
    "tier": 2,
    "anchor_soc_csv": "29-2041.00",
    "anchor_soc_effective": "avg(29-2042.00,29-2043.00)",
    "anchor_title": "EMTs/Paramedics",
    "alpha": 0.2,
    "flagged": "Split into 29-2042.00 (EMTs) + 29-2043.00 (Paramedics) in O*NET 30.3; use average"
  },
  "Ortho / Pediatric": {
    "parent_soc": "29-1242.00",
    "tier": 2,
    "anchor_soc_csv": "25-2054.00",
    "anchor_soc_effective": "25-2059.00",
    "anchor_title": "Special Education Teachers",
    "alpha": 0.2,
    "flagged": "Restructured in O*NET 30.3; use 25-2059.00 (Special Education Teachers, All Other)"
  },
  "Ortho / Adult Reconstruction": {
    "parent_soc": "29-1242.00",
    "tier": 2,
    "anchor_soc_csv": "17-2112.00",
    "anchor_soc_effective": "17-2112.00",
    "anchor_title": "Industrial Engineers",
    "alpha": 0.2
  },
  "Ortho / MSK Oncology": {
    "parent_soc": "29-1242.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Otolaryngology (ENT)": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "29-1029.00",
    "anchor_soc_effective": "29-1029.00",
    "anchor_title": "Dentists, All Other",
    "alpha": 0.2
  },
  "ENT / Neurotology": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "17-2072.00",
    "anchor_soc_effective": "17-2072.00",
    "anchor_title": "Electronics Engineers",
    "alpha": 0.2
  },
  "ENT / Pediatric ENT": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "25-2054.00",
    "anchor_soc_effective": "25-2059.00",
    "anchor_title": "Special Education Teachers",
    "alpha": 0.2,
    "flagged": "Restructured in O*NET 30.3; use 25-2059.00 (Special Education Teachers, All Other)"
  },
  "ENT / Head & Neck Surg Onc": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "ENT / Facial Plastic": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "27-1013.00",
    "anchor_soc_effective": "27-1013.00",
    "anchor_title": "Fine Artists (Sculptors)",
    "alpha": 0.2
  },
  "ENT / Laryngology": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "29-1127.00",
    "anchor_soc_effective": "29-1127.00",
    "anchor_title": "Speech-Language Pathologists",
    "alpha": 0.2
  },
  "ENT / Rhinology": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "29-2034.00",
    "anchor_soc_effective": "29-2034.00",
    "anchor_title": "Radiologic Technologists",
    "alpha": 0.2
  },
  "Urology": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "17-2112.00",
    "anchor_soc_effective": "17-2112.00",
    "anchor_title": "Industrial Engineers",
    "alpha": 0.2
  },
  "Urology / Pediatric": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "25-2054.00",
    "anchor_soc_effective": "25-2059.00",
    "anchor_title": "Special Education Teachers",
    "alpha": 0.2,
    "flagged": "Restructured in O*NET 30.3; use 25-2059.00 (Special Education Teachers, All Other)"
  },
  "Urology / Female Pelvic/Recon": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "29-1123.00",
    "anchor_soc_effective": "29-1123.00",
    "anchor_title": "Physical Therapists",
    "alpha": 0.2
  },
  "Thoracic Surgery": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "17-2112.00",
    "anchor_soc_effective": "17-2112.00",
    "anchor_title": "Industrial Engineers",
    "alpha": 0.2
  },
  "Congenital Cardiac Surgery": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "17-2072.00",
    "anchor_soc_effective": "17-2072.00",
    "anchor_title": "Electronics Engineers",
    "alpha": 0.2
  },
  "Plastic Surgery": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "27-1013.00",
    "anchor_soc_effective": "27-1013.00",
    "anchor_title": "Fine Artists (Sculptors)",
    "alpha": 0.2
  },
  "Plastic / Hand Surgery": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "29-1123.00",
    "anchor_soc_effective": "29-1123.00",
    "anchor_title": "Physical Therapists",
    "alpha": 0.2
  },
  "Plastic / Craniofacial": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "17-2112.00",
    "anchor_soc_effective": "17-2112.00",
    "anchor_title": "Industrial Engineers",
    "alpha": 0.2
  },
  "Plastic / Microsurgery": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "51-9071.00",
    "anchor_soc_effective": "51-9071.00",
    "anchor_title": "Jewelers/Precious Stone Workers",
    "alpha": 0.2
  },
  "Colorectal Surgery": {
    "parent_soc": "29-1249.00",
    "tier": 2,
    "anchor_soc_csv": "17-2112.00",
    "anchor_soc_effective": "17-2112.00",
    "anchor_title": "Industrial Engineers",
    "alpha": 0.2
  },
  "EM / Medical Toxicology": {
    "parent_soc": "29-1214.00",
    "tier": 2,
    "anchor_soc_csv": "19-4092.00",
    "anchor_soc_effective": "19-4092.00",
    "anchor_title": "Forensic Science Technicians",
    "alpha": 0.2
  },
  "EM / Sports Medicine": {
    "parent_soc": "29-1214.00",
    "tier": 2,
    "anchor_soc_csv": "29-9091.00",
    "anchor_soc_effective": "29-9091.00",
    "anchor_title": "Athletic Trainers",
    "alpha": 0.2
  },
  "EM / Ultrasound": {
    "parent_soc": "29-1214.00",
    "tier": 2,
    "anchor_soc_csv": "29-2032.00",
    "anchor_soc_effective": "29-2032.00",
    "anchor_title": "Diagnostic Medical Sonographers",
    "alpha": 0.2
  },
  "EM / EMS-Prehospital": {
    "parent_soc": "29-1214.00",
    "tier": 2,
    "anchor_soc_csv": "29-2041.00",
    "anchor_soc_effective": "avg(29-2042.00,29-2043.00)",
    "anchor_title": "EMTs/Paramedics",
    "alpha": 0.2,
    "flagged": "Split into 29-2042.00 (EMTs) + 29-2043.00 (Paramedics) in O*NET 30.3; use average"
  },
  "EM / Disaster Medicine": {
    "parent_soc": "29-1214.00",
    "tier": 2,
    "anchor_soc_csv": "13-1061.00",
    "anchor_soc_effective": "11-9161.00",
    "anchor_title": "Emergency Management Directors",
    "alpha": 0.2,
    "flagged": "Wrong SOC family in O*NET 30.3; correct is 11-9161.00 (Emergency Management Directors)"
  },
  "EM / Wilderness Medicine": {
    "parent_soc": "29-1214.00",
    "tier": 2,
    "anchor_soc_csv": "29-2041.00",
    "anchor_soc_effective": "avg(29-2042.00,29-2043.00)",
    "anchor_title": "EMTs/Paramedics",
    "alpha": 0.2,
    "flagged": "Split into 29-2042.00 (EMTs) + 29-2043.00 (Paramedics) in O*NET 30.3; use average"
  },
  "EM / Hospice & Palliative": {
    "parent_soc": "29-1214.00",
    "tier": 2,
    "anchor_soc_csv": "21-1022.00",
    "anchor_soc_effective": "21-1022.00",
    "anchor_title": "Healthcare Social Workers",
    "alpha": 0.2
  },
  "EM / Critical Care (EMCCM)": {
    "parent_soc": "29-1214.00",
    "tier": 2,
    "anchor_soc_csv": "29-1126.00",
    "anchor_soc_effective": "29-1126.00",
    "anchor_title": "Respiratory Therapists",
    "alpha": 0.2
  },
  "EM / Administration": {
    "parent_soc": "29-1214.00",
    "tier": 2,
    "anchor_soc_csv": "11-9111.00",
    "anchor_soc_effective": "11-9111.00",
    "anchor_title": "Medical/Health Services Managers",
    "alpha": 0.2
  },
  "EM / Clinical Informatics": {
    "parent_soc": "29-1214.00",
    "tier": 2,
    "anchor_soc_csv": "15-1252.00",
    "anchor_soc_effective": "15-1252.00",
    "anchor_title": "Software Developers",
    "alpha": 0.2
  },
  "Anes / Critical Care": {
    "parent_soc": "29-1211.00",
    "tier": 2,
    "anchor_soc_csv": "29-1126.00",
    "anchor_soc_effective": "29-1126.00",
    "anchor_title": "Respiratory Therapists",
    "alpha": 0.2
  },
  "Anes / Pain Medicine": {
    "parent_soc": "29-1211.00",
    "tier": 2,
    "anchor_soc_csv": "29-1123.00",
    "anchor_soc_effective": "29-1123.00",
    "anchor_title": "Physical Therapists",
    "alpha": 0.2
  },
  "Anes / Cardiac": {
    "parent_soc": "29-1211.00",
    "tier": 2,
    "anchor_soc_csv": "29-2031.00",
    "anchor_soc_effective": "29-2031.00",
    "anchor_title": "Cardiovascular Technologists",
    "alpha": 0.2
  },
  "Anes / Pediatric": {
    "parent_soc": "29-1211.00",
    "tier": 2,
    "anchor_soc_csv": "25-2054.00",
    "anchor_soc_effective": "25-2059.00",
    "anchor_title": "Special Education Teachers",
    "alpha": 0.2,
    "flagged": "Restructured in O*NET 30.3; use 25-2059.00 (Special Education Teachers, All Other)"
  },
  "Anes / Neuroanesthesia": {
    "parent_soc": "29-1211.00",
    "tier": 2,
    "anchor_soc_csv": "17-2072.00",
    "anchor_soc_effective": "17-2072.00",
    "anchor_title": "Electronics Engineers",
    "alpha": 0.2
  },
  "Anes / Regional-Acute Pain": {
    "parent_soc": "29-1211.00",
    "tier": 2,
    "anchor_soc_csv": "29-2032.00",
    "anchor_soc_effective": "29-2032.00",
    "anchor_title": "Diagnostic Medical Sonographers",
    "alpha": 0.2
  },
  "Anes / Obstetric": {
    "parent_soc": "29-1211.00",
    "tier": 2,
    "anchor_soc_csv": "29-1161.00",
    "anchor_soc_effective": "29-1161.00",
    "anchor_title": "Nurse Midwives",
    "alpha": 0.2
  },
  "Anes / Perioperative Medicine": {
    "parent_soc": "29-1211.00",
    "tier": 2,
    "anchor_soc_csv": "11-9111.00",
    "anchor_soc_effective": "11-9111.00",
    "anchor_title": "Medical/Health Services Managers",
    "alpha": 0.2
  },
  "Neuroradiology": {
    "parent_soc": "29-1224.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Musculoskeletal Radiology": {
    "parent_soc": "29-1224.00",
    "tier": 2,
    "anchor_soc_csv": "29-9091.00",
    "anchor_soc_effective": "29-9091.00",
    "anchor_title": "Athletic Trainers",
    "alpha": 0.2
  },
  "Breast Imaging": {
    "parent_soc": "29-1224.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Pediatric Radiology": {
    "parent_soc": "29-1224.00",
    "tier": 2,
    "anchor_soc_csv": "25-2054.00",
    "anchor_soc_effective": "25-2059.00",
    "anchor_title": "Special Education Teachers",
    "alpha": 0.2,
    "flagged": "Restructured in O*NET 30.3; use 25-2059.00 (Special Education Teachers, All Other)"
  },
  "Abdominal/Body Imaging": {
    "parent_soc": "29-1224.00",
    "tier": 2,
    "anchor_soc_csv": "29-2034.00",
    "anchor_soc_effective": "29-2034.00",
    "anchor_title": "Radiologic Technologists",
    "alpha": 0.2
  },
  "Cardiothoracic Imaging": {
    "parent_soc": "29-1224.00",
    "tier": 2,
    "anchor_soc_csv": "29-2031.00",
    "anchor_soc_effective": "29-2031.00",
    "anchor_title": "Cardiovascular Technologists",
    "alpha": 0.2
  },
  "Interventional Radiology": {
    "parent_soc": "29-1224.00",
    "tier": 2,
    "anchor_soc_csv": "17-2112.00",
    "anchor_soc_effective": "17-2112.00",
    "anchor_title": "Industrial Engineers",
    "alpha": 0.2
  },
  "Nuclear Medicine": {
    "parent_soc": "29-1224.00",
    "tier": 3,
    "anchor_soc_csv": "29-2033.00",
    "anchor_soc_effective": "29-2033.00",
    "anchor_title": "Nuclear Medicine Technologists",
    "alpha": 0.4
  },
  "Radiation Oncology": {
    "parent_soc": "29-1224.00",
    "tier": 2,
    "anchor_soc_csv": "17-2199.00",
    "anchor_soc_effective": "17-2199.00",
    "anchor_title": "Engineers, All Other",
    "alpha": 0.2
  },
  "Surgical Pathology": {
    "parent_soc": "29-1222.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Cytopathology": {
    "parent_soc": "29-1222.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Dermatopathology (Path)": {
    "parent_soc": "29-1222.00",
    "tier": 2,
    "anchor_soc_csv": "27-1013.00",
    "anchor_soc_effective": "27-1013.00",
    "anchor_title": "Fine Artists (Sculptors)",
    "alpha": 0.2
  },
  "Neuropathology": {
    "parent_soc": "29-1222.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Forensic Pathology": {
    "parent_soc": "29-1222.00",
    "tier": 2,
    "anchor_soc_csv": "19-4092.00",
    "anchor_soc_effective": "19-4092.00",
    "anchor_title": "Forensic Science Technicians",
    "alpha": 0.2
  },
  "Clinical Pathology/Lab Medicine": {
    "parent_soc": "29-1222.00",
    "tier": 2,
    "anchor_soc_csv": "11-9121.00",
    "anchor_soc_effective": "11-9121.00",
    "anchor_title": "Natural Sciences Managers",
    "alpha": 0.2
  },
  "Hematopathology": {
    "parent_soc": "29-1222.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Clinical Chemistry": {
    "parent_soc": "29-1222.00",
    "tier": 2,
    "anchor_soc_csv": "19-2031.00",
    "anchor_soc_effective": "19-2031.00",
    "anchor_title": "Chemists",
    "alpha": 0.2
  },
  "Microbiology (Path)": {
    "parent_soc": "29-1222.00",
    "tier": 2,
    "anchor_soc_csv": "19-1022.00",
    "anchor_soc_effective": "19-1022.00",
    "anchor_title": "Microbiologists",
    "alpha": 0.2
  },
  "Blood Banking/Transfusion": {
    "parent_soc": "29-1222.00",
    "tier": 2,
    "anchor_soc_csv": "11-9121.00",
    "anchor_soc_effective": "11-9121.00",
    "anchor_title": "Natural Sciences Managers",
    "alpha": 0.2
  },
  "Molecular Genetic Pathology": {
    "parent_soc": "29-1222.00",
    "tier": 2,
    "anchor_soc_csv": "15-2051.00",
    "anchor_soc_effective": "15-2051.00",
    "anchor_title": "Data Scientists",
    "alpha": 0.2
  },
  "Clinical Informatics (Path)": {
    "parent_soc": "29-1222.00",
    "tier": 2,
    "anchor_soc_csv": "15-1252.00",
    "anchor_soc_effective": "15-1252.00",
    "anchor_title": "Software Developers",
    "alpha": 0.2
  },
  "Dermatopathology (Derm)": {
    "parent_soc": "29-1213.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Mohs/Procedural Dermatology": {
    "parent_soc": "29-1213.00",
    "tier": 2,
    "anchor_soc_csv": "51-9071.00",
    "anchor_soc_effective": "51-9071.00",
    "anchor_title": "Jewelers/Precious Stone Workers",
    "alpha": 0.2
  },
  "Pediatric Dermatology": {
    "parent_soc": "29-1213.00",
    "tier": 2,
    "anchor_soc_csv": "25-2054.00",
    "anchor_soc_effective": "25-2059.00",
    "anchor_title": "Special Education Teachers",
    "alpha": 0.2,
    "flagged": "Restructured in O*NET 30.3; use 25-2059.00 (Special Education Teachers, All Other)"
  },
  "Cosmetic Dermatology": {
    "parent_soc": "29-1213.00",
    "tier": 2,
    "anchor_soc_csv": "27-1013.00",
    "anchor_soc_effective": "27-1013.00",
    "anchor_title": "Fine Artists (Sculptors)",
    "alpha": 0.2
  },
  "Vascular Neurology/Stroke": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "29-2041.00",
    "anchor_soc_effective": "avg(29-2042.00,29-2043.00)",
    "anchor_title": "EMTs/Paramedics",
    "alpha": 0.2,
    "flagged": "Split into 29-2042.00 (EMTs) + 29-2043.00 (Paramedics) in O*NET 30.3; use average"
  },
  "Epilepsy/Clinical Neurophysiology": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "17-2072.00",
    "anchor_soc_effective": "17-2072.00",
    "anchor_title": "Electronics Engineers",
    "alpha": 0.2
  },
  "Neuromuscular Medicine": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Movement Disorders": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Behavioral Neurology/Neuropsychiatry": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "19-3031.00",
    "anchor_soc_effective": "19-3033.00",
    "anchor_title": "Clinical Psychologists",
    "alpha": 0.2,
    "flagged": "Renamed to 19-3033.00 in O*NET 30.3 (Clinical and Counseling Psychologists)"
  },
  "Neuro-oncology": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Headache Medicine": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "21-1015.00",
    "anchor_soc_effective": "21-1015.00",
    "anchor_title": "Rehabilitation Counselors",
    "alpha": 0.2
  },
  "Neuroimmunology/MS": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Autonomic Disorders": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "17-2072.00",
    "anchor_soc_effective": "17-2072.00",
    "anchor_title": "Electronics Engineers",
    "alpha": 0.2
  },
  "Sleep Medicine (Neuro)": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "29-2099.00",
    "anchor_soc_effective": "29-2099.00",
    "anchor_title": "Health Technologists, All Other",
    "alpha": 0.2
  },
  "Neurocritical Care": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "29-1126.00",
    "anchor_soc_effective": "29-1126.00",
    "anchor_title": "Respiratory Therapists",
    "alpha": 0.2
  },
  "Pain Medicine (Neuro)": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "29-1123.00",
    "anchor_soc_effective": "29-1123.00",
    "anchor_title": "Physical Therapists",
    "alpha": 0.2
  },
  "Hospice & Palliative (Neuro)": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "21-1022.00",
    "anchor_soc_effective": "21-1022.00",
    "anchor_title": "Healthcare Social Workers",
    "alpha": 0.2
  },
  "Clinical Informatics (Neuro)": {
    "parent_soc": "29-1217.00",
    "tier": 2,
    "anchor_soc_csv": "15-1252.00",
    "anchor_soc_effective": "15-1252.00",
    "anchor_title": "Software Developers",
    "alpha": 0.2
  },
  "Maternal-Fetal Medicine": {
    "parent_soc": "29-1218.00",
    "tier": 2,
    "anchor_soc_csv": "29-2032.00",
    "anchor_soc_effective": "29-2032.00",
    "anchor_title": "Diagnostic Medical Sonographers",
    "alpha": 0.2
  },
  "Reproductive Endocrinology/Infertility": {
    "parent_soc": "29-1218.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Gynecologic Oncology": {
    "parent_soc": "29-1218.00",
    "tier": 2,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.2
  },
  "Female Pelvic Med/Recon Surgery": {
    "parent_soc": "29-1218.00",
    "tier": 2,
    "anchor_soc_csv": "29-1123.00",
    "anchor_soc_effective": "29-1123.00",
    "anchor_title": "Physical Therapists",
    "alpha": 0.2
  },
  "Complex Family Planning": {
    "parent_soc": "29-1218.00",
    "tier": 2,
    "anchor_soc_csv": "21-1022.00",
    "anchor_soc_effective": "21-1022.00",
    "anchor_title": "Healthcare Social Workers",
    "alpha": 0.2
  },
  "Minimally Invasive Gyn Surgery": {
    "parent_soc": "29-1218.00",
    "tier": 2,
    "anchor_soc_csv": "17-2112.00",
    "anchor_soc_effective": "17-2112.00",
    "anchor_title": "Industrial Engineers",
    "alpha": 0.2
  },
  "Ophthalmology (general)": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "29-1041.00",
    "anchor_soc_effective": "29-1041.00",
    "anchor_title": "Optometrists",
    "alpha": 0.4
  },
  "Retina/Vitreous": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "29-2034.00",
    "anchor_soc_effective": "29-2034.00",
    "anchor_title": "Radiologic Technologists",
    "alpha": 0.4
  },
  "Glaucoma": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "17-2112.00",
    "anchor_soc_effective": "17-2112.00",
    "anchor_title": "Industrial Engineers",
    "alpha": 0.4
  },
  "Cornea/External Disease": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.4
  },
  "Oculoplastics": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "27-1013.00",
    "anchor_soc_effective": "27-1013.00",
    "anchor_title": "Fine Artists (Sculptors)",
    "alpha": 0.4
  },
  "Pediatric Ophthalmology/Strabismus": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "25-2054.00",
    "anchor_soc_effective": "25-2059.00",
    "anchor_title": "Special Education Teachers",
    "alpha": 0.4,
    "flagged": "Restructured in O*NET 30.3; use 25-2059.00 (Special Education Teachers, All Other)"
  },
  "Neuro-ophthalmology": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "19-1042.00",
    "anchor_soc_effective": "19-1042.00",
    "anchor_title": "Medical Scientists",
    "alpha": 0.4
  },
  "PM&R (general)": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "29-1123.00",
    "anchor_soc_effective": "29-1123.00",
    "anchor_title": "Physical Therapists",
    "alpha": 0.4
  },
  "Spinal Cord Injury": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "21-1015.00",
    "anchor_soc_effective": "21-1015.00",
    "anchor_title": "Rehabilitation Counselors",
    "alpha": 0.4
  },
  "Brain Injury": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "21-1015.00",
    "anchor_soc_effective": "21-1015.00",
    "anchor_title": "Rehabilitation Counselors",
    "alpha": 0.4
  },
  "Pain Medicine (PM&R)": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "29-1123.00",
    "anchor_soc_effective": "29-1123.00",
    "anchor_title": "Physical Therapists",
    "alpha": 0.4
  },
  "Sports Medicine (PM&R)": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "29-9091.00",
    "anchor_soc_effective": "29-9091.00",
    "anchor_title": "Athletic Trainers",
    "alpha": 0.4
  },
  "Pediatric Rehab": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "25-2054.00",
    "anchor_soc_effective": "25-2059.00",
    "anchor_title": "Special Education Teachers",
    "alpha": 0.4,
    "flagged": "Restructured in O*NET 30.3; use 25-2059.00 (Special Education Teachers, All Other)"
  },
  "Neuromuscular (PM&R)": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "17-2072.00",
    "anchor_soc_effective": "17-2072.00",
    "anchor_title": "Electronics Engineers",
    "alpha": 0.4
  },
  "EMG/Electrodiagnostics": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "17-2072.00",
    "anchor_soc_effective": "17-2072.00",
    "anchor_title": "Electronics Engineers",
    "alpha": 0.4
  },
  "Cancer Rehab": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "21-1015.00",
    "anchor_soc_effective": "21-1015.00",
    "anchor_title": "Rehabilitation Counselors",
    "alpha": 0.4
  },
  "Preventive Med/Public Health": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "19-1041.00",
    "anchor_soc_effective": "19-1041.00",
    "anchor_title": "Epidemiologists",
    "alpha": 0.4
  },
  "Occupational Medicine": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "13-1041.00",
    "anchor_soc_effective": "13-1041.00",
    "anchor_title": "Compliance Officers",
    "alpha": 0.4
  },
  "Aerospace Medicine": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "17-2011.00",
    "anchor_soc_effective": "17-2011.00",
    "anchor_title": "Aerospace Engineers",
    "alpha": 0.4
  },
  "Undersea & Hyperbaric Medicine": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "17-2199.00",
    "anchor_soc_effective": "17-2199.00",
    "anchor_title": "Engineers, All Other",
    "alpha": 0.4
  },
  "Addiction Medicine (Prev)": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "21-1011.00",
    "anchor_soc_effective": "21-1011.00",
    "anchor_title": "Substance Abuse Counselors",
    "alpha": 0.4
  },
  "Clinical Informatics (Prev)": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "15-1252.00",
    "anchor_soc_effective": "15-1252.00",
    "anchor_title": "Software Developers",
    "alpha": 0.4
  },
  "Medical Toxicology (Prev)": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "19-4092.00",
    "anchor_soc_effective": "19-4092.00",
    "anchor_title": "Forensic Science Technicians",
    "alpha": 0.4
  },
  "Medical Genetics (general)": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "29-9092.00",
    "anchor_soc_effective": "29-9092.00",
    "anchor_title": "Genetic Counselors",
    "alpha": 0.4
  },
  "Biochemical Genetics": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "19-2031.00",
    "anchor_soc_effective": "19-2031.00",
    "anchor_title": "Chemists",
    "alpha": 0.4
  },
  "Molecular Genetics": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "15-2051.00",
    "anchor_soc_effective": "15-2051.00",
    "anchor_title": "Data Scientists",
    "alpha": 0.4
  },
  "Clinical Cytogenetics": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "29-2010.00",
    "anchor_soc_effective": "29-2011.00",
    "anchor_title": "Clinical Lab Technologists",
    "alpha": 0.4,
    "flagged": "Group code in O*NET 30.3; use 29-2011.00 (Medical and Clinical Laboratory Technologists)"
  },
  "Pain Medicine (multidisciplinary)": {
    "parent_soc": "29-1229.00",
    "tier": 3,
    "anchor_soc_csv": "29-1123.00",
    "anchor_soc_effective": "29-1123.00",
    "anchor_title": "Physical Therapists",
    "alpha": 0.4
  }
} as const;
