/** ACGME-accredited specialties and common subspecialties (alphabetical). */
export const ACGME_SPECIALTIES = [
  "Addiction Psychiatry",
  "Adolescent Medicine",
  "Allergy and Immunology",
  "Anatomic and Clinical Pathology",
  "Anesthesiology",
  "Blood Banking/Transfusion Medicine",
  "Cardiovascular Disease",
  "Child and Adolescent Psychiatry",
  "Child Neurology",
  "Clinical Biochemical Genetics",
  "Clinical Cardiac Electrophysiology",
  "Clinical Genetics and Genomics",
  "Clinical Informatics",
  "Clinical Neurophysiology",
  "Colon and Rectal Surgery",
  "Critical Care Medicine",
  "Cytopathology",
  "Dermatology",
  "Dermatopathology",
  "Developmental-Behavioral Pediatrics",
  "Emergency Medical Services",
  "Emergency Medicine",
  "Endocrinology, Diabetes and Metabolism",
  "Epilepsy",
  "Family Medicine",
  "Female Pelvic Medicine and Reconstructive Surgery",
  "Forensic Pathology",
  "Forensic Psychiatry",
  "Gastroenterology",
  "Geriatric Medicine",
  "Geriatric Psychiatry",
  "Gynecologic Oncology",
  "Hand Surgery",
  "Hematology",
  "Hematology and Oncology",
  "Hospice and Palliative Medicine",
  "Infectious Disease",
  "Internal Medicine",
  "Internal Medicine-Pediatrics",
  "Interventional Cardiology",
  "Interventional Radiology",
  "Maternal-Fetal Medicine",
  "Medical Genetics and Genomics",
  "Medical Microbiology",
  "Medical Toxicology",
  "Molecular Genetic Pathology",
  "Neonatal-Perinatal Medicine",
  "Nephrology",
  "Neurocritical Care",
  "Neurological Surgery",
  "Neurology",
  "Neuropathology",
  "Neuroradiology",
  "Neurotology",
  "Nuclear Medicine",
  "Nuclear Radiology",
  "Obstetrics and Gynecology",
  "Occupational and Environmental Medicine",
  "Ophthalmology",
  "Orthopaedic Sports Medicine",
  "Orthopaedic Surgery",
  "Otolaryngology - Head and Neck Surgery",
  "Pain Medicine",
  "Pediatric Anesthesiology",
  "Pediatric Cardiology",
  "Pediatric Critical Care Medicine",
  "Pediatric Emergency Medicine",
  "Pediatric Endocrinology",
  "Pediatric Gastroenterology",
  "Pediatric Hematology-Oncology",
  "Pediatric Hospital Medicine",
  "Pediatric Infectious Diseases",
  "Pediatric Nephrology",
  "Pediatric Pulmonology",
  "Pediatric Radiology",
  "Pediatric Rehabilitation Medicine",
  "Pediatric Surgery",
  "Pediatric Urology",
  "Physical Medicine and Rehabilitation",
  "Plastic Surgery",
  "Plastic Surgery-Integrated",
  "Preventive Medicine",
  "Psychiatry",
  "Pulmonary Disease",
  "Radiation Oncology",
  "Radiology - Diagnostic",
  "Rheumatology",
  "Sleep Medicine",
  "Spinal Cord Injury Medicine",
  "Sports Medicine",
  "Surgery",
  "Surgical Critical Care",
  "Thoracic Surgery",
  "Transplant Hepatology",
  "Undersea and Hyperbaric Medicine",
  "Urology",
  "Vascular Neurology",
  "Vascular Surgery",
  "Other",
] as const;

export type AcgmeSpecialty = (typeof ACGME_SPECIALTIES)[number];

export const CAREER_STAGES = [
  "Medical Student",
  "Resident",
  "Fellow",
  "Early Attending",
  "Mid-Career Attending",
  "Senior Attending",
  "Retired",
] as const;

export type CareerStage = (typeof CAREER_STAGES)[number];

export function filterSpecialties(query: string): AcgmeSpecialty[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...ACGME_SPECIALTIES];
  return ACGME_SPECIALTIES.filter((s) => s.toLowerCase().includes(q));
}

export function isValidSpecialty(value: string): value is AcgmeSpecialty {
  return (ACGME_SPECIALTIES as readonly string[]).includes(value);
}

export function isValidCareerStage(value: string): value is CareerStage {
  return (CAREER_STAGES as readonly string[]).includes(value);
}
