export const FISCMAK_TERMS_VERSION = "2026-05-29";
export const FISCMAK_TERMS_LAST_UPDATED = "May 29, 2026";

export type LegalSection = {
  id: string;
  title: string;
  paragraphs: string[];
  subsections?: { title: string; paragraphs: string[] }[];
};

export const TERMS_OF_SERVICE_SECTIONS: LegalSection[] = [
  {
    id: "intro",
    title: "Welcome",
    paragraphs: [
      'Welcome to FISCMAK. Please read these Terms and Conditions ("Terms", "Agreement") carefully before using the website, interactive tools, and artificial intelligence features (collectively, the "Platform") operated by FISCMAK, LLC ("Company", "we", "us", or "our").',
      'By accessing or using the Platform, completing our interactive onboarding flow, or checking an "I Accept" box, you agree to be legally bound by these Terms. If you disagree with any part of the terms, you may not access the service.',
    ],
  },
  {
    id: "onboarding",
    title: "1. Account Onboarding, Registration, and User Representation",
    paragraphs: [],
    subsections: [
      {
        title: "1.1 The Onboarding Process",
        paragraphs: [
          'Access to and full utility of the Platform is contingent upon the completion of our interactive, step-by-step onboarding flow (the "Onboarding Flow"). The Onboarding Flow utilizes a sequential, card-by-card user interface designed to collect professional criteria, user preferences, and career data necessary to initialize your personalized account profile.',
        ],
      },
      {
        title: "1.2 Affirmative Consent and Electronic Signature",
        paragraphs: [
          "By progressing through the Onboarding Flow, interacting with the sequential cards, and affirmatively clicking the final initialization or acceptance button, you expressly acknowledge and agree that your final affirmative action constitutes an electronic signature and provides explicit, legally binding consent to these Terms and Conditions and our Privacy Policy.",
        ],
      },
      {
        title: "1.3 Truthfulness and Accuracy of Data",
        paragraphs: [
          "The utility of the Platform relies heavily on the integration of user-submitted materials and data points. By submitting information, documentation, clinical career histories, or preferences through any card or input field during or after onboarding, you represent and warrant that all data provided is true, accurate, current, and complete.",
        ],
      },
    ],
  },
  {
    id: "privacy",
    title: "2. Data Privacy, Institutional Accounts, and Clinical Competency Disclosures",
    paragraphs: [],
    subsections: [
      {
        title: "2.1 Absolute Confidentiality of Direct Chat Communications",
        paragraphs: [
          'All interactive dialogues, conversational inputs, personal reflections, and career development queries occurring within the platform\'s direct chat interface (the "Direct Chat") are strictly confidential. The Company does not sell, lease, or share granular text logs or individual chat histories with any third party, including your affiliated medical school, hospital system, residency program, or employer (collectively, "Affiliated Institutions"). Everything you input, upload, or confirm within the confidential chat interface is treated as private career narrative evidence accessible solely by you.',
        ],
      },
      {
        title: "2.2 Institutional B2B Accounts and Summative Reporting",
        paragraphs: [
          'If your account is provisioned under, funded by, or explicitly tied to an institutional B2B enterprise license (an "Institutional Account"), you acknowledge that the platform generates structured, aggregated performance data to assist in professional milestone tracking. The transmission of data to your Affiliated Institution is strictly governed by the following parameters:',
          "No Chat Exposure: Raw chat histories, specific questions asked, and granular text strings are completely excluded from institutional visibility.",
          "Summative Data Only: The platform compiles and delivers only objective, high-level summative reports, cohort benchmarks, milestone competencies, and logged task validations (e.g., validated hours, career lattice progress).",
        ],
      },
      {
        title: "2.3 Institutional Use in CCC and Review Meetings",
        paragraphs: [
          "For users under an Institutional Account (such as medical students, residents, and fellows), you expressly acknowledge and agree that the authorized summative reports generated by the platform are designed to align with validated ACGME and AAMC competency frameworks. Consequently, your Affiliated Institution will utilize these platform-generated summative reports, milestone trackers, and aggregated cohort data during formal evaluation cycles, including Clinical Competency Committee (CCC) review sessions and semi-annual or annual residency/fellowship program review meetings.",
        ],
      },
    ],
  },
  {
    id: "cohort",
    title: "3. Cohort Data Masking and Protection",
    paragraphs: [],
    subsections: [
      {
        title: "3.1 Anonymization and Masking of Small Cohorts",
        paragraphs: [
          "To prevent the accidental re-identification of individual users within specialized, low-volume training environments, the Platform enforces strict mathematical data masking protocols on all institutional reporting dashboards. For any residency track, fellowship program, or medical student rotation containing fewer than five (5) active users in a single reporting cohort, individual milestone progress and objective metrics are automatically pooled into a broader department-wide or institutional-level data stream. No specific user's career lattice data or logged invisible work hours will be isolated or identifiable within small cohort brackets, preserving absolute anonymity.",
        ],
      },
    ],
  },
  {
    id: "ip",
    title: "4. Intellectual Property and Output Ownership",
    paragraphs: [],
    subsections: [
      {
        title: "4.1 Ownership of Generated Career Documents and Academic Portfolios",
        paragraphs: [
          'The Platform utilizes proprietary artificial intelligence models to synthesize user inputs, clinical logs, and narrative tracking notes into structured career development assets (including, but not limited to, Curriculum Vitae (CVs), Cover Letters, Federal Dossiers, and Academic Portfolios, collectively referred to as "Generated Academic Outputs").',
        ],
      },
      {
        title: "4.2 Assignment of Rights",
        paragraphs: [
          "You retain full intellectual property rights, title, and ownership over all original raw materials and personal documentation uploaded to the platform. The Company hereby assigns all rights, title, and intellectual property interests in the structural and textual arrangement of the Generated Academic Outputs entirely to you, the individual user. You possess the permanent, irrevocable, and unrestricted right to download, export, edit, print, publish, or present your CV or Portfolio for any academic, community, or professional advancement purpose.",
        ],
      },
      {
        title: "4.3 Perpetual Individual Access",
        paragraphs: [
          "Your ownership of your Generated Academic Outputs is independent of your institutional affiliation. If your relationship with an Affiliated Institution terminates, or if an institutional enterprise license expires, your personal right to access and export your generated career advancement assets remains intact.",
        ],
      },
    ],
  },
  {
    id: "disclaimers",
    title: "5. Platform Limitations and Disclaimers",
    paragraphs: [],
    subsections: [
      {
        title: "5.1 Verification and Compliance Audits",
        paragraphs: [
          "The Company reserves the right, but does not assume the obligation, to review, verify, or audit any information or credentials submitted. If you provide any information that is untrue, inaccurate, misleading, or violates third-party intellectual property or compliance standards, the Company reserves the absolute right to suspend or terminate your account immediately without liability.",
        ],
      },
      {
        title: "5.2 Liability Limitation",
        paragraphs: [
          "FISCMAK, LLC is a platform for career mapping, narrative development, and administrative organization. The Company is not responsible for institutional employment decisions, residency matching outcomes, CCC promotional evaluations, or academic grading structures executed by your Affiliated Institution.",
        ],
      },
    ],
  },
];
